// Generated HOMEii Music Flow localization dictionary.
// Keep keys stable. Translate only the string values.
const messages = Object.freeze({
  "ui.action_menu_labels": "Noms des actions sous les icônes",
  "ui.a_guided_music_wizard": "Un assistant musical guidé",
  "ui.a_radio_station": "Une station de radio",
  "ui.accent_color": "Couleur d'accentuation",
  "ui.actions": "actions",
  "ui.actions_2": "Actions",
  "ui.active_days": "Jours actifs",
  "ui.active_player_helper": "Entité du lecteur actif",
  "ui.active_player_helper_must_be_an_input_text_entity": "L'entité du lecteur actif doit être un input_text entity",
  "ui.active_players": "Lecteurs actifs",
  "ui.add": "Ajouter",
  "ui.add_to_queue": "Ajouter à la file d'attente",
  "ui.add_to_selection": "Ajouter à la sélection",
  "ui.added_to_liked": "Ajouter aux titres aimés",
  "ui.added_to_music_assistant_liked": "Ajouter aux favoris de Music Assistant",
  "ui.added_to_queue": "Ajouté à la file d'attente",
  "ui.added_to_studio_queue": "Ajouté à la file d'attente du Studio",
  "ui.adds_motion_to_the_background_layers_subtle_keeps_it_calm_strong_is_noti": "Ajoute une animation à l'arrière-plan. Subtil est doux, Fort est perceptible, et Extrême donne un mouvement plus marqué.",
  "ui.adds_to_the_current_volume_only_during_announcements_then_restores_the_p": "Augmente le volume actuel seulement pendant les annonces, puis rétablit le volume précédent",
  "ui.after_run": "Après exécution",
  "ui.album": "Album",
  "ui.albums": "Albums",
  "ui.all_albums": "Tous les Albums",
  "ui.all_artists": "Tous les Artistes",
  "ui.all_countries": "Tous les Pays",
  "ui.all_player_groups_disconnected": "Tous les groupes de lecteurs déconnectés",
  "ui.all_players": "Tous les lecteurs",
  "ui.all_players_2": "tous les lecteurs",
  "ui.all_podcasts": "Tous les Podcasts",
  "ui.all_tracks": "Toutes les pistes",
  "ui.always_visible": "Toujours visible",
  "ui.announce": "Faire une annonce",
  "ui.announce_to_all_players": "Faire une annonce à tous les lecteurs",
  "ui.announcement": "Annonce",
  "ui.announcement_failed_with_error": "Échec de l'annonce{error}",
  "ui.announcement_language": "Langue des annonces",
  "ui.announcement_presets": "Annonces prédéfinies",
  "ui.announcement_sent_to_player": "Annonce envoyée à {player}",
  "ui.announcement_studio": "studio d'annonces",
  "ui.announcement_studio_2": "Studio d'annonces",
  "ui.announcement_target": "Lecteur cible",
  "ui.announcement_to_player_preview": "Annoncer sur {player}: {preview}",
  "ui.announcement_volume_boost": "Augmentation du volume pendant les annonces",
  "ui.announcements": "Annonces",
  "ui.appearance": "Apparence",
  "ui.alphabetical": "Alphabétique",
  "ui.auxiliary_button": "Bouton auxiliaire",
  "ui.auxiliary_button_action": "Action du bouton auxiliaire",
  "ui.auxiliary_button_entity": "Entité du bouton auxiliaire",
  "ui.auxiliary_button_icon": "Icône du bouton auxiliaire",
  "ui.auxiliary_button_name": "Nom du bouton auxiliaire",
  "ui.auxiliary_buttons": "Boutons auxiliaires",
  "ui.apply_group": "Créer le groupe",
  "ui.apply_schedule": "Appliquer la programmation",
  "ui.artist": "Artiste",
  "ui.artist_radio": "Radio de l'artiste",
  "ui.artists": "Artistes",
  "ui.artwork": "Pochette d'album",
  "ui.artwork_swipe": "Défilement de la couverture",
  "ui.ascending": "Croissant",
  "ui.at_least_one_player_must_stay_selected": "Au minimum un lecteur doit être sélectionner",
  "ui.australia": "Australie",
  "ui.auto_chooses_mobile_or_tablet_based_on_actual_width": "Sélectionne automatiquement l'affichage mobile ou tablette selon la largeur réelle de l'appareil",
  "ui.auto_cloud_default": "Auto / Cloud par défaut",
  "ui.auto_extracts_colors_from_the_current_artwork_and_keeps_the_effect_subtl": "Extrait automatiquement les couleurs de la pochette actuelle et garde un effet subtil. Le mode Fort rend la palette plus riche et lumineuse.",
  "ui.auto_leaves_home_assistant_cloud_voice_defaults_untouched_manual_choices": "Auto ne modifie pas la configuration par défaut de l'assistant vocal Home Assistant Cloud. Sélection Manuelle envoie une langue spécifique",
  "ui.available": "Disponible",
  "ui.back": "Retour",
  "ui.back_2": "Retour",
  "ui.back_to_countries": "Retour aux Pays",
  "ui.back_to_queue": "Retour vers la file d'attente",
  "ui.background_motion": "Mouvement de l'arrière-plan",
  "ui.behavior": "Comportement",
  "ui.browse_covers": "Parcourir les pochettes d'album",
  "ui.browse_playlists_artists_albums_and_radio": "Parcourir les listes de lectures, artistes, albums et radio",
  "ui.browser_players": "Parcourir les lecteurs",
  "ui.build_custom_mix": "Créer un mix personnalisé",
  "ui.building_studio_mix": "Création du mix Studio...",
  "ui.button": "Bouton",
  "ui.by_mood": "Par ambiance",
  "ui.cache_duration_in_milliseconds_for_selected_data_requests": "Durée du cache en millisecondes pour les requêtes de données sélectionnées",
  "ui.cache_ttl": "Cache TTL",
  "ui.calm": "Calme",
  "ui.canada": "Canada",
  "ui.cancel": "Annuler",
  "ui.cancel_2": "Annuler",
  "ui.cancel_selection": "Annuler la sélection",
  "ui.card_configuration": "Configuration de la carte",
  "ui.card_height": "Hauteur de la carte",
  "ui.card_height_in_pixels": "Hauteur de la carte en pixels.",
  "ui.card_settings_are_managed_from_the_visual_editor": "Les paramètres de la carte sont configurés à partir de l'éditeur visuel",
  "ui.change_song": "Changer de chanson",
  "ui.change_track": "Changer de piste",
  "ui.chill_mix": "Mix Détente",
  "ui.choose_a_country_or_all_countries_to_browse_every_country_inside_the_rad": "Choisir un pays ou définir sur Tous les pays pour parcourir tous les pays de l'onglet Radio",
  "ui.choose_a_queue_position": "Choisir une position dans la file d'attente",
  "ui.choose_a_source_player": "Choisir la source du lecteur",
  "ui.choose_a_target_player": "Choisir le lecteur cible",
  "ui.choose_at_least_one_player": "Choisir au moins un lecteur",
  "ui.choose_icons_text_or_both_for_the_footer": "Choisir des icônes, du texte ou les deux pour le pied de page.",
  "ui.choose_music_assistant_players_only_the_in_card_pinning_list_shows_only": "Choisissez uniquement des lecteurs MA. La liste d’épinglage affiche seulement les lecteurs MA afin d’éviter toute confusion.",
  "ui.choose_one_clear_option": "Choisissez une seule option",
  "ui.choose_player": "Choisir un lecteur",
  "ui.choose_something_from_the_quick_shelf_or_tap_the_wand_for_a_random_playl": "Choisissez une liste de lecture rapide ou cliquez sur la baguette magique pour une liste aléatoire",
  "ui.choose_source": "Choisissez la source",
  "ui.choose_target": "Choisissez la cible",
  "ui.choose_target_player": "Choisissez le lecteur cible",
  "ui.choose_the_accent_color_for_the_mobile_layout": "Choisissez une couleur d'accentuation pour la disposition mobile.",
  "ui.choose_the_music": "Choisissez votre musique",
  "ui.choose_the_small_buttons_shown_under_the_song_title_timer_appears_first": "Choisissez les petits boutons affichés sous le titre de la chanson. En hébreu, le minuteur apparaît en premier afin d’être placé du côté droit.",
  "ui.choose_the_source_first_playback_will_use_the_current_target": "Choisissez la source en premier. La lecture démarrera sur la cible actuelle.",
  "ui.choose_where_to_play": "Choisissez où faire jouer",
  "ui.choose_whether_artwork_swipe_changes_track_or_browses_covers": "Choisir si le défilement de la pochette d'album change la piste ou parcourt les pochettes.",
  "ui.choose_whether_settings_are_controlled_from_the_in_card_ui_or_from_the_c": "Choisir si les paramètres sont contrôlés à partir de l'éditeur visuel intégré ou à partir la configuration de la carte dans le tableau de bord",
  "ui.choose_which_actions_appear_in_the_main_bar": "Choisir quelles actions apparaissent sur la barre d'outil principale",
  "ui.choose_which_days_the_auto_night_mode_window_applies_to": "Choisir quels jours sont concernés par le mode Sombre Auto",
  "ui.choose_which_icons_appear_in_the_quick_action_row": "Choisir quelles icônes apparaissent dans la barre d'actions rapides. Tout réinitialiser demande une confirmation avant de déconnecter tous les lecteurs actifs",
  "ui.choose_which_players_appear_as_tiles_in_the_room": "Choisir quels lecteurs apparaissent comme des tuiles dans les pièces",
  "ui.choose_which_players_stay_in_the_current_control_selection": "Choisissez les lecteurs à conserver dans la sélection actuelle.",
  "ui.choose_which_tabs_are_available_in_the_library_screen": "Choisir quels onglets sont visibles sur la page de bibliothèque",
  "ui.choose_who_is_controlled": "Choisir quel lecteurs sont contrôlés",
  "ui.choosing_visual_disables_the_in_card_settings_screen": "Visuel désactive la page de configuration de la carte intégrée",
  "ui.clean_all": "Tout réinitialiser",
  "ui.clean_all_confirm_action": "Tout réinitialisé",
  "ui.clean_all_confirm_copy": "Cette action déconnectera tous les lecteurs actifs, arrêtera la lecture et supprimera leur file d'attente. Continuer?",
  "ui.clean_all_confirm_title": "Réinitialiser tous les lecteurs?",
  "ui.clean_the_studio_wall": "Réinitialiser le Studio",
  "ui.clear": "Réinitialiser",
  "ui.clear_queue": "Réinitialiser la file d'attente",
  "ui.clear_search": "Réinitialiser la recherche",
  "ui.clone_queue": "Dupliquer la file d'attente",
  "ui.close": "Fermer",
  "ui.collapse_compact_player": "Réduire le lecteur compact",
  "ui.compact_mode": "Mode compact",
  "ui.configure_ready_made_announcement_phrases": "Configurer des phrases prédéfinies d'annonces.",
  "ui.connect_this_device": "Connecter cet appareil",
  "ui.connect_this_device_2": "Connecter cet appareil",
  "ui.connected": "Connecté",
  "ui.connected_2": "Connecté",
  "ui.connected_players": "lecteurs connectés",
  "ui.connected_players_2": "Lecteurs connectés",
  "ui.connecting": "Connexion",
  "ui.connecting_2": "Connexion...",
  "ui.confirm": "Confirmer",
  "ui.connection_and_behavior": "Connection et Comportement",
  "ui.connects_directly_from_this_card_using_sendspin": "Connecter directement à partir de cette carte en utilisant SendspinConnecter",
  "ui.continue": "Continuer",
  "ui.continue_2": "Continuer",
  "ui.continue_from_recent_music_assistant_activity": "Continuer à partir des activités récentes de Music Assistant",
  "ui.continue_listening": "Continuer la lecture",
  "ui.continue_what_was_played_recently": "Continuer la lecture récente",
  "ui.control_whether_the_card_background_moves_gently_and_how_strong_the_moti": "Définit si l'arrière-plan est légèrement animé et la force de l'animation",
  "ui.controlling": "Lecteurs sélectionnés",
  "ui.could_not_build_quick_mix_from_the_current_song": "Échec de la création du Mix Rapide à partir de cette chanson",
  "ui.could_not_build_studio_mix": "Échec de la création du mix Studio",
  "ui.could_not_choose_media": "Échec de la sélection du média",
  "ui.could_not_clone_the_queue": "Échec de la duplication de la file d'attente",
  "ui.could_not_find_music": "Aucune musique trouvée",
  "ui.could_not_play_label": "Échec de la lecture: {label}",
  "ui.could_not_start_chill_mix": "Échec de la lecture du mix Détente",
  "ui.could_not_start_playback": "Impossible de démarrer la lecture",
  "ui.could_not_start_playback_2": "Impossible de démarrer la lecture",
  "ui.could_not_start_playback_in_studio": "Impossible démarrer la lecture dans le Studio",
  "ui.could_not_start_quick_mix": "Impossible de démarrer le Mix Rapide",
  "ui.could_not_start_radio_playback": "Impossible de démarrer la radio",
  "ui.could_not_transfer_the_queue": "Échec du transfert de la file d'attente",
  "ui.could_not_update_active_player_helper": "Impossible d'actualiser l'entité du lecteur actif",
  "ui.create_schedule": "Créer une programmation",
  "ui.current_path": "Chemin actuel",
  "ui.custom": "Personnalisé",
  "ui.dark": "Sombre",
  "ui.delete_scene": "Supprimer la scène",
  "ui.delete_schedule": "Supprimer la programmation",
  "ui.descending": "Décroissant",
  "ui.dictate": "Dicter",
  "ui.disabled": "Désactivé",
  "ui.disables_blur_animations_dynamic_backgrounds_and_heavy_shadows_recommend": "Désactive le flou, les animations, l'arrière-plan dynamique et les ombres. Recommandé pour les appareils Nest et les tablettes moins performantes",
  "ui.disconnect": "Déconnecter",
  "ui.disconnect_all": "Tout déconnecter",
  "ui.disconnect_groups": "Déconnecter les groupes",
  "ui.disconnect_player_groups": "Déconnecter les groupes de lecteurs",
  "ui.disconnect_this_device": "Déconnecter cet appareil",
  "ui.disconnected": "Déconnecté",
  "ui.disconnecting": "Déconnexion",
  "ui.disconnecting_player_groups": "Déconnexion des groupes de lecteurs...",
  "ui.discover": "Découvertes",
  "ui.down": "Bas",
  "ui.dynamic_theme": "Thème dynamique",
  "ui.edit_schedule": "Modifier la programmation",
  "ui.enable": "Activer",
  "ui.enable_or_disable_the_footer_search_button": "Activer/désactiver la barre de recherche inférieure.",
  "ui.enable_or_disable_the_studio_button_in_the_footer_bar": "Activer/désactiver le bouton Studio dans la barre inférieure.",
  "ui.enable_the_floating_home_shortcut_button": "Activer le bouton flottant du raccourci pour le menu principal.",
  "ui.enabled": "Activé",
  "ui.enables_switching_to_local_liked_mode": "Autoriser le mode local pour les titres préférés.",
  "ui.end_time": "Heure de fin",
  "ui.excluded_players": "Lecteurs exclus",
  "ui.energetic": "Énergique",
  "ui.energy_and_rhythm": "Énergie et rythme",
  "ui.enter_an_announcement_first": "Entrer d'abord une annonce",
  "ui.example_quiet_jazz_greek_music_workout": "Exemple: smooth jazz, musique Grèque, entrainement",
  "ui.existing_content": "Contenu existant",
  "ui.expand_player": "Maximiser le lecteur",
  "ui.extract_colors_from_the_current_artwork_and_apply_them_to_the_interface": "Extraire les couleurs à partir de la pochette actuelle et appliquer celles-ci à l'interface.",
  "ui.extreme": "Extrême",
  "ui.fallback_for_setups_that_need_an_alternate_queue_service_path": "Fallback pour les configurations nécessitant un chemin alternatif pour le service de file d’attente.",
  "ui.fallback_mode": "Mode Fallback",
  "ui.family_friendly": "Adapté pour toute la famille",
  "ui.favorite": "Favoris",
  "ui.favorite_action_failed": "Échec de l'ajout aux favoris",
  "ui.favorite_action_sent": "Action d'ajout aux favoris envoyées",
  "ui.favorite_center": "centre des favoris",
  "ui.favorite_center_2": "Centre des Favoris",
  "ui.favorite_radio": "Radio préférée",
  "ui.favorite_updated": "Favoris actualisés",
  "ui.favorites_and_liked_music": "Favoris et titres préférés",
  "ui.feature_detection_player_context_and_this_device_playback_tools": "Détection des fonctionnalités, contexte du lecteur et outils de lecture sur cet appareil.",
  "ui.find_music": "Trouver de la musique",
  "ui.finding_music": "Recherche de musique",
  "ui.fixed": "Fixe",
  "ui.flow_mix": "FLOW Mix",
  "ui.font_scale": "Ratio de la police",
  "ui.font_size": "Taille de la police",
  "ui.footer_search": "Barre de recherche inférieure",
  "ui.footer_style": "Style de la barre inférieure",
  "ui.footer_style_2": "Style de la barre inférieure",
  "ui.for_example_lovelace_home_or_any_other_home_assistant_path": "Par exemple /lovelace/home ou n'importe quel chemin Home Assistant.",
  "ui.for_weaker_displays_turns_off_heavy_blur_animations_dynamic_theme_extrac": "Pour les écrans de faible performance: désactive le flou agressif, les animations, l'extraction dynamique du thème et les animations de l'arrière-plan.",
  "ui.france": "France",
  "ui.free_style": "Free style",
  "ui.free_style_quiet_jazz_greek_music_workout": "Free style: smooth jazz, musique Grèque, entrainement...",
  "ui.fresh_start": "Nouvelle écoute",
  "ui.fresh_start_2": "Nouvelle écoute",
  "ui.fri": "Ven",
  "ui.friendly_and_simple": "Amical et simple",
  "ui.from": "De",
  "ui.general": "Général",
  "ui.general_and_display": "Général et Affichage",
  "ui.germany": "Allemagne",
  "ui.global_scale_for_every_interface_font_1_is_the_default_size": "Résolution globale de la police sur toute l'interface. 1 est la taille par défaut.",
  "ui.greece": "Grèce",
  "ui.grid": "Grille",
  "ui.group": "Groupe",
  "ui.group_cleared": "Groupe réinitialisé",
  "ui.group_cleared_2": "Groupe réinitialisé",
  "ui.group_speakers": "Groupes d'enceintes",
  "ui.group_speakers_2": "Groupes d'enceintes",
  "ui.group_updated": "Groupe actualisé",
  "ui.group_volume": "Volume du groupe",
  "ui.group_volume_up_energetic_mix": "Groupe, augmenter le volume, mix énergique",
  "ui.grouped_players": "Lecteurs groupés",
  "ui.hebrew": "Hébreu",
  "ui.history": "Historique",
  "ui.history_tabs": "Onglet Historique",
  "ui.home": "Accueil",
  "ui.home_party_night_presets": "Accueil, fête, préréglage de nuit",
  "ui.home_path": "Chemin d'Accueil",
  "ui.home_scene_prepared": "Scène d'accueil préparée",
  "ui.home_shortcut": "Raccourci d'accueil",
  "ui.home_shortcut_path": "Chemin du raccourci d'accueil",
  "ui.icon_and_text": "Icône et texte",
  "ui.icon_only": "Icône seulement",
  "ui.icon_plus_text": "Icône + texte",
  "ui.idle": "En veille",
  "ui.idle_2": "En veille",
  "ui.in_card_ui": "UI intégrée",
  "ui.includes_the_custom_theme_mode_from_the_in_card_settings_screen": "Inclure le mode de thème personnalisé depuis l’écran des paramètres intégrés.",
  "ui.info": "Info",
  "ui.israel": "Israel",
  "ui.israeli": "Israeli",
  "ui.italy": "Italie",
  "ui.items": "items",
  "ui.join_selected_players": "Grouper les lecteurs sélectionnés",
  "ui.kids": "Kids",
  "ui.language": "Langue",
  "ui.larger_lyrics": "Agrandir les paroles",
  "ui.layout_adapted_to_height": "Disposition adaptée à la hauteur",
  "ui.layout_mode": "Style de disposition",
  "ui.leave_empty_if_the_card_should_use_home_assistant_only": "Laisser vide si la carte doit utiliser Home Assistant seulement.",
  "ui.library": "Bibliothèque",
  "ui.library_2": "Bibliothèque",
  "ui.library_pages": "Sections de la bibliothèque",
  "ui.default_library_layout": "Affichage par défaut de la bibliothèque",
  "ui.choose_how_library_pages_open_grid_or_list_can_still_be_changed_manually": "Choisissez la disposition de la bibliothèque. Vous pouvez toujours basculer entre Grille et Liste dans la bibliothèque.",
  "ui.library_radio": "Bibliothèque de radios",
  "ui.library_surprise": "Bibliothèque surprise",
  "ui.library_tabs": "Onglet Bibliothèque",
  "ui.library_tabs_2": "Onglet Bibliothèque",
  "ui.light": "Clair",
  "ui.like": "Aimer",
  "ui.like_2": "Aimer",
  "ui.like_3": "Aimer",
  "ui.liked": "Titres préférés",
  "ui.liked_mode": "Mode des titres préférés",
  "ui.liked_sync": "Synchronisation des titres préférés",
  "ui.list": "Liste",
  "ui.listening": "Écoute en cours...",
  "ui.loading": "Chargement...",
  "ui.loading_favorites": "Chargement des favoris...",
  "ui.loading_library": "Chargement de la bibliothèque...",
  "ui.loading_lyrics": "Chargement des paroles...",
  "ui.loading_players": "Chargement des lecteurs...",
  "ui.loading_queue": "Chargement de la file d'attente...",
  "ui.loading_recent_items": "Chargement des items récents...",
  "ui.loading_schedules": "Chargement des programmations...",
  "ui.local": "Local",
  "ui.local_favorites": "Favoris locaux",
  "ui.local_favorites_2": "Favoris locaux",
  "ui.local_mode_is_only_meaningful_when_local_likes_are_enabled": "Le mode Local n'est applicable que si les titres préférés locaux sont activés.",
  "ui.low_light_listening": "Écoute en faible luminosité",
  "ui.low_volume_and_quiet_mix": "Mix calme à faible volume",
  "ui.lower_volume_mood": "Ambiance douce",
  "ui.lyrics": "Paroles",
  "ui.lyrics_earlier": "Paroles précédentes",
  "ui.lyrics_font_size": "Taille de police des paroles",
  "ui.lyrics_later": "Paroles suivantes",
  "ui.lyrics_timing": "Synchronisation des paroles",
  "ui.lyrics_unavailable_right_now": "Paroles indisponibles actuellement",
  "ui.ma_favorite_action_failed_with_error": "Échec de l'ajout aux favoris de Music Assistant{error}",
  "ui.ma_interface_path": "Chemin de l'interface MA",
  "ui.main_bar": "Barre principale",
  "ui.main_bar_items": "Items de la barre principale",
  "ui.main_bar_items_2": "Items de la barre principale",
  "ui.main_opacity": "Transparence générale",
  "ui.mainly_relevant_on_larger_layouts": "Applicable principalement aux affichages larges.",
  "ui.matches_the_microphone_setting_from_the_in_card_settings_screen": "Utilise le même réglage de microphone que les paramètres intégrés.",
  "ui.media": "Média",
  "ui.media_2": "Média",
  "ui.media_actions": "Actions des Médias",
  "ui.media_layout": "Disposition des Médias",
  "ui.media_selected_target": "Sélectionné: {media} ? Cible: {target}",
  "ui.menu": "Menu",
  "ui.message": "Message",
  "ui.microphone": "Microphone",
  "ui.microphone_2": "Microphone",
  "ui.microphone_is_disabled": "Le microphone est désactivé.",
  "ui.missing_url": "URL manquante",
  "ui.mobile": "Mobile",
  "ui.mon": "Lun",
  "ui.mood_style_or_free_text": "Ambiance, style ou texte libre",
  "ui.more_info": "Plus d'infos",
  "ui.more_info_is_unavailable_for_this_player": "Infos indisponibles pour ce lecteur.",
  "ui.morning": "Matin",
  "ui.morning_mix": "Mix matinal",
  "ui.move_to_next": "Lire ensuite",
  "ui.move_to_position": "Déplacer à la position",
  "ui.music": "Musique",
  "ui.music_assistant_required": "Music Assistant requis",
  "ui.music_assistant_config_entry_id_if_you_want_direct_integration_lookup_th": "ID de l’entrée de configuration Music Assistant, si vous souhaitez une détection directe de l’intégration via Home Assistant.",
  "ui.music_assistant_config_entry_was_not_found": "L'entrée de configuration de Music Assistant n'a pas été trouvé.",
  "ui.music_assistant_token": "Music Assistant token",
  "ui.music_assistant_url": "Music Assistant URL",
  "ui.music_hub": "hub musical",
  "ui.music_hub_2": "Hub Musical",
  "ui.mute": "Sourdine",
  "ui.mute_command_failed": "Échec de la mise en sourdine",
  "ui.my_studio_scene": "Ma scène du Studio",
  "ui.name_or_keyword": "Nom ou mot-clé",
  "ui.name_this_studio_scene": "Nommer cette scène du Studio...",
  "ui.netherlands": "Pays-bas",
  "ui.new_schedule": "Nouvelle programmation",
  "ui.new_wake_schedule": "Nouveau démarrage programmé",
  "ui.newest": "Les plus récents",
  "ui.next": "Suivant",
  "ui.next_track_failed": "Impossible de passer à la piste suivante",
  "ui.night": "Nuit",
  "ui.night_end_time": "Heure de la fin de la nuit",
  "ui.night_mode": "Mode sombre",
  "ui.night_mode_auto_window": "Mode sombre automatique {start}-{end}",
  "ui.night_mode_days": "Jours actifs du mode sombre",
  "ui.night_mode_is_always_on": "Mode sombre toujours actif",
  "ui.night_mode_is_off": "Mode sombre désactivé",
  "ui.night_mode_is_off_until_you_choose_another_mode": "Mode sombre désactivé jusqu'à changement.",
  "ui.night_mode_stays_on_until_you_choose_another_mode": "Mode sombre activé jusqu'à changement.",
  "ui.night_schedule_updated": "Programmation du mode sombre mise à jour",
  "ui.night_start_time": "Heure du début de la nuit",
  "ui.no_active_media": "Aucun média actif",
  "ui.no_active_players": "Aucun lecteur actif",
  "ui.no_available_players": "Aucun lecteur disponible",
  "ui.no_content_found": "Aucun contenu trouvé",
  "ui.no_dynamic_player_groups_to_disconnect": "Aucun groupe de lecteurs à déconnecter",
  "ui.no_extra_ma_players": "Aucun lecteur MA supplémentaire",
  "ui.no_extra_ma_players_2": "Aucun lecteur MA supplémentaire",
  "ui.no_favorites_found": "Aucun favori trouvé",
  "ui.no_liked_media_yet": "Aucun titre préféré actuellement",
  "ui.no_liked_tracks_to_play": "Aucun titre préféré à jouer",
  "ui.no_light_entities_found": "Aucune entité lumière trouvée",
  "ui.no_lyrics_found": "Aucune parole trouvée",
  "ui.no_matching_content_was_found": "Aucun contenu correspondant trouvé",
  "ui.no_media_found": "Aucun média trouvé",
  "ui.no_media_found_for_this_search": "Aucun média trouvé pour cette recherche",
  "ui.no_mix_content_found": "Aucun contenu de mix trouvé",
  "ui.no_music_assistant_players_were_found_check_music_assistant_and_media_pl": "Aucun lecteur Music Assistant ont été trouvé. Vérifier Music Assistant et les entités media_player.",
  "ui.no_music_assistant_players_were_found_for_pinning": "Aucun lecteur Music Assistant trouvé à épingler",
  "ui.no_next_track_in_queue": "Aucune chanson restant dans la liste d'attente",
  "ui.no_player_groups_to_disconnect": "Aucun groupe de lecteurs à déconnecter",
  "ui.no_player_light_pairs_yet": "Aucune paire lecteur-lumière actuellement",
  "ui.no_player_selected": "Aucun lecteur sélectionné",
  "ui.no_players_found": "Aucun lecteur trouvé",
  "ui.no_players_found_yet": "Aucun lecteur trouvé actuellement",
  "ui.no_playlists_found": "Aucune liste de lecture trouvée",
  "ui.no_queue": "Aucune file d'attente",
  "ui.no_queue_item_to_rebuild": "Aucun item de file d'attente à reconstruire",
  "ui.no_queue_to_clone": "Aucune file d'attente à dupliquer",
  "ui.no_radio_browser_countries_found": "Aucun pays trouvé dans le gestionnaire de radios",
  "ui.no_radio_stations_found": "Aucune station de radio trouvée",
  "ui.no_recent_listening_yet": "Aucune lecture récente actuellement",
  "ui.no_results": "Aucun résultat",
  "ui.no_results_found": "Aucun résultat trouvé",
  "ui.no_saved_studio_scenes_yet": "Aucun Studio enregistré actuellement",
  "ui.no_scheduled_start_is_active": "Aucune programmation n'est active",
  "ui.no_selected_tracks_to_play": "Aucune piste sélectionnée à jouer",
  "ui.no_sleep_timer_is_active": "Aucune minuterie de veille n'est active",
  "ui.no_speech_was_captured": "Aucune parole n'a été capturée",
  "ui.no_target_players_available": "Aucun lecteur cible disponible",
  "ui.no_target_players_available_2": "Aucun lecteur cible disponible",
  "ui.no_tts_service_or_entity_is_configured": "Aucun service TTS ou entité configuré",
  "ui.no_wake_schedules_yet": "Aucune démarrage programmé actuellement",
  "ui.none": "Aucun",
  "ui.nothing_is_playing_right_now": "Rien n'est en lecture présentement",
  "ui.nothing_playing": "Aucune lecture",
  "ui.now_playing": "Joue présentement",
  "ui.now_playing_2": "Joue présentement",
  "ui.off": "Éteint",
  "ui.off_2": "Éteint",
  "ui.off_disables_it_on_keeps_it_active_and_auto_follows_the_configured_time": "Désactivé coupe la fonction, Activé la maintient active et Auto suit la plage horaire configurée.",
  "ui.oldest": "Les plus vieux",
  "ui.on": "Actif",
  "ui.one_tap_prepares_players_grouping_volume_and_content_save_your_own_curre": "Taper une fois prépare les lecteurs, groupes, volume et contenu. Enregistre votre Studio actuel comme étant une scène locale.",
  "ui.only_actions_for_the_current_target_are_shown_here": "Seules les actions concernant la cible actuelle sont affichées ici.",
  "ui.only_music_assistant_players_are_shown_here_browser_and_local_sendspin_p": "Seuls les lecteurs de Music Assistant sont affichés ici. Les lecteurs Web et Sendspin locaux sont cachés pour afin d'éviter la confusion.",
  "ui.only_needed_when_using_a_direct_music_assistant_url": "Nécessaire seulement lorsque l'URL directe de Music Assistant est utilisée.",
  "ui.opacity_for_popups_and_overlays": "Transparence des popups et des superpositions.",
  "ui.opacity_for_the_main_card_background": "Transparence de l'arrière-plan de la page principale.",
  "ui.open_full_interface": "Ouvrir l'interface complète",
  "ui.open_full_queue": "Afficher la file d'attente complète",
  "ui.open_interface_in": "Ouvrir l'interface dans",
  "ui.open_ma": "Ouvrir MA",
  "ui.open_music_assistant": "Ouvrir Music Assistant",
  "ui.open_music_assistant_2": "Ouvrir Music Assistant?",
  "ui.open_music_assistant_on_this_device_to_activate_the_browser_player": "Ouvrir Music Assistant sur cet appareil pour activer le lecteur Web",
  "ui.open_player_picker": "Ouvrir le sélecteur de lecteur",
  "ui.open_queue": "Afficher la file d'attente",
  "ui.open_saved_songs": "Afficher les chansons enregistrées",
  "ui.open_the_full_music_assistant_interface": "Ouvrir l'interface complète de Music Assistant?",
  "ui.open_the_full_music_assistant_interface_2": "Ouvrir l'interface complète de Music Assistant",
  "ui.opening_studio_library": "Ouverture de la bibliothèque du Studio",
  "ui.opening_timers": "Minuterie d'ouverture",
  "ui.option": "Option",
  "ui.optional": "Optionnel",
  "ui.optional_2": "Optionnel",
  "ui.optional_entity_used_for_an_external_favorite_button": "Entité optionnelle utilisée pour le bouton de favoris externes.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for": "Entrée input_text optionnel mis à jour avec l’entity_id du lecteur actif pour les automatisations et les modèles.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for_2": "Entrée input_text optionnel mis à jour avec l’entity_id du lecteur actif pour les automatisations et les modèles.",
  "ui.other": "Autre",
  "ui.other_players": "Autres lecteurs",
  "ui.party": "Fête",
  "ui.path_used_when_opening_the_music_assistant_interface": "Chemin utilisé pour ouvrir l'interface de Music Assistant.",
  "ui.pause": "Pause",
  "ui.paused": "En pause",
  "ui.per_device_in_card": "Par appareil / intégré à la carte",
  "ui.performance_mode": "Mode performance",
  "ui.performance_mode_for_weak_devices": "Mode performance pour les appareils moins performants.",
  "ui.performance_profile": "Profil de performance",
  "ui.performance_profile_helper": "Choisissez le profil de performance pour les effets visuels. Ultra Lite réduit la transparence, le flou, les pochettes dynamiques et les animations pour les appareils peu puissants.",
  "ui.pick_a_mood_or_type_your_own_style_studio_will_search_music_assistant_an": "Choisissez une ambiance ou tapez votre propre style. Studio cherchera dans Music Assistant et créera une file d'attente.",
  "ui.pinned": "Épinglé",
  "ui.pinned_players": "Lecteurs épinglés",
  "ui.play": "Lecture",
  "ui.play_2": "Lecture",
  "ui.play_a_few_tracks_and_they_will_appear_here": "Lisez quelques titres et ils apparaîtront ici.",
  "ui.play_a_saved_list": "Lire une liste enregistrée",
  "ui.play_all": "Tout lire",
  "ui.play_an_artist": "Lire un artiste",
  "ui.play_artwork_action": "Action sur la pochette",
  "ui.play_everywhere": "Lire partout",
  "ui.play_next": "Lire ensuite",
  "ui.play_next_and_clear_queue": "Lire ensuite et vider la file d'attente",
  "ui.play_now": "Lire maintenant",
  "ui.play_now_and_clear_queue": "Lire maintenant et vider la file d'attente",
  "ui.play_pause": "Lecture / Pause",
  "ui.play_queue_radio_or_remove_favorites_directly_from_studio": "Lire, ajouter à la file d’attente, lancer la radio ou retirer des favoris directement depuis le Studio.",
  "ui.play_selected": "Lire la sélection",
  "ui.playback_command_failed": "Impossible d’exécuter la commande de lecture",
  "ui.playback_command_failed_2": "Impossible d’exécuter la commande de lecture",
  "ui.playback_started": "Lecture démarrée",
  "ui.player": "lecteur",
  "ui.player_2": "Lecteur",
  "ui.player_count_many": "{count} lecteurs",
  "ui.player_count_one": "1 lecteur",
  "ui.player_groups_could_not_be_disconnected": "Le groupe de lecteurs n'a pu être déconnecté",
  "ui.player_is_pinned_from_settings": "Le lecteur est épinglé à partir des paramètres",
  "ui.player_is_ready": "Le lecteur est prêt",
  "ui.player_is_ready_nothing_is_playing_right_now": "Le lecteur est prêt - Rien en cours de lecture actuellement",
  "ui.player_order": "Ordre des lecteurs",
  "ui.player_on_this_device": "Lecteur sur cet appareil",
  "ui.player_selected": "Lecteur sélectionné",
  "ui.player_settings_and_dsp_presets_stay_read_only_until_music_assistant_exp": "Les paramètres du lecteur et les préréglages DSP restent en lecture seule jusqu’à ce que Music Assistant fournisse un schéma fiable pour ce lecteur.",
  "ui.player_sort": "Tri des lecteurs",
  "ui.players": "Lecteurs",
  "ui.players_queue_and_groups": "Lecteurs, file d'attente et groupes",
  "ui.playing": "En cours de lecture",
  "ui.playing_a_random_playlist": "Lecture d'une liste de lecture aléatoire",
  "ui.playing_a_random_radio_station": "Lecture d'une station de radio aléatoire",
  "ui.playing_on": "En cours de lecture sur",
  "ui.playing_on_2": "En cours de lecture sur",
  "ui.playlist": "Liste de lecture",
  "ui.playlists": "Listes de lecture",
  "ui.podcast": "Podcast",
  "ui.podcasts": "Podcasts",
  "ui.popup_opacity": "Transparence du popup",
  "ui.preset_message": "Message prédéfini",
  "ui.previous": "Précédent",
  "ui.primary": "Principale",
  "ui.primary_target": "Cible principale",
  "ui.pro_tools": "Outils Pro",
  "ui.queue": "File d'attente",
  "ui.queue_2": "File d'attente",
  "ui.queue_action_failed": "Échec de l'action sur la file d'attente",
  "ui.queue_action_is_not_available_for_this_player": "L'action sur la file d'attente est indisponible sur ce lecteur",
  "ui.queue_actions": "Actions de la file d'attente",
  "ui.queue_cleared": "File d'attente vidée",
  "ui.queue_cleared_and_item_moved_next": "File d'attente vidée et élément déplacé en position suivante ",
  "ui.queue_cloned": "File d'attente dupliquée",
  "ui.queue_cockpit": "centre de contrôle de la file d'attente",
  "ui.queue_cockpit_2": "Centre de contrôle de la file d'attente",
  "ui.queue_is_empty": "La file d'attente est vide",
  "ui.queue_is_unavailable_for_this_player": "La file d'attente est indisponible sur ce lecteur",
  "ui.queue_item": "Éléments de la file d'attente",
  "ui.queue_item_id_is_not_ready_yet_refresh_the_queue_and_try_again": "L'ID d'élément pour la file d'attente n'est pas prêt. Actualisez la file d'attente et réessayez.",
  "ui.queue_results": "Résultats de la file d'attente",
  "ui.queue_transferred": "File d'attente transférée",
  "ui.queues_refreshed": "Files d'attente actualisées",
  "ui.quick_actions": "Actions rapides",
  "ui.quick_actions_2": "Actions rapides",
  "ui.quick_mix": "Mix rapide",
  "ui.quick_mix_started": "Mix rapide démarré",
  "ui.quick_play": "Lecture rapide",
  "ui.radio": "Radio",
  "ui.radio_browser": "Radio Browser",
  "ui.radio_browser_countries": "Parcourir par pays",
  "ui.radio_browser_country": "Parcourir par pays",
  "ui.radio_browser_country_2": "Parcourir par pays",
  "ui.radio_mode_is_not_available_for_this_media_type": "Le mode radio n'est pas disponible pour ce type de média",
  "ui.radio_mode_started": "Mode radio démarré",
  "ui.radio_station_changed": "Station de radio changée",
  "ui.radio_stations": "Stations de radio",
  "ui.random": "Aléatoire",
  "ui.random_gentle_morning_mix": "Mix matinal aléatoire",
  "ui.random_playlist": "Liste de lecture aléatoire",
  "ui.random_radio": "Radio aléatoire",
  "ui.ready": "Prêt",
  "ui.ready_to_play": "Prêt à lire",
  "ui.recent": "Récent",
  "ui.recent_continue": "Récent / Reprendre",
  "ui.recent_listening": "lecture récente",
  "ui.recent_track": "Piste récente",
  "ui.recently_added": "Récemment ajouté",
  "ui.recently_played": "Récemment lu",
  "ui.recently_played_2": "Récemment lu",
  "ui.recommendations_will_appear_once_homeii_flow_sees_your_queue_or_recent_l": "Les recommendations apparaîtront lorsque HOMEii Flow verra votre liste d'attente et vos lectures récentes.",
  "ui.recommended": "Recommandés",
  "ui.recommended_format_hh_mm_such_as_06_00_crossing_midnight_is_supported": "Format recommandé: HH:MM, par exemple 06:00. Le passage après minuit est pris en charge.",
  "ui.recommended_format_hh_mm_such_as_22_00": "Format recommandé: HH:MM, par exemple 22:00.",
  "ui.recommended_playlist": "Liste de lecture recommandée",
  "ui.recommended_track": "Piste recommandé",
  "ui.reconnects_when_you_return_to_this_dashboard": "Se connecte à nouveau lorsque vous retournez sur ce tableau de bord",
  "ui.refresh": "Actualiser",
  "ui.remember_as_this_device": "Mémoriser comme cet appareil",
  "ui.remove": "Retirer",
  "ui.remove_from_selection": "Retirer de la sélection",
  "ui.removed_from_liked": "Retiré des titres préférés",
  "ui.removed_from_music_assistant_liked": "Retiré des titres préférés sur Music Assistant",
  "ui.reorder_queue": "Réorganiser la file d'attente",
  "ui.repeat": "Répéter",
  "ui.repeat_all": "Tout répéter",
  "ui.repeat_off": "Répétition désactivée",
  "ui.repeat_one": "Répéter la piste",
  "ui.reset": "Réinitialiser",
  "ui.reset_lyrics_font_size": "Réinitialiser la taille de police",
  "ui.reset_lyrics_timing": "Réinitialiser la synchronisation des paroles",
  "ui.results": "Résultats",
  "ui.rtl": "RTL",
  "ui.sat": "Sam",
  "ui.save_current_target": "Enregistrer la cible actuelle",
  "ui.save_schedule": "Enregistrer la programmation",
  "ui.scene_players_are_not_available": "Les lecteurs de Scène sont indisponibles",
  "ui.scene_presets": "scènes prédéfinies",
  "ui.scene_presets_2": "Scènes Prédéfinies",
  "ui.scenes": "Scènes",
  "ui.scales_interface_icons_without_changing_button_sizes": "Ajuster la taille des icônes de l'interface sans changer la taille des boutons ni la disposition.",
  "ui.scheduled_start": "Démarrage programmé",
  "ui.scheduled_start_activated_label": "Démarrage programmé activé: {label}",
  "ui.scheduled_start_cleared": "Démarrage programmé désactivé",
  "ui.scheduled_start_failed": "Échec du démarrage programmé",
  "ui.scheduled_start_saved": "Démarrage programmé enregistré",
  "ui.scheduled_starts_active_count": "{count} démarrages programmés actifs",
  "ui.schedules": "Programmation",
  "ui.search": "Recherche",
  "ui.search_and_choose_play_next_add_radio_or_like": "Rechercher et choisissez Lire, Lire ensuite, Ajouter, Radio ou Aimer.",
  "ui.search_everything": "Rechercher partout...",
  "ui.search_failed": "Échec de la recherche",
  "ui.search_in_queue": "Rechercher dans la file d'attente",
  "ui.search_queue_and_library": "Rechercher dans la file d'attente et la bibliothèque...",
  "ui.search_the_library": "Rechercher dans la bibliothèque...",
  "ui.search_tracks_albums_artists_and_playlists": "Rechercher des pistes, albums, artistes ou listes de lecture",
  "ui.searching": "Recherche...",
  "ui.searching_library": "Recherche dans la bibliothèque...",
  "ui.searching_smart_selection": "Recherche d'une sélection intelligente...",
  "ui.seek": "Navigation",
  "ui.select": "Selectionner",
  "ui.select_lights": "Sélectionnez une ou plusieurs lumières",
  "ui.select_player": "Sélectionnez un lecteur",
  "ui.select_2": "Sélectionner",
  "ui.select_a_player_first": "Sélectionnez d'abord un lecteur",
  "ui.select_at_least_one_studio_player": "Sélectionnez au moins un lecteur Studio",
  "ui.select_at_least_two_players_to_create_a_group": "Sélectionnez au moins deux lecteurs pour créer un groupe",
  "ui.selected": "Sélectionné",
  "ui.selected_music": "Musique sélectionnée",
  "ui.selected_player": "Lecteur sélectionné",
  "ui.selected_player_2": "Lecteur sélectionné",
  "ui.selected_player_3": "Lecteur sélectionné",
  "ui.selected_players_at_comfortable_volume": "Lecteurs sélectionnés à volume confortable",
  "ui.selected_playlist": "Liste de lecture sélectionnée",
  "ui.send_a_short_voice_message_or_announcement_url": "Envoyer un court message ou un URL d'annonce.",
  "ui.send_a_voice_message": "Envoyer un message vocal",
  "ui.send_announcement": "Envoyer l'annonce",
  "ui.sendspin_and_diagnostics": "Sendspin et diagnostics",
  "ui.set_sleep_timer": "Régler la minuterie de mise en veille",
  "ui.set_volume": "Régler le volume",
  "ui.set_the_visual_order_of_quick_actions": "Réorganiser. Seules les actions rapides sélectionnées sont affichées ; les éléments non sélectionnés sont ignorés.",
  "ui.settings": "Paramètres",
  "ui.settings_section_announcements": "Annonces",
  "ui.settings_section_display": "Affichage",
  "ui.settings_section_music_assistant": "Music Assistant",
  "ui.settings_section_players_library": "Lecteurs et bibliothèque",
  "ui.settings_section_quick_actions_bar": "Actions rapides et barre",
  "ui.settings_section_smart_home": "Maison intelligente et économiseur d'écran",
  "ui.settings_section_voice_assistant": "Assistant vocal",
  "ui.settings_source": "Source des paramètres",
  "ui.show_ma_button": "Afficher le bouton MA",
  "ui.show_or_hide_the_inline_next_track_row_in_now_playing": "Afficher ou masquer la piste suivante dans Lecture en cours.",
  "ui.show_theme_toggle": "Afficher le sélecteur de thème",
  "ui.show_up_next": "Afficher la section À suivre",
  "ui.show_up_next_2": "Afficher la section À suivre",
  "ui.shows_a_standalone_compact_player_tile_with_artwork_basic_controls_volum": "Affiche une tuile de lecteur compacte autonome avec la pochette, les contrôles de base, le volume et un bouton pour agrandir l’interface.",
  "ui.shuffle": "Aléatoire",
  "ui.shuffle_all": "Tout lire en aléatoire",
  "ui.shuffle_favorites": "Lecture aléatoire des favoris",
  "ui.shuffle_play": "Lecture aléatoire",
  "ui.skipped_to_up_next": "Passé à la piste suivante",
  "ui.sleep_timer": "Minuterie de mise en veille",
  "ui.sleep_timer_2": "Minuterie de mise en veille",
  "ui.sleep_timer_active_remaining": "Minuterie de mise en veille: {remaining}",
  "ui.sleep_timer_added_minutes": "{minutes} minutes ajoutées à la minuterie",
  "ui.sleep_timer_and_morning_playback": "Minuterie de mise en veille et démarrage programmé",
  "ui.sleep_timer_and_scheduled_playback": "Minuterie de mise en veille et démarrage programmé",
  "ui.sleep_timer_cleared": "Minuterie de mise en veille effacée",
  "ui.sleep_timer_finished": "Minuterie de mise en veille terminée",
  "ui.sleep_timer_presets": "Préréglages de minuterie de mise en veille",
  "ui.sleep_timer_set_for_15_minutes": "Mise en veille programmée dans 15 minutes",
  "ui.sleep_timer_set_minutes": "Mise en veille programmée dans {minutes} minutes",
  "ui.sleep_timer_updated_minutes": "Mise en veille re-programmée dans {minutes} minutes",
  "ui.smaller_lyrics": "Paroles plus petites",
  "ui.smart": "Intelligent",
  "ui.smart_mix": "mix intelligent",
  "ui.smart_mix_builder": "Générateur de mix intelligent",
  "ui.smart_voice_selection": "Sélection vocale intelligente",
  "ui.soft_and_relaxed": "Doux et relaxant",
  "ui.soft_relaxed_music": "Musique relaxante, douce",
  "ui.some_players_could_not_be_stopped_or_cleared": "Certains lecteurs n'ont pu être arrêté ou vidé",
  "ui.songs_around_an_artist": "Chansons d'un artiste",
  "ui.sort": "Trier",
  "ui.sort_ascending": "Par ordre croissant",
  "ui.sort_descending": "Par ordre décroissant",
  "ui.source_queue": "Source de la file d'attente",
  "ui.spain": "Espagne",
  "ui.speak_to_target_players": "Communiquer dans les lecteurs cibles",
  "ui.start_radio_mode": "Démarrer le mode radio",
  "ui.start_time": "Heure du début",
  "ui.start_time_2": "Heure du début",
  "ui.started_on_selected_player": "Démarré sur les lecteurs sélectionnés",
  "ui.starting_a_chill_mix": "Démarrage d'un mix chill",
  "ui.starting_quick_mix": "Démarrage du Mix Rapide...",
  "ui.stations": "stations",
  "ui.stay_active": "Rester actif",
  "ui.stays_active": "Reste actif",
  "ui.stop_all": "Tout arrêter",
  "ui.stop_all_players": "Arrêter tous les lecteurs",
  "ui.stop_command_failed": "Échec de la commande Arrêter",
  "ui.stop_playback_clear_queues_and_disconnect_groups": "Arrête la lecture, vide la file d'attente et déconnecte les groupes",
  "ui.stopped_all_players_cleared_playlists_and_disconnected_groups": "Lecteurs arrêtés, file d'attente vidée et groupes déconnectés.",
  "ui.stops_this_browser_player": "Arrête ce lecteur Web",
  "ui.strong": "Fort",
  "ui.studio": "Studio",
  "ui.studio_closed": "Studio fermé",
  "ui.studio_media_action_failed": "Échec de l'action du Studio",
  "ui.studio_mix_started": "Mix Studio démarré",
  "ui.studio_opened": "Studio ouvert",
  "ui.studio_pro": "studio pro",
  "ui.studio_pro_2": "Studio Pro",
  "ui.studio_scene": "Scène Studio",
  "ui.studio_scene_deleted": "Scène Studio supprimée",
  "ui.studio_scene_saved": "Scène Studio enregistrée",
  "ui.studio_scene_was_not_found": "La scène Studio n'a pas été trouvé",
  "ui.studio_search": "rechercher studio",
  "ui.studio_shortcut": "Raccourci Studio",
  "ui.subtle": "Subtil",
  "ui.sun": "Dim",
  "ui.surprise_me": "Surprenez moi",
  "ui.sync": "Synchronisation",
  "ui.sync_lyrics": "Synchroniser les paroles",
  "ui.tablet": "Tablette",
  "ui.tap_to_start_a_sleep_timer": "Toucher pour démarrer une minuterie de mise en veille",
  "ui.target_players": "Lecteurs cibles",
  "ui.target_queue": "File d'attente cible",
  "ui.text_announcements_use_home_assistant_tts_into_the_selected_music_assist": "Les annonces textuelles utilisent le TTS de Home Assistant sur le lecteur Music Assistant sélectionné. Les annonces par URL utilisent la lecture d’annonces de Music Assistant.",
  "ui.text_only": "Texte seulement",
  "ui.text_tone": "Couleur du texte",
  "ui.theme": "Thème",
  "ui.theme_2": "Thème",
  "ui.theme_mode": "Mode du thème",
  "ui.theme_toggle": "Sélecteur de thème",
  "ui.theme_toggle_2": "Sélecteur de thème",
  "ui.this_device": "Cet appareil",
  "ui.this_device_2": "Cet appareil",
  "ui.this_device_player_connected": "Lecteur de cet appareil connecté",
  "ui.this_device_player_disconnected": "Lecteur de cet appareil déconnecté",
  "ui.thu": "Jeu",
  "ui.timer": "Minuterie",
  "ui.timer_active_remaining": "Minuterie active: {remaining}",
  "ui.timers": "Minuteries",
  "ui.to": "À",
  "ui.today": "Aujourd'hui",
  "ui.track": "Piste",
  "ui.track_lyrics": "Paroles",
  "ui.tracks": "Pistes",
  "ui.transfer_clone_inspect_or_clear_queues_without_hiding_the_studio": "Transférer, dupliquer, inspecter ou vider les files d'attente sans masquer le Studio.",
  "ui.transfer_is_unavailable_while_a_pinned_player_is_configured": "Le transfert n'est pas disponible lorsqu'un lecteur épinglé est configuré",
  "ui.transfer_queue": "Transférer la file d'attente",
  "ui.transfer_queue_2": "Transférer la file d'attente",
  "ui.transfer_queue_3": "Transférer la file d'attente",
  "ui.try_again": "Réessayer",
  "ui.tts_entity": "Entité TTS",
  "ui.tts_entity_used_by_the_announcement_screen": "Entité TTS utilisée par l'écran d'annonce.",
  "ui.tts_language": "Langue du TTS",
  "ui.tue": "Mar",
  "ui.turkey": "Turquie",
  "ui.turn_off": "Désactiver",
  "ui.turns_off_after_run": "Se désactive après l'exécution",
  "ui.turns_off_heavy_visuals_so_the_card_runs_smoother_on_nest_hub_older_tabl": "Désactive les effets visuels intensifs pour une meilleure performance sur les Nest Hub et les tablettes moins puissantes.",
  "ui.type_a_free_style_first": "Saisissez d'abord un style",
  "ui.type_an_announcement": "Saisissez une annonce...",
  "ui.type_anything": "Saisissez n'importe quoi",
  "ui.type_what_should_be_announced": "Saisissez ce qui doit être annoncé...",
  "ui.ungroup": "Dissocier",
  "ui.ungroup_2": "Dissocier",
  "ui.united_kingdom": "Royaume-Uni",
  "ui.united_states": "États-Unis",
  "ui.unknown": "Inconnu",
  "ui.up": "Haut",
  "ui.move_down": "Descendre",
  "ui.move_up": "Monter",
  "ui.up_next": "À suivre",
  "ui.up_next_2": "À suivre",
  "ui.up_next_title": "À suivre: {title}",
  "ui.upbeat_and_moving": "Énergique et entraînant",
  "ui.use_any_home_assistant_path_example_lovelace_home": "Utilisez n'importe quel chemin Home Assistant, par exemple /lovelace/home",
  "ui.use_current_view_for_home_button": "Utiliser la vue actuelle pour le bouton Accueil",
  "ui.use_expand_to_open_the_full_player": "Utilisez le bouton d'agrandissement pour ouvrir le lecteur complet",
  "ui.uses_the_same_base_country_list_shown_in_the_in_card_settings_screen": "Utilise la même liste de pays de base affichée dans l’écran des paramètres intégrés à la carte.",
  "ui.visible_tiles": "tuiles visibles",
  "ui.visible_tiles_2": "Tuiles visibles",
  "ui.visual_editor": "Éditeur visuel",
  "ui.assist_agent": "Agent Assist",
  "ui.assist_agent_id": "ID de l'agent Assist",
  "ui.assist_only": "Assist seulement",
  "ui.default_assist_agent": "Home Assistant Assist par défaut",
  "ui.default_order": "Ordre par d?faut",
  "ui.hybrid_handles_music_locally_and_sends_unknown_commands_to_assist": "Recommandé : les commandes musicales sont exécutées localement. Tout ce que la carte ne comprend pas est envoyé à Home Assistant Assist.",
  "ui.hybrid_music_plus_assist": "Hybride: Musique + Assist",
  "ui.icon_size": "Taille des icônes",
  "ui.music_only": "Musique seulement",
  "ui.music_plus_assist": "Musique + Assist",
  "ui.optional_assist_agent_id_leave_empty_for_home_assistant_default": "ID optionnel de l’agent Assist. Laissez vide pour utiliser l’agent Assist par défaut de Home Assistant.",
  "ui.optional_assist_agent_leave_empty_for_home_assistant_default": "Optionnel. Laissez l’agent par défaut sauf si vous utilisez plusieurs agents Assist et souhaitez que cette carte en utilise un spécifique.",
  "ui.show_a_push_to_talk_button_for_music_and_assist_commands": "Affiche un bouton push-to-talk pour les commandes musicales et de l'agent Assist.",
  "ui.show_home_inside_quick_actions": "Affiche Accueil comme une action rapide au lieu d'un bouton flottant.",
  "ui.show_plus_minus_buttons_next_to_the_volume_slider": "Afficher les boutons plus et moins avec le curseur de volume.",
  "ui.speak_voice_assistant_responses_out_loud": "Lit les réponses reconnues de l’assistant vocal à voix haute dans ce navigateur lorsque cette fonction est prise en charge.",
  "ui.flow_assistant": "FLOW ASSISTANT",
  "ui.voice_assistant": "Assistant vocal",
  "ui.voice_assistant_disabled": "Assistant vocal désactivé",
  "ui.voice_assistant_listening": "Écoute en cours...",
  "ui.voice_assistant_mode": "Mode de l’assistant vocal",
  "ui.voice_command_executed": "Commande vocale exécutée",
  "ui.voice_command_completed_action": "Terminé : {action}",
  "ui.voice_command_failed": "Échec de la commande vocale",
  "ui.voice_command_no_player": "Sélectionnez un lecteur ou dites son nom à voix haute.",
  "ui.voice_command_not_understood": "Je n’ai pas compris cette commande.",
  "ui.voice_command_sent": "Commande vocale envoyée",
  "ui.voice_done_status": "Terminé",
  "ui.voice_error_status": "Attention requise",
  "ui.voice_feedback": "Retour vocal",
  "ui.voice_group_connect_needs_players": "Dites au moins deux noms de lecteurs, ou sélectionnez un lecteur puis dites le nom de l’autre.",
  "ui.voice_group_connected_players": "{primary} connecté à {members}",
  "ui.voice_group_disconnect_needs_player": "Indiquez quel groupe de lecteurs doit être déconnecté.",
  "ui.voice_group_disconnected_player": "Le groupe de {player} a été déconnecté",
  "ui.voice_input_failed": "Échec de l'entrée vocale",
  "ui.voice_input_is_not_supported_on_this_device": "L'entrée vocale n'est pas prise en charge sur cet appareil",
  "ui.voice_language_is_not_supported": "La langue de la reconnaissance vocale sélectionnée n'est pas prise en charge par ce navigateur.",
  "ui.voice_match_not_confident": "J’ai trouvé {title}, mais cela ne correspond pas assez à « {query} ». Réessayez en disant le titre et l’artiste.",
  "ui.voice_music_searching": "Recherche de musique en cours: {query}",
  "ui.voice_playing_result": "Lecture de {title}",
  "ui.voice_queue_transfer_needs_players": "Dites la source et la cible du lecteur. Par exemple: transfère la file d'attente de Salon vers Cuisine.",
  "ui.voice_queue_transferred_between": "File d'attente transférée de {source} vers {target}",
  "ui.voice_starting_playback": "Démarrage de la lecture: {title}...",
  "ui.voice_processing_status": "Traitement en cours...",
  "ui.voice_ready_status": "Prêt",
  "ui.voice_recognition_network_failed": "Le service de reconnaissance vocale est indisponible. Les permissions du microphone peuvent être correctes ; vérifiez le navigateur, le VPN, le DNS, le pare-feu ou le réseau.",
  "ui.voice_response": "Réponse",
  "ui.voice_response_will_appear_here": "La réponse apparaîtra ici.",
  "ui.voice_search": "Recherche vocale",
  "ui.voice_search_failed": "Échec de la recherche vocale",
  "ui.voice_search_is_not_supported_on_this_device": "La recherche vocale n'est pas prise en charge sur cet appareil",
  "ui.voice_transcript": "Transcription",
  "ui.voice_listening_status": "Écoute...",
  "ui.waiting_for_speech": "En attente d'une commande vocale...",
  "ui.microphone_permission_or_browser_blocked": "Le navigateur empêche la reconnaissance vocale. Vérifiez les paramètres du navigateur.",
  "ui.volume": "Volume",
  "ui.volume_and_player_target": "Volume et lecteur cible",
  "ui.volume_boost": "Gain de volume",
  "ui.volume_control_large_screen_only": "Contrôle du volume (écrans larges seulement)",
  "ui.volume_down": "Baisser le volume",
  "ui.volume_mode": "Mode du volume",
  "ui.volume_presets": "Préréglages de volume",
  "ui.volume_step_between_1_and_10_percent_default_5": "Incrémentation du volume entre 1 % et 10 %. Par défaut : 5 %.",
  "ui.volume_step_buttons": "Boutons volume +/-",
  "ui.volume_step_percent": "Incrémentation du volume",
  "ui.volume_up": "Augmenter le volume",
  "ui.waiting_for_this_device_player": "En attente du lecteur de cet appareil...",
  "ui.wake": "Démarrage",
  "ui.wake_schedules": "Démarrage programmé",
  "ui.wed": "Mer",
  "ui.week": "Semaine",
  "ui.what_would_you_like_to_listen_to": "Qu'aimeriez-vous écouter?",
  "ui.will_play_next": "Sera lu ensuite",
  "ui.will_play_next_in_studio": "Sera lu ensuite dans le Studio",
  "ui.worldwide_popular": "Populaire dans le monde entier",
  "ui.add_player_light_pair": "Ajouter une paire",
  "ui.ambient_light": "Lumière ambiante",
  "ui.ambient_light_brightness": "Luminosité",
  "ui.ambient_light_cooldown": "Délai entre les mises à jour",
  "ui.ambient_light_entities": "Couleur par défaut",
  "ui.ambient_light_player_map": "Association lecteur/lumière",
  "ui.ambient_light_player_map_helper": "Créez des paires lumières-lecteurs pour la lumière ambiante. Une paire par ligne ; effacez un lecteur ou ses lumières pour supprimer la paire.",
  "ui.ambient_light_transition": "Transition",
  "ui.analog": "Analogue",
  "ui.choose_only_the_lights_that_should_follow_the_music": "Choisissez uniquement les lumières compatibles avec les couleurs qui doivent suivre la musique lorsqu’aucune paire spécifique à un lecteur n’existe.",
  "ui.digital": "Numérique",
  "ui.discover_albums": "Découvrir des albums",
  "ui.discover_music": "Découvrir",
  "ui.discover_subtitle": "Playlists, albums et radios recommandés.",
  "ui.discovery": "Découverte",
  "ui.discovery_failed": "Échec du mode Découverte",
  "ui.discovery_mode": "Mode Découverte",
  "ui.discovery_started": "Découverte démarrée: {mood}",
  "ui.maximum_brightness_for_music_lighting": "Luminosité maximale de l'éclairage musical",
  "ui.minimum_seconds_between_light_updates": "Délai minimum en secondes entre les mises à jour",
  "ui.player_light_pair_lights": "Lumières colorées {number}",
  "ui.player_light_pair_lights_helper": "Choisissez les lumières compatibles avec les couleurs pour ce lecteur Music Assistant. Effacez ce champ ou le lecteur pour supprimer la paire.",
  "ui.player_light_pair_player": "Lecteur Music Assistant {number}",
  "ui.player_light_pair_player_helper": "Choisissez le lecteur MA pour cette lumière.",
  "ui.all": "Tous",
  "ui.all_genres": "Tous les styles",
  "ui.genres_and_styles": "Styles et genres",
  "ui.compact_widget_mode": "Style du widget compact",
  "ui.choose_when_compact_mode_uses_the_two_row_mobile_widget": "Choisissez le mode du widget. Mini widget affiche une carte compacte adaptée pour mobile.",
  "ui.full": "Complet",
  "ui.mini_widget": "Mini widget",
  "ui.genre": "Style",
  "ui.mood_and_genre": "Ambiance et style",
  "ui.music_by_mood_and_genre": "Musique par ambiance et style",
  "ui.optional_entity_for_the_power_button_leave_empty_to_stop_the_active_player": "(Optionnel) Entité pour le bouton d'alimentation. Laissez vide pour arrêter le lecteur actif.",
  "ui.optional_name_for_the_auxiliary_button": "(Optionnel) Nom du bouton auxiliaire.",
  "ui.choose_the_auxiliary_button_icon": "Choisissez l'icône affichée sur le bouton auxiliaire.",
  "ui.choose_how_players_are_sorted": "Choisissez l'ordre des lecteurs : par défaut, alphabétique ou personnalisé.",
  "ui.choose_music_assistant_players_to_hide_from_the_card": "Choisissez les lecteurs Music Assistant qui ne doivent jamais apparaître sur la carte.",
  "ui.custom_order": "Ordre personnalisé",
  "ui.no_visible_music_assistant_players_after_exclusions": "Tous les lecteurs Music Assistant sont masqués par le paramètre des lecteurs exclus.",
  "ui.set_custom_player_order": "Définissez l'ordre des lecteurs. Les emplacements vides sont ignorés.",
  "ui.show_auxiliary_button_in_quick_actions": "Affiche ce bouton auxiliaire sur la ligne des actions rapides.",
  "ui.power": "Alimentation",
  "ui.power_action_failed": "Échec de l'action d'alimentation",
  "ui.power_action_sent": "Action d'alimentation envoyé",
  "ui.power_button": "Bouton d'alimentation",
  "ui.power_button_action": "Action du bouton d'alimentation",
  "ui.power_button_entity": "Entité du bouton d'alimentation",
  "ui.scene": "Scène",
  "ui.screensaver": "Économiseur d'écran",
  "ui.screensaver_buttons": "Boutons de l'économiseur d'écran",
  "ui.screensaver_controls": "Contrôles de l'économiseur d'écran",
  "ui.screensaver_clock_mode": "Mode de l'horloge de l'économiseur d'écran",
  "ui.screensaver_clock_size": "Taille de l'horloge",
  "ui.screensaver_clock_size_helper": "Ajuste la taille de l'horloge sur l'économiseur d'écran sans déplacer la pochette.",
  "ui.screensaver_clock_x": "Position de l'horloge - GAUCHE / DROITE",
  "ui.screensaver_clock_x_helper": "Diminuez la valeur pour déplacer à gauche, augmentez pour déplacer à droite.",
  "ui.screensaver_clock_y": "Position de l'horloge - HAUT / BAS",
  "ui.screensaver_clock_y_helper": "Diminuez la valeur pour déplacer vers le haut, augmentez la valeur pour déplacer vers le bas.",
  "ui.screensaver_message": "Message sur l'économiseur d'écran",
  "ui.screensaver_timeout": "Délai de l'économiseur d'écran",
  "ui.script": "Script",
  "ui.short_optional_message_shown_on_the_screensaver": "Court message affiché sur l'économiseur d'écran. (optionnel)",
  "ui.show_previous_next_controls_on_the_screensaver": "Afficher les boutons suivant/précédent sur l'économiseur d'écran.",
  "ui.choose_which_buttons_appear_on_the_screensaver": "Choisissez pr?cis?ment quels boutons apparaissent sur l'économiseur d'écran, y compris FLOW ASSISTANT, précédent et suivant.",
  "ui.show_a_calm_clock_artwork_display_after_idle_time": "Afficher une horloge discrète et la pochette après un temps d'inactivité.",
  "ui.show_power_button_in_the_player_controls": "Afficher le bouton d'alimentation dans les contrôles du lecteur.",
  "ui.show_the_fullscreen_discovery_mode_in_actions": "Afficher le mode Découverte en plein écran dans les Actions.",
  "ui.smart_home": "Maison intelligente",
  "ui.soft_transition_time_for_music_lighting": "Transitions douces pour la l'éclairage musical.",
  "ui.stop_player": "Arrêter le lecteur",
  "ui.sync_selected_lights_to_the_current_artwork_color": "Synchroniser les lumières sélectionnées avec la couleur de pochette du média actif.",
  "ui.toggle": "Basculer",
  "ui.turn_on": "Activer",
  "ui.choose_a_category_to_browse_provider_playlists": "Choisissez une catégorie pour parcourir les listes de lecture du fournisseur avant de lancer la lecture.",
  "ui.new_and_recommended": "Nouveau et recommandé",
  "ui.provider_playlists": "Listes de lecture du fournisseur",
  "ui.hotel_mode": "Mode hôtel",
  "ui.hotel_mode_helper": "Interface minimale sécurisée pour l'hôtel : commandes du lecteur, volume, recherche, navigation dans les pochettes et sélection du lecteur uniquement.",
  "ui.style_and_genres": "Styles et genres",
  "ui.card_id": "Card ID",
  "ui.card_id_helper": "Unique slug (letters, digits, '-', '_'). Set this when running multiple HOMEii Flow dashboards in the same browser so each dashboard keeps its own player picker, theme, layout, and other in-card settings. Leave blank to share state with every other HOMEii Flow card in this browser (the original behaviour).",
});

export default messages;
