// Generated HOMEii Music Flow localization dictionary.
// Keep keys stable. Translate only the string values.
const messages = Object.freeze({
  "ui.a_guided_music_wizard": "אשף מוזיקה ברור ומהיר",
  "ui.a_radio_station": "תחנה זמינה",
  "ui.accent_color": "צבע מוביל",
  "ui.actions": "פעולות",
  "ui.actions_2": "פעולות",
  "ui.active_days": "ימים פעילים",
  "ui.active_player_helper": "Helper לנגן פעיל",
  "ui.active_player_helper_must_be_an_input_text_entity": "ה־helper של הנגן הפעיל חייב להיות מסוג input_text",
  "ui.active_players": "נגנים פעילים",
  "ui.add": "הוסף",
  "ui.add_to_queue": "הוסף לתור",
  "ui.add_to_selection": "הוסף לבחירה",
  "ui.added_to_liked": "נוסף לאהבתי",
  "ui.added_to_music_assistant_liked": "נוסף לאהבתי של מיוזיק אסיסטנט",
  "ui.added_to_queue": "נוסף לתור",
  "ui.added_to_studio_queue": "נוסף לתור הסטודיו",
  "ui.adds_motion_to_the_background_layers_subtle_keeps_it_calm_strong_is_noti": "מוסיף תנועה לשכבות הרקע. מצב עדין שומר על מראה רגוע, מצב חזק כבר מורגש, ואקסטרים נותן את התנועה הכי נועזת.",
  "ui.adds_to_the_current_volume_only_during_announcements_then_restores_the_p": "מוסיף אחוזים לווליום הקיים רק בזמן הכריזה ואז מחזיר למה שהיה לפני.",
  "ui.after_run": "אחרי הפעלה",
  "ui.album": "אלבום",
  "ui.albums": "אלבומים",
  "ui.all_albums": "כל האלבומים",
  "ui.all_artists": "כל האמנים",
  "ui.all_countries": "כל המדינות",
  "ui.all_player_groups_disconnected": "כל קבוצות הנגנים נותקו",
  "ui.all_players": "כל הנגנים",
  "ui.all_players_2": "כל הנגנים",
  "ui.all_podcasts": "כל הפודקאסטים",
  "ui.all_tracks": "כל השירים",
  "ui.allow_local_likes": "אהבתי מקומי",
  "ui.always_visible": "פעיל תמיד",
  "ui.announce": "כרוז",
  "ui.announce_to_all_players": "כרוז לכולם",
  "ui.announcement": "כריזה",
  "ui.announcement_failed_with_error": "?????? ?????{error}",
  "ui.announcement_language": "שפת כריזה",
  "ui.announcement_presets": "משפטי כריזה",
  "ui.announcement_sent_to_player": "?????? ????? ?? {player}",
  "ui.announcement_studio": "סטודיו כריזה",
  "ui.announcement_studio_2": "סטודיו כריזה",
  "ui.announcement_target": "יעד כריזה",
  "ui.announcement_to_player_preview": "????? ?? {player}: {preview}",
  "ui.announcement_volume_boost": "תוספת ווליום כריזה",
  "ui.announcements": "כריזה",
  "ui.appearance": "מראה",
  "ui.alphabetical": "אלפביתי",
  "ui.auxiliary_button": "לחצן עזר",
  "ui.auxiliary_button_action": "פעולת לחצן עזר",
  "ui.auxiliary_button_entity": "ישות לחצן עזר",
  "ui.auxiliary_button_icon": "אייקון לחצן עזר",
  "ui.auxiliary_button_name": "שם לחצן עזר",
  "ui.auxiliary_buttons": "לחצני עזר",
  "ui.apply_group": "חבר קבוצה",
  "ui.apply_schedule": "אישור",
  "ui.artist": "אמן",
  "ui.artist_radio": "רדיו אמן",
  "ui.artists": "אמנים",
  "ui.artwork": "עטיפה",
  "ui.artwork_swipe": "סוויפ על עטיפה",
  "ui.ascending": "סדר עולה",
  "ui.at_least_one_player_must_stay_selected": "נגן אחד חייב להישאר נבחר",
  "ui.australia": "אוסטרליה",
  "ui.auto_chooses_mobile_or_tablet_based_on_actual_width": "Auto בוחר מובייל או טאבלט לפי רוחב בפועל.",
  "ui.auto_cloud_default": "אוטומטי / ברירת מחדל בענן",
  "ui.auto_extracts_colors_from_the_current_artwork_and_keeps_the_effect_subtl": "מצב Auto מחלץ צבעים מהעטיפה הפעילה ושומר על מראה עדין. מצב Strong נותן נוכחות עשירה ובולטת יותר.",
  "ui.auto_leaves_home_assistant_cloud_voice_defaults_untouched_manual_choices": "Auto לא שולח שפה ל־Home Assistant Cloud כדי להשתמש בברירת המחדל שלך. בחירה ידנית תשלח language מפורש.",
  "ui.available": "זמין",
  "ui.back": "חזרה",
  "ui.back_2": "חזור",
  "ui.back_to_countries": "חזרה למדינות",
  "ui.back_to_queue": "חזרה לתור",
  "ui.background_motion": "תנועת רקע",
  "ui.behavior": "התנהגות",
  "ui.browse_covers": "מדפדף עטיפות",
  "ui.browse_playlists_artists_albums_and_radio": "דפדוף בפלייליסטים, אמנים, אלבומים ורדיו",
  "ui.browser_players": "נגני דפדפן",
  "ui.build_custom_mix": "בנה מיקס חופשי",
  "ui.building_studio_mix": "בונה מיקס סטודיו...",
  "ui.button": "כפתור",
  "ui.by_mood": "לפי סגנון",
  "ui.cache_duration_in_milliseconds_for_selected_data_requests": "משך הקאש במילישניות עבור קריאות נתונים מסוימות.",
  "ui.cache_ttl": "זמן קאש",
  "ui.calm": "רגוע",
  "ui.canada": "קנדה",
  "ui.cancel": "ביטול",
  "ui.cancel_2": "בטל",
  "ui.cancel_selection": "בטל בחירה",
  "ui.card_configuration": "מהגדרות הכרטיס",
  "ui.card_height": "גובה הכרטיס",
  "ui.card_height_in_pixels": "גובה הכרטיס בפיקסלים.",
  "ui.card_settings_are_managed_from_the_visual_editor": "הגדרות הכרטיס מנוהלות מתוך העורך הוויזואלי",
  "ui.change_song": "מעביר שיר",
  "ui.change_track": "מעביר שיר",
  "ui.chill_mix": "מיקס רגוע",
  "ui.choose_a_country_or_all_countries_to_browse_every_country_inside_the_rad": "בחר מדינה, או כל המדינות כדי לדפדף בכל המדינות מתוך טאב הרדיו.",
  "ui.choose_a_queue_position": "בחר מיקום בתור",
  "ui.choose_a_source_player": "בחר נגן מקור",
  "ui.choose_a_target_player": "בחר נגן יעד",
  "ui.choose_at_least_one_player": "בחר לפחות נגן אחד",
  "ui.choose_icons_text_or_both_for_the_footer": "קובע אם הפוטר יוצג כאייקונים, טקסט או שניהם.",
  "ui.choose_music_assistant_players_only_the_in_card_pinning_list_shows_only": "בחר רק נגני Music Assistant. בתוך הכרטיס יוצגו לקיבוע רק נגני Music Assistant כדי למנוע בלבול.",
  "ui.choose_one_clear_option": "בחר אפשרות אחת ברורה",
  "ui.choose_player": "בחר נגן",
  "ui.choose_something_from_the_quick_shelf_or_tap_the_wand_for_a_random_playl": "בחר משהו מהמדף המהיר או לחץ על השרביט לפלייליסט אקראי.",
  "ui.choose_source": "בחר מקור",
  "ui.choose_target": "בחר יעד",
  "ui.choose_target_player": "בחר נגן יעד",
  "ui.choose_the_accent_color_for_the_mobile_layout": "בחר צבע בסיס לעיצוב המובייל.",
  "ui.choose_the_music": "איזו מוזיקה?",
  "ui.choose_the_small_buttons_shown_under_the_song_title_timer_appears_first": "בחר וסדר את הכפתורים הקטנים שיופיעו מתחת לשם השיר.",
  "ui.choose_the_source_first_playback_will_use_the_current_target": "בחר מקור מוזיקה. הניגון יישלח ליעד הנוכחי.",
  "ui.choose_where_to_play": "איפה לנגן?",
  "ui.choose_whether_artwork_swipe_changes_track_or_browses_covers": "קובע האם סוויפ על עטיפת האלבום יעביר שיר או ידפדף עטיפות.",
  "ui.choose_whether_settings_are_controlled_from_the_in_card_ui_or_from_the_c": "בחר אם ההגדרות נשלטות מתוך ה־UI בכרטיס או מתוך הגדרות הכרטיס בדשבורד.",
  "ui.choose_which_actions_appear_in_the_main_bar": "בחר אילו כפתורים יופיעו בסרגל הראשי.",
  "ui.choose_which_days_the_auto_night_mode_window_applies_to": "בחר באילו ימים חלון מצב הלילה יהיה פעיל במצב Auto.",
  "ui.choose_which_icons_appear_in_the_quick_action_row": "בחר אילו אייקונים יופיעו בשורת הפעולות המהירות. נקה הכל יבקש אישור לפני ניתוק הנגנים הפעילים.",
  "ui.choose_which_players_appear_as_tiles_in_the_room": "בחר אילו נגנים יופיעו כאריחים בחדר.",
  "ui.choose_which_players_stay_in_the_current_control_selection": "בחר אילו נגנים יישארו בבחירה הנוכחית.",
  "ui.choose_which_tabs_are_available_in_the_library_screen": "בחר אילו טאבים יהיו זמינים במסך הספרייה.",
  "ui.choose_who_is_controlled": "בחר על מי שולטים",
  "ui.choosing_visual_disables_the_in_card_settings_screen": "בחירה ב־Visual מבטלת את מסך ההגדרות מתוך הכרטיס.",
  "ui.clean_all": "נקה הכל",
  "ui.clean_all_confirm_action": "נקה הכל",
  "ui.clean_all_confirm_copy": "הפעולה תנתק את כל הנגנים הפעילים, תעצור נגינה ותנקה את התורים שלהם. להמשיך?",
  "ui.clean_all_confirm_title": "לנקות את כל הנגנים?",
  "ui.clean_the_studio_wall": "סדר את מסך הסטודיו",
  "ui.clear": "נקה",
  "ui.clear_queue": "נקה תור",
  "ui.clear_search": "נקה חיפוש",
  "ui.clone_queue": "העתק תור",
  "ui.close": "סגור",
  "ui.collapse_compact_player": "חזרה למצב קומפקטי",
  "ui.compact_mode": "מצב קומפקטי",
  "ui.configure_ready_made_announcement_phrases": "אפשר להגדיר כמה משפטי כריזה מוכנים מראש.",
  "ui.connect_this_device": "חבר את המכשיר הזה",
  "ui.connect_this_device_2": "חבר מכשיר זה",
  "ui.connected": "מחובר",
  "ui.connected_2": "מחוברים",
  "ui.connected_players": "נגנים מחוברים",
  "ui.connected_players_2": "נגנים מחוברים",
  "ui.connecting": "מתחבר",
  "ui.connecting_2": "מתחבר...",
  "ui.confirm": "אישור",
  "ui.connection_and_behavior": "חיבור והתנהגות",
  "ui.connects_directly_from_this_card_using_sendspin": "מתחבר ישירות מתוך הכרטיס דרך Sendspin",
  "ui.continue": "מעבר",
  "ui.continue_2": "המשך",
  "ui.continue_from_recent_music_assistant_activity": "המשך מהאזנות אחרונות ב־Music Assistant.",
  "ui.continue_listening": "המשך האזנה",
  "ui.continue_what_was_played_recently": "המשך ממה שהתנגן לאחרונה",
  "ui.control_whether_the_card_background_moves_gently_and_how_strong_the_moti": "שולט אם רקע הכרטיס נע בעדינות, ובאיזו עוצמה.",
  "ui.controlling": "שולט עכשיו על",
  "ui.could_not_build_quick_mix_from_the_current_song": "לא הצלחתי לבנות Quick Mix מהשיר הנוכחי",
  "ui.could_not_build_studio_mix": "לא הצלחתי לבנות מיקס סטודיו",
  "ui.could_not_choose_media": "לא ניתן לבחור מדיה",
  "ui.could_not_clone_the_queue": "לא הצלחתי להעתיק את התור",
  "ui.could_not_find_music": "לא הצלחתי למצוא מוזיקה",
  "ui.could_not_play_label": "?? ?????? ????: {label}",
  "ui.could_not_start_chill_mix": "לא ניתן להפעיל מיקס רגוע",
  "ui.could_not_start_playback": "לא הצלחתי להתחיל ניגון",
  "ui.could_not_start_playback_2": "לא ניתן להתחיל ניגון",
  "ui.could_not_start_playback_in_studio": "לא הצלחתי להפעיל ניגון בסטודיו",
  "ui.could_not_start_quick_mix": "לא ניתן להפעיל Quick Mix",
  "ui.could_not_start_radio_playback": "לא ניתן להתחיל ניגון רדיו",
  "ui.could_not_transfer_the_queue": "לא הצלחתי להעביר את התור",
  "ui.could_not_update_active_player_helper": "לא ניתן לעדכן helper לנגן פעיל",
  "ui.create_schedule": "צור תזמון",
  "ui.current_path": "נתיב נוכחי",
  "ui.custom": "אישי",
  "ui.dark": "כהה",
  "ui.delete_scene": "מחק סצנה",
  "ui.delete_schedule": "מחק תזמון",
  "ui.descending": "סדר יורד",
  "ui.dictate": "הכתבה קולית",
  "ui.disabled": "כבוי",
  "ui.disables_blur_animations_dynamic_backgrounds_and_heavy_shadows_recommend": "מכבה טשטושים, אנימציות, רקעים דינמיים וצללים כבדים. מומלץ ל־Nest Hub וטאבלטים חלשים.",
  "ui.disconnect": "נתק",
  "ui.disconnect_all": "נתק הכל",
  "ui.disconnect_groups": "נתק קבוצות",
  "ui.disconnect_player_groups": "נתק קבוצות נגנים",
  "ui.disconnect_this_device": "נתק את המכשיר הזה",
  "ui.disconnected": "מנותק",
  "ui.disconnecting": "מתנתק",
  "ui.disconnecting_player_groups": "מנתק קבוצות נגנים...",
  "ui.discover": "גלה",
  "ui.down": "למטה",
  "ui.dynamic_theme": "ערכת נושא דינמית",
  "ui.edit_schedule": "עריכת תזמון",
  "ui.enable": "הפעל",
  "ui.enable_or_disable_the_footer_search_button": "מפעיל או מכבה את כפתור החיפוש בפוטר.",
  "ui.enable_or_disable_the_studio_button_in_the_footer_bar": "מפעיל או מכבה את כפתור הסטודיו בסרגל התחתון.",
  "ui.enable_the_floating_home_shortcut_button": "מפעיל את כפתור הבית הצף.",
  "ui.enabled": "פעיל",
  "ui.enables_switching_to_local_liked_mode": "מפעיל אפשרות לעבור ל־Liked mode מקומי.",
  "ui.end_time": "שעת סיום",
  "ui.excluded_players": "נגנים מוחרגים",
  "ui.energetic": "קצבי",
  "ui.energy_and_rhythm": "אנרגיה וקצב",
  "ui.enter_an_announcement_first": "קודם צריך להזין הודעת כריזה",
  "ui.example_quiet_jazz_greek_music_workout": "לדוגמה: ג'אז רגוע, מוזיקה יוונית, אימון",
  "ui.existing_content": "תוכן קיים",
  "ui.expand_player": "הרחב נגן",
  "ui.extract_colors_from_the_current_artwork_and_apply_them_to_the_interface": "מחלץ צבעים מעטיפת האלבום ומחיל אותם על הממשק.",
  "ui.extreme": "אקסטרים",
  "ui.fallback_for_setups_that_need_an_alternate_queue_service_path": "Fallback למערכות שבהן תור ההשמעה דורש נתיב service חלופי.",
  "ui.fallback_mode": "מצב בסיסי",
  "ui.family_friendly": "ידידותי למשפחה",
  "ui.favorite": "אהבתי",
  "ui.favorite_action_failed": "פעולת אהבתי נכשלה",
  "ui.favorite_action_sent": "פעולת אהבתי נשלחה",
  "ui.favorite_button_entity": "ישות כפתור Like",
  "ui.favorite_center": "מרכז אהבתי",
  "ui.favorite_center_2": "מרכז אהבתי",
  "ui.favorite_radio": "תחנות מועדפות",
  "ui.favorite_updated": "אהבתי עודכן",
  "ui.favorites_and_liked_music": "מועדפים ומוזיקה אהובה",
  "ui.feature_detection_player_context_and_this_device_playback_tools": "זיהוי יכולות, הקשר נגן וכלים לנגן המכשיר הזה.",
  "ui.find_music": "מצא מוזיקה",
  "ui.finding_music": "מחפש מוזיקה",
  "ui.fixed": "קבוע",
  "ui.flow_mix": "מיקס FLOW",
  "ui.font_scale": "סקייל פונט",
  "ui.font_size": "גודל פונט",
  "ui.footer_search": "חיפוש בפוטר",
  "ui.footer_style": "מראה פוטר",
  "ui.footer_style_2": "סגנון פוטר",
  "ui.for_example_lovelace_home_or_any_other_home_assistant_path": "למשל /lovelace/home או כל נתיב אחר ב-Home Assistant.",
  "ui.for_weaker_displays_turns_off_heavy_blur_animations_dynamic_theme_extrac": "למסכים חלשים: מכבה טשטושים כבדים, אנימציות, חילוץ צבעים מהעטיפה ותנועת רקע.",
  "ui.france": "צרפת",
  "ui.free_style": "סגנון חופשי",
  "ui.free_style_quiet_jazz_greek_music_workout": "סגנון חופשי: ג'אז רגוע, יוונית, אימון...",
  "ui.fresh_start": "פתיחה נעימה ליום",
  "ui.fresh_start_2": "פתיחה קלילה",
  "ui.fri": "ו׳",
  "ui.friendly_and_simple": "שמח וברור",
  "ui.from": "מ־",
  "ui.general": "כללי",
  "ui.general_and_display": "כללי ותצוגה",
  "ui.germany": "גרמניה",
  "ui.global_scale_for_every_interface_font_1_is_the_default_size": "סקייל כללי לכל הפונטים בממשק. 1 הוא ברירת המחדל.",
  "ui.greece": "יוון",
  "ui.grid": "גריד",
  "ui.group": "קבוצה",
  "ui.group_cleared": "הקבוצה פורקה",
  "ui.group_cleared_2": "הקבוצה נותקה",
  "ui.group_speakers": "חיבור רמקולים",
  "ui.group_speakers_2": "קבוצת נגנים",
  "ui.group_updated": "הקבוצה עודכנה",
  "ui.group_volume": "ווליום קבוצה",
  "ui.group_volume_up_energetic_mix": "קבוצה, ווליום גבוה ומיקס קצבי",
  "ui.grouped_players": "נגנים בקבוצה",
  "ui.hebrew": "עברית",
  "ui.history": "היסטוריה",
  "ui.history_tabs": "טאבי היסטוריה",
  "ui.home": "בית",
  "ui.home_party_night_presets": "בית, מסיבה, לילה",
  "ui.home_path": "נתיב הבית",
  "ui.home_scene_prepared": "סצנת בית מוכנה",
  "ui.home_shortcut": "כפתור בית",
  "ui.home_shortcut_path": "נתיב כפתור בית",
  "ui.icon_and_text": "אייקון ומלל",
  "ui.icon_only": "אייקון בלבד",
  "ui.icon_plus_text": "אייקון ומלל",
  "ui.idle": "פנוי",
  "ui.idle_2": "ממתין",
  "ui.in_card_ui": "מה־UI בתוך הכרטיס",
  "ui.includes_the_custom_theme_mode_from_the_in_card_settings_screen": "כולל גם מצב אישי כמו במסך ההגדרות של הכרטיס.",
  "ui.info": "מידע",
  "ui.israel": "ישראל",
  "ui.israeli": "ישראלי",
  "ui.italy": "איטליה",
  "ui.items": "פריטים",
  "ui.join_selected_players": "חבר נגנים נבחרים",
  "ui.kids": "ילדים",
  "ui.language": "שפה",
  "ui.larger_lyrics": "מילים גדולות יותר",
  "ui.layout_adapted_to_height": "הפריסה הותאמה לגובה",
  "ui.layout_mode": "מצב פריסה",
  "ui.leave_empty_if_the_card_should_use_home_assistant_only": "השאר ריק אם הכרטיס ניגש ל־Music Assistant דרך Home Assistant בלבד.",
  "ui.library": "ספריה",
  "ui.library_2": "ספרייה",
  "ui.library_pages": "דפי ספריה",
  "ui.default_library_layout": "תצוגת ברירת מחדל לספריה",
  "ui.choose_how_library_pages_open_grid_or_list_can_still_be_changed_manually": "בחר איך דפי הספריה ייפתחו. עדיין אפשר להחליף Grid/List ידנית בתוך הספריה.",
  "ui.library_radio": "רדיו מהספריה",
  "ui.library_surprise": "הפתעה מהספריה",
  "ui.library_tabs": "דפי ספרייה",
  "ui.library_tabs_2": "טאבי ספרייה",
  "ui.light": "בהיר",
  "ui.like": "לייק",
  "ui.like_2": "אהבתי",
  "ui.like_3": "סמן אהבתי",
  "ui.liked": "אהבתי",
  "ui.liked_mode": "מצב אהבתי",
  "ui.liked_sync": "סנכרון אהבתי",
  "ui.list": "רשימה",
  "ui.listening": "מקשיב...",
  "ui.loading": "טוען...",
  "ui.loading_favorites": "טוען אהובים...",
  "ui.loading_library": "טוען ספרייה...",
  "ui.loading_lyrics": "טוען מילים...",
  "ui.loading_players": "טוען נגנים...",
  "ui.loading_queue": "טוען תור...",
  "ui.loading_recent_items": "טוען אחרונים...",
  "ui.loading_schedules": "טוען תזמונים...",
  "ui.local": "מקומי",
  "ui.local_favorites": "מוזיקה מקומית",
  "ui.local_favorites_2": "מוזיקה ישראלית",
  "ui.local_mode_is_only_meaningful_when_local_likes_are_enabled": "מצב Local שימושי רק אם Local likes מופעל.",
  "ui.low_light_listening": "שקט לערב",
  "ui.low_volume_and_quiet_mix": "ווליום נמוך ומיקס רגוע",
  "ui.lower_volume_mood": "אווירת לילה רגועה",
  "ui.lyrics": "מילים",
  "ui.lyrics_earlier": "מילים מוקדם יותר",
  "ui.lyrics_font_size": "גודל פונט מילים",
  "ui.lyrics_later": "מילים מאוחר יותר",
  "ui.lyrics_timing": "תזמון מילים",
  "ui.lyrics_unavailable_right_now": "המילים לא זמינות כרגע",
  "ui.ma_favorite_action_failed_with_error": "????? ????? ?? ?????? ??????? ?????{error}",
  "ui.ma_interface_path": "נתיב ממשק MA",
  "ui.main_bar": "סרגל ראשי",
  "ui.main_bar_items": "פריטים בסרגל הראשי",
  "ui.main_bar_items_2": "פריטי סרגל ראשי",
  "ui.main_opacity": "שקיפות ראשית",
  "ui.mainly_relevant_on_larger_layouts": "רלוונטי במיוחד במסכים גדולים.",
  "ui.mass_queue_send_command_fallback": "Fallback mass_queue/send_command",
  "ui.matches_the_microphone_setting_from_the_in_card_settings_screen": "זהה לבחירת המיקרופון במסך ההגדרות.",
  "ui.media": "מדיה",
  "ui.media_2": "Media",
  "ui.media_actions": "פעולות מדיה",
  "ui.media_layout": "תצוגת מדיה",
  "ui.media_selected_target": "????: {media} ? ???: {target}",
  "ui.menu": "תפריט",
  "ui.message": "הודעה",
  "ui.microphone": "שימוש במיקרופון",
  "ui.microphone_2": "מיקרופון",
  "ui.microphone_is_disabled": "המיקרופון מנותק",
  "ui.missing_url": "חסר URL",
  "ui.mobile": "מובייל",
  "ui.mon": "ב׳",
  "ui.mood_style_or_free_text": "מצב רוח, סגנון או חיפוש חופשי",
  "ui.more_info": "מידע נוסף",
  "ui.more_info_is_unavailable_for_this_player": "מידע נוסף לא זמין לנגן הזה",
  "ui.morning": "בוקר",
  "ui.morning_mix": "מיקס בוקר",
  "ui.move_to_next": "העבר לבא בתור",
  "ui.move_to_position": "העבר למיקום",
  "ui.music": "מוזיקה",
  "ui.music_assistant_required": "נדרשת אינטגרציית Music Assistant",
  "ui.music_assistant_config_entry_id_if_you_want_direct_integration_lookup_th": "מזהה ה־config entry של Music Assistant, אם רוצים קישור ישיר דרך Home Assistant.",
  "ui.music_assistant_config_entry_was_not_found": "לא נמצא Config Entry של Music Assistant",
  "ui.music_assistant_token": "טוקן Music Assistant",
  "ui.music_assistant_url": "כתובת Music Assistant",
  "ui.music_hub": "מרכז מוזיקה",
  "ui.music_hub_2": "מרכז מוזיקה",
  "ui.mute": "השתק",
  "ui.mute_command_failed": "פקודת ההשתקה נכשלה",
  "ui.my_studio_scene": "סצנת סטודיו שלי",
  "ui.name_or_keyword": "שם או מילת חיפוש",
  "ui.name_this_studio_scene": "שם לסצנת הסטודיו...",
  "ui.netherlands": "הולנד",
  "ui.new_schedule": "תזמון חדש",
  "ui.new_wake_schedule": "תזמון השכמה חדש",
  "ui.newest": "הכי חדש",
  "ui.next": "הבא",
  "ui.next_track_failed": "מעבר לשיר הבא נכשל",
  "ui.night": "לילה",
  "ui.night_end_time": "שעת סיום ללילה",
  "ui.night_mode": "מצב לילה",
  "ui.night_mode_auto_window": "??? ???? ??????? {start}-{end}",
  "ui.night_mode_days": "ימי מצב לילה",
  "ui.night_mode_is_always_on": "מצב לילה פעיל תמיד",
  "ui.night_mode_is_off": "מצב לילה כבוי",
  "ui.night_mode_is_off_until_you_choose_another_mode": "מצב לילה כבוי עד שתבחר מצב אחר.",
  "ui.night_mode_stays_on_until_you_choose_another_mode": "מצב לילה יישאר פעיל עד שתבחר מצב אחר.",
  "ui.night_schedule_updated": "לוח הזמנים של מצב לילה עודכן",
  "ui.night_start_time": "שעת התחלה ללילה",
  "ui.no_active_media": "אין מדיה פעילה",
  "ui.no_active_players": "אין נגנים פעילים",
  "ui.no_available_players": "אין נגנים זמינים",
  "ui.no_content_found": "לא נמצא תוכן",
  "ui.no_dynamic_player_groups_to_disconnect": "אין קבוצות נגנים דינמיות לניתוק",
  "ui.no_extra_ma_players": "אין נגני MA נוספים",
  "ui.no_extra_ma_players_2": "אין נגנים נוספים",
  "ui.no_favorites_found": "לא נמצאו אהובים.",
  "ui.no_liked_media_yet": "עדיין לא נשמרו מועדפים",
  "ui.no_liked_tracks_to_play": "אין שירים מועדפים לנגן",
  "ui.no_light_entities_found": "לא נמצאו ישויות תאורה.",
  "ui.no_lyrics_found": "לא נמצאו מילים לשיר הזה",
  "ui.no_matching_content_was_found": "לא נמצא תוכן מתאים",
  "ui.no_media_found": "לא נמצאה מדיה.",
  "ui.no_media_found_for_this_search": "לא נמצאה מדיה לחיפוש הזה.",
  "ui.no_mix_content_found": "לא נמצא תוכן למיקס",
  "ui.no_music_assistant_players_were_found_check_music_assistant_and_media_pl": "נדרשת אינטגרציית Music Assistant. הפעל את Music Assistant ב-Home Assistant וודא שיש לפחות נגן Music Assistant אחד. נגני Home Assistant רגילים מוסתרים בכוונה.",
  "ui.no_music_assistant_players_were_found_for_pinning": "לא נמצאו נגני Music Assistant לקיבוע.",
  "ui.no_next_track_in_queue": "אין שיר הבא בתור",
  "ui.no_player_groups_to_disconnect": "אין קבוצות נגנים לניתוק",
  "ui.no_player_light_pairs_yet": "עדיין לא נוספו צמדי נגן-תאורה.",
  "ui.no_player_selected": "לא נבחר נגן",
  "ui.no_players_found": "לא נמצאו נגנים",
  "ui.no_players_found_yet": "עדיין לא נמצאו נגנים",
  "ui.no_playlists_found": "לא נמצאה מוזיקה אקראית",
  "ui.no_queue": "אין תור",
  "ui.no_queue_item_to_rebuild": "לא נמצא פריט פעיל לתור",
  "ui.no_queue_to_clone": "אין תור להעתקה",
  "ui.no_radio_browser_countries_found": "לא נמצאו מדינות Radio Browser",
  "ui.no_radio_stations_found": "לא נמצאו תחנות רדיו",
  "ui.no_recent_listening_yet": "אין האזנות אחרונות עדיין.",
  "ui.no_results": "אין תוצאות",
  "ui.no_results_found": "לא נמצאו תוצאות",
  "ui.no_saved_studio_scenes_yet": "עדיין אין סצנות סטודיו שמורות.",
  "ui.no_scheduled_start_is_active": "אין כרגע תזמון הפעלה פעיל",
  "ui.no_selected_tracks_to_play": "אין שירים נבחרים לנגן",
  "ui.no_sleep_timer_is_active": "אין כרגע טיימר שינה פעיל",
  "ui.no_speech_was_captured": "לא נקלט דיבור",
  "ui.no_target_players_available": "אין נגנים זמינים להעברה",
  "ui.no_target_players_available_2": "אין נגני יעד זמינים",
  "ui.no_tts_service_or_entity_is_configured": "לא הוגדר שירות או ישות TTS",
  "ui.no_wake_schedules_yet": "עדיין אין תזמוני השכמה",
  "ui.none": "אין",
  "ui.nothing_is_playing_right_now": "לא מתנגן כרגע",
  "ui.nothing_playing": "לא מתנגן",
  "ui.now_playing": "מתנגן עכשיו",
  "ui.now_playing_2": "מתנגן עכשיו",
  "ui.off": "כבוי",
  "ui.off_2": "מנותק",
  "ui.off_disables_it_on_keeps_it_active_and_auto_follows_the_configured_time": "Off מכבה, On מפעיל תמיד, ו־Auto פועל לפי חלון השעות שהגדרת.",
  "ui.oldest": "הכי ישן",
  "ui.on": "פעיל",
  "ui.one_tap_prepares_players_grouping_volume_and_content_save_your_own_curre": "לחיצה אחת מכינה נגנים, קבוצה, ווליום ותוכן. אפשר לשמור את יעד הסטודיו הנוכחי כסצנה מקומית.",
  "ui.only_actions_for_the_current_target_are_shown_here": "כאן מופיעות רק פעולות ליעד השליטה הנוכחי.",
  "ui.only_music_assistant_players_are_shown_here_browser_and_local_sendspin_p": "מוצגים כאן רק נגני Music Assistant. נגני דפדפן ו-Sendspin מקומי מוסתרים כדי למנוע בלבול.",
  "ui.only_needed_when_using_a_direct_music_assistant_url": "נדרש רק אם אתה עובד מול כתובת MA ישירה.",
  "ui.opacity_for_popups_and_overlays": "שקיפות חלונות וקופצים.",
  "ui.opacity_for_the_main_card_background": "שקיפות הרקע הראשי של הכרטיס.",
  "ui.open_full_interface": "פתיחת ממשק מלא",
  "ui.open_full_queue": "פתח תור מלא",
  "ui.open_interface_in": "פתיחת ממשק",
  "ui.open_ma": "פתח MA",
  "ui.open_music_assistant": "פתח Music Assistant",
  "ui.open_music_assistant_2": "מעבר ל-Music Assistant",
  "ui.open_music_assistant_on_this_device_to_activate_the_browser_player": "פתח את Music Assistant במכשיר הזה כדי להפעיל את נגן הדפדפן",
  "ui.open_player_picker": "בחר נגן",
  "ui.open_queue": "פתח תור",
  "ui.open_saved_songs": "פתח שירים שמורים",
  "ui.open_the_full_music_assistant_interface": "האם לפתוח את הממשק המלא של Music Assistant?",
  "ui.open_the_full_music_assistant_interface_2": "פתח את ממשק Music Assistant המלא",
  "ui.opening_studio_library": "פותח את ספריית הסטודיו",
  "ui.opening_timers": "פותח טיימרים",
  "ui.option": "אפשרות",
  "ui.optional": "אופציונלי",
  "ui.optional_2": "לא חובה",
  "ui.optional_entity_used_for_an_external_favorite_button": "ישות אופציונלית לכפתור Like חיצוני.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for": "אופציונלי: input_text שהכרטיס יעדכן עם entity_id של הנגן הפעיל, עבור אוטומציות ותבניות.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for_2": "אופציונלי: בחר input_text שהכרטיס יעדכן עם entity_id של הנגן הפעיל עבור אוטומציות ותבניות.",
  "ui.other": "אחר",
  "ui.other_players": "נגנים נוספים",
  "ui.party": "מסיבה",
  "ui.path_used_when_opening_the_music_assistant_interface": "נתיב לפתיחת ממשק Music Assistant.",
  "ui.pause": "השהה",
  "ui.paused": "מושהה",
  "ui.per_device_in_card": "מהמכשיר / הממשק",
  "ui.performance_mode": "מצב ביצועים",
  "ui.performance_mode_for_weak_devices": "מצב ביצועים למכשירים חלשים",
  "ui.performance_profile": "פרופיל ביצועים",
  "ui.performance_profile_helper": "בחר כמה עבודה חזותית הכרטיס יבצע. Ultra Lite מפחית שקיפות, טשטוש, רקעי עטיפה דינמיים ותנועה עבור מכשירים חלשים.",
  "ui.pick_a_mood_or_type_your_own_style_studio_will_search_music_assistant_an": "בחר מצב רוח או כתוב סגנון חופשי. הסטודיו יחפש ב־Music Assistant ויבנה תור.",
  "ui.pinned": "מקובע",
  "ui.pinned_players": "נגנים מקובעים",
  "ui.play": "נגן",
  "ui.play_2": "ניגון",
  "ui.play_a_few_tracks_and_they_will_appear_here": "נגן כמה שירים והם יופיעו כאן.",
  "ui.play_a_saved_list": "רשימה מוכנה",
  "ui.play_all": "נגן הכל",
  "ui.play_an_artist": "ניגון אמן",
  "ui.play_artwork_action": "פעולת עטיפה",
  "ui.play_everywhere": "ניגון בכל הבית",
  "ui.play_next": "נגן הבא",
  "ui.play_next_and_clear_queue": "נגן הבא ונקה תור",
  "ui.play_now": "נגן עכשיו",
  "ui.play_now_and_clear_queue": "נגן עכשיו נקה תור",
  "ui.play_pause": "נגן / השהה",
  "ui.play_queue_radio_or_remove_favorites_directly_from_studio": "נגן, הוסף, הפעל רדיו או נהל אהובים ישירות מהסטודיו.",
  "ui.play_selected": "נגן נבחרים",
  "ui.playback_command_failed": "Playback command failed",
  "ui.playback_command_failed_2": "פקודת הניגון נכשלה",
  "ui.playback_started": "הניגון התחיל",
  "ui.player": "נגן",
  "ui.player_2": "נגן",
  "ui.player_count_many": "{count} ?????",
  "ui.player_count_one": "??? ???",
  "ui.player_groups_could_not_be_disconnected": "קבוצות הנגנים לא נותקו",
  "ui.player_is_pinned_from_settings": "הנגן מקובע מתוך ההגדרות",
  "ui.player_is_ready": "הנגן מוכן",
  "ui.player_is_ready_nothing_is_playing_right_now": "הנגן זמין – לא מתנגן כרגע כלום",
  "ui.player_order": "סדר נגנים",
  "ui.player_on_this_device": "נגן במכשיר זה",
  "ui.player_selected": "הנגן נבחר",
  "ui.player_settings_and_dsp_presets_stay_read_only_until_music_assistant_exp": "הגדרות נגן ו־DSP נשארים בשלב זה כזיהוי יכולות בלבד עד ש־Music Assistant מחזיר schema אמין לנגן.",
  "ui.player_sort": "מיון נגנים",
  "ui.players": "נגנים",
  "ui.players_queue_and_groups": "נגנים, תור וקבוצות",
  "ui.playing": "מנגן",
  "ui.playing_a_random_playlist": "מנגן פלייליסט אקראי",
  "ui.playing_a_random_radio_station": "מנגן תחנת רדיו אקראית",
  "ui.playing_on": "מתנגן על",
  "ui.playing_on_2": "מנגן ב",
  "ui.playlist": "פלייליסט",
  "ui.playlists": "פלייליסטים",
  "ui.podcast": "פודקאסט",
  "ui.podcasts": "פודקאסטים",
  "ui.popup_opacity": "שקיפות חלונות",
  "ui.preset_message": "משפט מוגדר מראש",
  "ui.previous": "הקודם",
  "ui.primary": "ראשי",
  "ui.primary_target": "יעד ראשי",
  "ui.pro_tools": "כלי Pro",
  "ui.queue": "תור ניגון",
  "ui.queue_2": "תור",
  "ui.queue_action_failed": "פעולה על התור נכשלה",
  "ui.queue_action_is_not_available_for_this_player": "פעולת התור לא זמינה לנגן הזה",
  "ui.queue_actions": "פעולות תור",
  "ui.queue_cleared": "התור נוקה",
  "ui.queue_cleared_and_item_moved_next": "התור נוקה והפריט הוגדר לבא בתור",
  "ui.queue_cloned": "התור הועתק",
  "ui.queue_cockpit": "ניהול תור",
  "ui.queue_cockpit_2": "ניהול תור",
  "ui.queue_is_empty": "התור ריק",
  "ui.queue_is_unavailable_for_this_player": "התור לא זמין לנגן הזה",
  "ui.queue_item": "פריט בתור",
  "ui.queue_item_id_is_not_ready_yet_refresh_the_queue_and_try_again": "מזהה פריט התור עדיין לא מוכן. רענן את התור ונסה שוב.",
  "ui.queue_results": "תוצאות בעמודת התור",
  "ui.queue_transferred": "התור הועבר",
  "ui.queues_refreshed": "התורים רועננו",
  "ui.quick_actions": "פעולות מהירות",
  "ui.quick_actions_2": "פעולות מהירות",
  "ui.quick_mix": "מיקס מהיר",
  "ui.quick_mix_started": "המיקס המהיר הופעל",
  "ui.quick_play": "ניגון מהיר",
  "ui.radio": "רדיו",
  "ui.radio_browser": "Radio Browser",
  "ui.radio_browser_countries": "מדינות Radio Browser",
  "ui.radio_browser_country": "מדינת Radio Browser",
  "ui.radio_browser_country_2": "מדינת רדיו",
  "ui.radio_mode_is_not_available_for_this_media_type": "Radio לא זמין לסוג המדיה הזה",
  "ui.radio_mode_started": "Radio הופעל",
  "ui.radio_station_changed": "תחנת הרדיו הוחלפה",
  "ui.radio_stations": "תחנות רדיו",
  "ui.random": "אקראי",
  "ui.random_gentle_morning_mix": "מיקס בוקר נעים ואקראי",
  "ui.random_playlist": "פלייליסט אקראי",
  "ui.random_radio": "רדיו אקראי",
  "ui.ready": "מוכן",
  "ui.ready_to_play": "מוכן לניגון",
  "ui.recent": "אחרונים",
  "ui.recent_continue": "אחרונים / המשך",
  "ui.recent_listening": "האזנות אחרונות",
  "ui.recent_track": "שיר קודם",
  "ui.recently_added": "נוספו לאחרונה",
  "ui.recently_played": "נוגן לאחרונה",
  "ui.recently_played_2": "נוגן לאחרונה",
  "ui.recommendations_will_appear_once_homeii_flow_sees_your_queue_or_recent_l": "המלצות יופיעו אחרי ש-HOMEii Flow יזהה את התור או ההאזנות האחרונות.",
  "ui.recommended": "המלצות",
  "ui.recommended_format_hh_mm_such_as_06_00_crossing_midnight_is_supported": "פורמט מומלץ: HH:MM כמו 06:00. אפשר לחצות חצות.",
  "ui.recommended_format_hh_mm_such_as_22_00": "פורמט מומלץ: HH:MM כמו 22:00.",
  "ui.recommended_playlist": "פלייליסט מומלץ",
  "ui.recommended_track": "המלצה",
  "ui.reconnects_when_you_return_to_this_dashboard": "יתחבר מחדש כשתחזור לדשבורד הזה",
  "ui.refresh": "רענן",
  "ui.remember_as_this_device": "שייך למכשיר הזה",
  "ui.remove": "הסר",
  "ui.remove_from_selection": "הסר מהבחירה",
  "ui.removed_from_liked": "הוסר מאהבתי",
  "ui.removed_from_music_assistant_liked": "הוסר מאהבתי של מיוזיק אסיסטנט",
  "ui.reorder_queue": "סידור תור",
  "ui.repeat": "חזרה",
  "ui.repeat_all": "חזרה על הכל",
  "ui.repeat_off": "חזרה כבויה",
  "ui.repeat_one": "חזרה על שיר אחד",
  "ui.reset": "איפוס",
  "ui.reset_lyrics_font_size": "איפוס גודל מילים",
  "ui.reset_lyrics_timing": "איפוס תזמון מילים",
  "ui.results": "תוצאות",
  "ui.rtl": "RTL",
  "ui.sat": "ש׳",
  "ui.save_current_target": "שמור יעד נוכחי",
  "ui.save_schedule": "שמור תזמון",
  "ui.scene_players_are_not_available": "הנגנים של הסצנה לא זמינים",
  "ui.scene_presets": "סצנות",
  "ui.scene_presets_2": "סצנות",
  "ui.scenes": "סצנות",
  "ui.scales_interface_icons_without_changing_button_sizes": "מגדיל או מקטין אייקונים בלי לשנות את גודל הכפתורים או המבנה.",
  "ui.scheduled_start": "תזמון הפעלה",
  "ui.scheduled_start_activated_label": "????? ?????? ?????: {label}",
  "ui.scheduled_start_cleared": "תזמון ההפעלה בוטל",
  "ui.scheduled_start_failed": "תזמון ההפעלה נכשל",
  "ui.scheduled_start_saved": "תזמון ההפעלה נשמר",
  "ui.scheduled_starts_active_count": "{count} ?????? ????? ??????",
  "ui.schedules": "תזמונים",
  "ui.search": "חיפוש",
  "ui.search_and_choose_play_next_add_radio_or_like": "חפש ובחר נגן, הבא, הוסף, רדיו או אהבתי.",
  "ui.search_everything": "חפש בכל מקום...",
  "ui.search_failed": "החיפוש נכשל",
  "ui.search_in_queue": "חיפוש בעמודת התור",
  "ui.search_queue_and_library": "חפש בתור ובספרייה...",
  "ui.search_the_library": "חפש בספריה...",
  "ui.search_tracks_albums_artists_and_playlists": "חיפוש שירים, אלבומים, אמנים ופלייליסטים",
  "ui.searching": "מחפש...",
  "ui.searching_library": "מחפש בספריה...",
  "ui.searching_smart_selection": "מחפש בחירה חכמה...",
  "ui.seek": "קפיצה",
  "ui.select": "בחר",
  "ui.select_lights": "בחירת תאורה או תאורות",
  "ui.select_player": "בחירת נגן",
  "ui.select_2": "בחירה",
  "ui.select_a_player_first": "בחר נגן קודם",
  "ui.select_at_least_one_studio_player": "בחר לפחות נגן אחד בסטודיו",
  "ui.select_at_least_two_players_to_create_a_group": "בחר לפחות שני נגנים כדי ליצור קבוצה",
  "ui.selected": "נבחר",
  "ui.selected_music": "מוזיקה נבחרת",
  "ui.selected_player": "נגן נבחר",
  "ui.selected_player_2": "נגן נבחר",
  "ui.selected_player_3": "הנגן הנבחר",
  "ui.selected_players_at_comfortable_volume": "נגנים נבחרים בווליום נוח",
  "ui.selected_playlist": "פלייליסט נבחר",
  "ui.send_a_short_voice_message_or_announcement_url": "שלח הודעה קולית קצרה או קישור כריזה.",
  "ui.send_a_voice_message": "שלח כריזה קולית",
  "ui.send_announcement": "שלח כריזה",
  "ui.sendspin_and_diagnostics": "Sendspin ודיאגנוסטיקה",
  "ui.set_sleep_timer": "הפעל טיימר שינה",
  "ui.set_volume": "קבע ווליום",
  "ui.set_the_visual_order_of_quick_actions": "קובע את הסדר הוויזואלי. רק פעולות מהירות שסומנו יוצגו; פריטים שלא סומנו יתעלמו.",
  "ui.settings": "הגדרות",
  "ui.settings_source": "מקור ההגדרות",
  "ui.show_confirmation_toasts": "הצג הודעות אישור",
  "ui.show_confirmation_toasts_helper": "הצג הודעות אישור קצרות לאחר פעולות כגון בחירת נגן או הוספה לרשימת המועדפים. השבת אפשרות זו כדי להסתיר הודעות אלה; הודעות שגיאה ימשיכו להופיע בכל מקרה.",
  "ui.show_ma_button": "כפתור MA",
  "ui.show_or_hide_the_inline_next_track_row_in_now_playing": "מציג או מסתיר את שורת השיר הבא במסך הניגון.",
  "ui.show_theme_toggle": "כפתור ערכת נושא",
  "ui.show_up_next": "הצג הבא בתור",
  "ui.show_up_next_2": "הצגת הבא בתור",
  "ui.shows_a_standalone_compact_player_tile_with_artwork_basic_controls_volum": "מציג נגן אריח עצמאי וקומפקטי עם עטיפה, פקדי בסיס, ווליום וכפתור הרחבה.",
  "ui.shuffle": "ערבוב",
  "ui.shuffle_all": "ערבב הכל",
  "ui.shuffle_favorites": "ערבוב אהובים",
  "ui.shuffle_play": "נגן בערבוב",
  "ui.skipped_to_up_next": "עבר לשיר הבא בתור",
  "ui.sleep_timer": "טיימר שינה",
  "ui.sleep_timer_2": "טיימר שינה",
  "ui.sleep_timer_active_remaining": "????? ???? ????: {remaining}",
  "ui.sleep_timer_added_minutes": "????? {minutes} ???? ??????",
  "ui.sleep_timer_and_morning_playback": "טיימר שינה ותזמון הפעלה",
  "ui.sleep_timer_and_scheduled_playback": "טיימר שינה ותזמון הפעלה",
  "ui.sleep_timer_cleared": "טיימר השינה בוטל",
  "ui.sleep_timer_finished": "טיימר השינה הסתיים",
  "ui.sleep_timer_presets": "בחירת זמן טיימר שינה",
  "ui.sleep_timer_set_for_15_minutes": "טיימר שינה הופעל ל־15 דקות",
  "ui.sleep_timer_set_minutes": "????? ???? ????? ??{minutes} ????",
  "ui.sleep_timer_updated_minutes": "????? ???? ????? ??{minutes} ????",
  "ui.smaller_lyrics": "מילים קטנות יותר",
  "ui.smart": "חכם",
  "ui.smart_mix": "מיקס חכם",
  "ui.smart_mix_builder": "בונה מיקס חכם",
  "ui.smart_voice_selection": "בחירה קולית חכמה",
  "ui.soft_and_relaxed": "רך ונעים",
  "ui.soft_relaxed_music": "מוזיקה רכה ורגועה",
  "ui.some_players_could_not_be_stopped_or_cleared": "חלק מהנגנים לא נעצרו או לא נוקו",
  "ui.songs_around_an_artist": "מוזיקה סביב אמן",
  "ui.sort": "מיון",
  "ui.sort_ascending": "סדר עולה",
  "ui.sort_descending": "סדר יורד",
  "ui.source_queue": "תור מקור",
  "ui.spain": "ספרד",
  "ui.speak_to_target_players": "שלח הודעה לנגנים",
  "ui.start_radio_mode": "הפעל Radio",
  "ui.start_time": "שעת הפעלה",
  "ui.start_time_2": "שעת התחלה",
  "ui.started_on_selected_player": "הופעל על הנגן הנבחר",
  "ui.starting_a_chill_mix": "מפעיל מיקס רגוע",
  "ui.starting_quick_mix": "מפעיל מיקס מהיר...",
  "ui.stations": "תחנות",
  "ui.stay_active": "יישאר פעיל",
  "ui.stays_active": "נשאר פעיל",
  "ui.stop_all": "עצור הכל",
  "ui.stop_all_players": "עצור את כל הנגנים",
  "ui.stop_command_failed": "פקודת העצירה נכשלה",
  "ui.stop_playback_clear_queues_and_disconnect_groups": "עצירה, ניקוי תורים וניתוק קבוצות",
  "ui.stopped_all_players_cleared_playlists_and_disconnected_groups": "כל הנגנים נעצרו, התורים נוקו והקבוצות נותקו",
  "ui.stops_this_browser_player": "עוצר את נגן הדפדפן הזה",
  "ui.strong": "חזק",
  "ui.studio": "סטודיו",
  "ui.studio_closed": "סטודיו נסגר",
  "ui.studio_media_action_failed": "פעולת המדיה בסטודיו נכשלה",
  "ui.studio_mix_started": "מיקס הסטודיו הופעל",
  "ui.studio_opened": "סטודיו נפתח",
  "ui.studio_pro": "סטודיו Pro",
  "ui.studio_pro_2": "סטודיו Pro",
  "ui.studio_scene": "סצנת סטודיו",
  "ui.studio_scene_deleted": "סצנת סטודיו נמחקה",
  "ui.studio_scene_saved": "סצנת סטודיו נשמרה",
  "ui.studio_scene_was_not_found": "סצנת הסטודיו לא נמצאה",
  "ui.studio_search": "חיפוש סטודיו",
  "ui.studio_shortcut": "כפתור סטודיו",
  "ui.subtle": "עדין",
  "ui.sun": "א׳",
  "ui.surprise_me": "תפתיע אותי",
  "ui.sync": "סנכרון",
  "ui.sync_lyrics": "סנכרון מילים",
  "ui.tablet": "טאבלט",
  "ui.tap_to_start_a_sleep_timer": "לחץ כדי להפעיל טיימר שינה",
  "ui.target_players": "נגני יעד",
  "ui.target_queue": "תור יעד",
  "ui.text_announcements_use_home_assistant_tts_into_the_selected_music_assist": "כריזה מטקסט משתמשת ב־TTS של Home Assistant אל נגן Music Assistant שנבחר. כריזה מקישור משתמשת בניגון הכרזה של Music Assistant.",
  "ui.text_only": "מלל בלבד",
  "ui.text_tone": "טון טקסט",
  "ui.theme": "ערכת תצוגה",
  "ui.theme_2": "ערכת נושא",
  "ui.theme_mode": "ערכת נושא",
  "ui.theme_toggle": "מצב כהה/בהיר",
  "ui.theme_toggle_2": "שמש / ירח",
  "ui.this_device": "המכשיר הזה",
  "ui.this_device_2": "מכשיר זה",
  "ui.this_device_player_connected": "נגן המכשיר חובר",
  "ui.this_device_player_disconnected": "נגן המכשיר נותק",
  "ui.thu": "ה׳",
  "ui.timer": "טיימר",
  "ui.timer_active_remaining": "????? ????: {remaining}",
  "ui.timers": "טיימרים",
  "ui.to": "אל",
  "ui.today": "היום",
  "ui.track": "שיר",
  "ui.track_lyrics": "מילות השיר",
  "ui.tracks": "שירים",
  "ui.transfer_clone_inspect_or_clear_queues_without_hiding_the_studio": "העבר, העתק, בדוק או נקה תורים בלי להסתיר את הסטודיו.",
  "ui.transfer_is_unavailable_while_a_pinned_player_is_configured": "העברת ניגון אינה זמינה כשמוגדר נגן מקובע",
  "ui.transfer_queue": "העבר תור",
  "ui.transfer_queue_2": "העבר תור",
  "ui.transfer_queue_3": "העברת התור",
  "ui.try_again": "נסה שוב",
  "ui.tts_entity": "ישות TTS",
  "ui.tts_entity_used_by_the_announcement_screen": "ישות TTS שתשמש למסך הכריזה.",
  "ui.tts_language": "שפת TTS",
  "ui.tue": "ג׳",
  "ui.turkey": "טורקיה",
  "ui.turn_off": "יכבה",
  "ui.turns_off_after_run": "נכבה אחרי הפעלה",
  "ui.turns_off_heavy_visuals_so_the_card_runs_smoother_on_nest_hub_older_tabl": "מכבה אפקטים כבדים כדי שהכרטיס ירוץ חלק יותר על Nest Hub, טאבלטים ישנים ומסכים חלשים.",
  "ui.type_a_free_style_first": "כתוב קודם סגנון חופשי",
  "ui.type_an_announcement": "הקלד הודעת כריזה...",
  "ui.type_anything": "כתוב מה שבא לך",
  "ui.type_what_should_be_announced": "כתוב מה להכריז...",
  "ui.ungroup": "נתק קבוצה",
  "ui.ungroup_2": "נתק",
  "ui.united_kingdom": "בריטניה",
  "ui.united_states": "ארצות הברית",
  "ui.unknown": "לא ידוע",
  "ui.up": "למעלה",
  "ui.move_down": "הזז למטה",
  "ui.move_up": "הזז למעלה",
  "ui.up_next": "הבא בתור",
  "ui.up_next_2": "הבא בתור",
  "ui.up_next_title": "??? ????: {title}",
  "ui.upbeat_and_moving": "קצב ותנועה",
  "ui.use_any_home_assistant_path_example_lovelace_home": "אפשר להשתמש בכל נתיב ב-Home Assistant. לדוגמה: /lovelace/home",
  "ui.use_current_view_for_home_button": "השתמש במסך הנוכחי עבור כפתור הבית",
  "ui.use_expand_to_open_the_full_player": "השתמש בהרחבה כדי לפתוח את הנגן המלא",
  "ui.uses_the_same_base_country_list_shown_in_the_in_card_settings_screen": "אותה רשימת מדינות בסיסית שמופיעה במסך ההגדרות.",
  "ui.visible_tiles": "אריחים מוצגים",
  "ui.visible_tiles_2": "אריחים מוצגים",
  "ui.visual_editor": "מהעורך הוויזואלי",
  "ui.voice_input_failed": "זיהוי קולי נכשל",
  "ui.voice_input_is_not_supported_on_this_device": "זיהוי קולי לא נתמך במכשיר הזה",
  "ui.voice_search": "חיפוש קולי",
  "ui.voice_search_failed": "החיפוש הקולי נכשל",
  "ui.voice_search_is_not_supported_on_this_device": "חיפוש קולי לא נתמך במכשיר הזה",
  "ui.volume": "ווליום",
  "ui.volume_and_player_target": "ווליום ויעד נגנים",
  "ui.volume_boost": "חיזוק ווליום",
  "ui.volume_control_large_screen_only": "בקרת ווליום (זמין רק במסך גדול)",
  "ui.volume_down": "הורדת ווליום",
  "ui.volume_mode": "בקרת ווליום",
  "ui.volume_presets": "בחירת ווליום",
  "ui.volume_step_between_1_and_10_percent_default_5": "קפיצת ווליום בין 1% ל-10%. ברירת המחדל היא 5%.",
  "ui.volume_step_buttons": "כפתורי ווליום +/-",
  "ui.volume_step_percent": "קפיצת ווליום",
  "ui.volume_up": "העלאת ווליום",
  "ui.waiting_for_this_device_player": "ממתין לנגן של המכשיר הזה...",
  "ui.wake": "השכמה",
  "ui.wake_schedules": "תזמוני השכמה",
  "ui.wed": "ד׳",
  "ui.week": "השבוע",
  "ui.what_would_you_like_to_listen_to": "לאיזה תוכן תרצו להאזין? ",
  "ui.will_play_next": "ינוגן הבא",
  "ui.will_play_next_in_studio": "ינוגן הבא בסטודיו",
  "ui.worldwide_popular": "פופולרי בעולם",
  "ui.add_player_light_pair": "הוספת צמד",
  "ui.ambient_light": "תאורה לפי עטיפה",
  "ui.ambient_light_brightness": "עוצמת תאורה",
  "ui.ambient_light_cooldown": "השהיית עדכון תאורה",
  "ui.ambient_light_entities": "תאורות צבע כברירת מחדל",
  "ui.ambient_light_player_map": "שיוך נגן -> תאורה",
  "ui.ambient_light_player_map_helper": "השתמש בסלקטורים של נגן ותאורות צבע למטה. כל שורה מלאה נשמרת כצמד; ניקוי הנגן או התאורות מסיר את הצמד.",
  "ui.ambient_light_transition": "מעבר תאורה",
  "ui.analog": "אנלוגי",
  "ui.choose_only_the_lights_that_should_follow_the_music": "בחר רק תאורות עם יכולת צבע שישמשו כברירת מחדל כשאין צמד ייעודי לנגן.",
  "ui.digital": "דיגיטלי",
  "ui.discover_albums": "גילוי אלבומים",
  "ui.discover_music": "גלה מוזיקה",
  "ui.discover_subtitle": "המלצות, אלבומים ורדיו לפי הסגנון שבחרת.",
  "ui.discovery": "גילוי מוזיקה",
  "ui.discovery_failed": "מצב ההמלצות נכשל",
  "ui.discovery_mode": "מצב המלצות",
  "ui.discovery_started": "התחלתי המלצה: {mood}",
  "ui.maximum_brightness_for_music_lighting": "עוצמת התאורה המקסימלית למוזיקה.",
  "ui.minimum_seconds_between_light_updates": "מספר שניות מינימלי בין עדכוני תאורה.",
  "ui.player_light_pair_lights": "תאורות צבע {number}",
  "ui.player_light_pair_lights_helper": "בחר תאורות עם יכולת צבע עבור נגן Music Assistant זה. ניקוי השדה או הנגן מסיר את הצמד.",
  "ui.player_light_pair_player": "נגן Music Assistant {number}",
  "ui.player_light_pair_player_helper": "בחר את נגן Music Assistant עבור צמד התאורה הזה.",
  "ui.all": "הכל",
  "ui.all_genres": "כל הז׳אנרים",
  "ui.genres_and_styles": "ז'אנרים וסגנונות",
  "ui.compact_widget_mode": "סגנון ווידג׳ט קומפקטי",
  "ui.choose_when_compact_mode_uses_the_two_row_mobile_widget": "בחר מתי מצב קומפקטי משתמש בווידג׳ט מובייל קטן בשתי שורות.",
  "ui.full": "רגיל",
  "ui.mini_widget": "ווידג׳ט קטן",
  "ui.genre": "ז׳אנר",
  "ui.mood_and_genre": "מצב רוח וז׳אנר",
  "ui.music_by_mood_and_genre": "מוזיקה לפי מצב רוח וז׳אנר",
  "ui.optional_entity_for_the_power_button_leave_empty_to_stop_the_active_player": "ישות אופציונלית ללחצן עזר. השאר ריק כדי לעצור את הנגן הפעיל.",
  "ui.optional_name_for_the_auxiliary_button": "שם אופציונלי שיוצג כטולטיפ ללחצן העזר.",
  "ui.choose_the_auxiliary_button_icon": "בחר את האייקון שיוצג ללחצן העזר.",
  "ui.choose_how_players_are_sorted": "בחר סדר ברירת מחדל, אלפביתי או סדר מותאם אישית.",
  "ui.choose_music_assistant_players_to_hide_from_the_card": "בחר נגני Music Assistant שלא יופיעו בכרטיס.",
  "ui.custom_order": "סדר מותאם",
  "ui.no_visible_music_assistant_players_after_exclusions": "כל נגני Music Assistant מוסתרים בהגדרת הנגנים המוחרגים.",
  "ui.set_custom_player_order": "קובע את סדר הנגנים המותאם. שדות ריקים יתעלמו.",
  "ui.show_auxiliary_button_in_quick_actions": "מציג את לחצן העזר הזה בשורת הפעולות המהירות.",
  "ui.power": "כיבוי",
  "ui.power_action_failed": "פעולת POWER נכשלה",
  "ui.power_action_sent": "פעולת POWER נשלחה",
  "ui.power_button": "לחצן עזר",
  "ui.power_button_action": "פעולת לחצן עזר",
  "ui.power_button_entity": "ישות לחצן עזר",
  "ui.scene": "סצנה",
  "ui.screensaver": "שומר מסך",
  "ui.screensaver_buttons": "כפתורי שומר מסך",
  "ui.screensaver_controls": "פקדי שומר מסך",
  "ui.screensaver_clock_mode": "סוג שעון בשומר מסך",
  "ui.screensaver_clock_size": "גודל שעון בשומר מסך",
  "ui.screensaver_clock_size_helper": "מגדיל או מקטין את השעון בשומר המסך בטאבלט בלי להזיז את העטיפה.",
  "ui.screensaver_clock_x": "מיקום שעון - LEFT / RIGHT",
  "ui.screensaver_clock_x_helper": "ערך נמוך מזיז שמאלה, ערך גבוה מזיז ימינה.",
  "ui.screensaver_clock_y": "מיקום שעון - UP / DOWN",
  "ui.screensaver_clock_y_helper": "ערך נמוך מזיז למעלה, ערך גבוה מזיז למטה.",
  "ui.screensaver_message": "הודעת שומר מסך",
  "ui.screensaver_timeout": "זמן עד שומר מסך",
  "ui.script": "סקריפט",
  "ui.short_optional_message_shown_on_the_screensaver": "הודעה קצרה ואופציונלית שתוצג בשומר המסך.",
  "ui.show_previous_next_controls_on_the_screensaver": "מציג כפתורי קודם והבא עדינים בשומר המסך.",
  "ui.choose_which_buttons_appear_on_the_screensaver": "בחירה מדויקת של הכפתורים שיופיעו בשומר המסך, כולל FLOW ASSISTANT, קודם והבא.",
  "ui.show_a_calm_clock_artwork_display_after_idle_time": "מציג שעון רגוע ועטיפה אחרי זמן ללא שימוש.",
  "ui.show_power_button_in_the_player_controls": "מציג לחצן עזר בשורת הפעולות המהירות.",
  "ui.show_the_fullscreen_discovery_mode_in_actions": "מציג מצב המלצות במסך מלא תחת פעולות.",
  "ui.smart_home": "בית חכם",
  "ui.soft_transition_time_for_music_lighting": "זמן מעבר רך לתאורת המוזיקה.",
  "ui.stop_player": "עצור נגן",
  "ui.sync_selected_lights_to_the_current_artwork_color": "מסנכרן אורות נבחרים לצבעי העטיפה הנוכחית.",
  "ui.toggle": "החלפה",
  "ui.turn_on": "הפעל",
  "ui.choose_a_category_to_browse_provider_playlists": "בחר קטגוריה כדי לראות פלייליסטים מהספקים לפני ניגון.",
  "ui.new_and_recommended": "חדש ומומלץ",
  "ui.provider_playlists": "פלייליסטים מהספקים",
  "ui.assist_agent": "סוכן Assist",
  "ui.assist_agent_id": "מזהה סוכן Assist",
  "ui.assist_only": "Assist בלבד",
  "ui.default_assist_agent": "Assist ברירת מחדל של Home Assistant",
  "ui.default_order": "סדר ברירת מחדל",
  "ui.hybrid_handles_music_locally_and_sends_unknown_commands_to_assist": "מומלץ: פקודות מוזיקה מתבצעות מקומית על הנגן הנבחר. כל דבר שהכרטיס לא מבין נשלח ל-Home Assistant Assist.",
  "ui.hybrid_music_plus_assist": "משולב: מוזיקה + Assist",
  "ui.icon_size": "גודל אייקונים",
  "ui.music_only": "מוזיקה בלבד",
  "ui.music_plus_assist": "מוזיקה + Assist",
  "ui.optional_assist_agent_id_leave_empty_for_home_assistant_default": "מזהה סוכן Assist אופציונלי. השאר ריק כדי להשתמש בסוכן ברירת המחדל של Home Assistant.",
  "ui.optional_assist_agent_leave_empty_for_home_assistant_default": "אופציונלי. השאר על סוכן ברירת המחדל אלא אם יש לך כמה סוכני Assist ואתה רוצה שהכרטיס ישתמש בסוכן מסוים.",
  "ui.show_a_push_to_talk_button_for_music_and_assist_commands": "מציג כפתור דיבור לפקודות מוזיקה ולגיבוי Assist.",
  "ui.show_home_inside_quick_actions": "מציג את הבית בתוך פעולות מהירות במקום כפתור צף.",
  "ui.show_plus_minus_buttons_next_to_the_volume_slider": "מציג כפתורי פלוס ומינוס ליד סליידר הווליום.",
  "ui.speak_voice_assistant_responses_out_loud": "מקריא את התגובה שזוהתה דרך הדפדפן הזה כאשר הדבר נתמך.",
  "ui.flow_assistant": "FLOW ASSISTANT",
  "ui.voice_assistant": "עוזר קולי",
  "ui.voice_assistant_disabled": "העוזר הקולי כבוי",
  "ui.voice_assistant_listening": "מקשיב לפקודה...",
  "ui.voice_assistant_mode": "מצב עוזר קולי",
  "ui.voice_command_executed": "הפקודה הקולית בוצעה",
  "ui.voice_command_completed_action": "בוצע: {action}",
  "ui.voice_command_failed": "הפקודה הקולית נכשלה",
  "ui.voice_command_no_player": "בחר נגן או אמור את שם הנגן.",
  "ui.voice_command_not_understood": "לא הצלחתי להבין את הפקודה.",
  "ui.voice_command_sent": "הפקודה הקולית נשלחה",
  "ui.voice_done_status": "בוצע",
  "ui.voice_error_status": "צריך בדיקה",
  "ui.voice_feedback": "פידבק קולי",
  "ui.voice_group_connect_needs_players": "אמור לפחות שני שמות נגנים, או בחר נגן ואמור את שם הנגן השני.",
  "ui.voice_group_connected_players": "{primary} חובר עם {members}",
  "ui.voice_group_disconnect_needs_player": "אמור איזו קבוצת נגן לנתק.",
  "ui.voice_group_disconnected_player": "הקבוצה של {player} נותקה",
  "ui.voice_music_searching": "מחפש מוזיקה: {query}",
  "ui.voice_language_is_not_supported": "הדפדפן לא תומך בשפת הזיהוי הקולי שנבחרה.",
  "ui.voice_match_not_confident": "מצאתי את {title}, אבל זה לא מספיק תואם ל־\"{query}\". נסה לומר שוב את שם השיר והאמן.",
  "ui.voice_playing_result": "מנגן את {title}",
  "ui.voice_queue_transfer_needs_players": "אמור מקור ויעד, למשל: העבר את התור מהסלון למטבח.",
  "ui.voice_queue_transferred_between": "התור הועבר מ־{source} אל {target}",
  "ui.voice_starting_playback": "מפעיל את {title}...",
  "ui.voice_processing_status": "מעבד פקודה...",
  "ui.voice_ready_status": "מוכן",
  "ui.voice_recognition_network_failed": "שירות זיהוי הדיבור לא זמין. ייתכן שהרשאת המיקרופון תקינה; בדוק דפדפן, VPN, DNS, חומת אש או רשת.",
  "ui.voice_response": "תגובה",
  "ui.voice_response_will_appear_here": "התגובה תופיע כאן.",
  "ui.voice_transcript": "תמלול",
  "ui.voice_listening_status": "מקשיב...",
  "ui.waiting_for_speech": "ממתין לדיבור...",
  "ui.microphone_permission_or_browser_blocked": "הדפדפן חסם את זיהוי הדיבור. בדוק הרשאות מיקרופון והגדרות זיהוי בדפדפן.",
  "ui.hotel_mode": "מצב מלון",
  "ui.hotel_mode_helper": "ממשק מצב מלון מינימלי: פקדי נגן, ווליום, חיפוש, דפדוף בעטיפות ובחירת נגן בלבד.",
  "ui.style_and_genres": "סגנונות וז'אנרים",
});

export default messages;
