// Generated HOMEii Music Flow localization dictionary.
// Keep keys stable. Translate only the string values.
const messages = Object.freeze({
  "ui.a_guided_music_wizard": "Un assistente musicale guidato",
  "ui.a_radio_station": "Una stazione radio",
  "ui.accent_color": "Colore d'accento",
  "ui.actions": "azioni",
  "ui.actions_2": "Azioni",
  "ui.active_days": "Giorni attivi",
  "ui.active_player_helper": "Aiutante riproduttore attivo",
  "ui.active_player_helper_must_be_an_input_text_entity": "L'aitante del riproduttore attivo deve essere un'entità input_text",
  "ui.active_players": "Riproduttori attivi",
  "ui.add": "Aggiungi",
  "ui.add_to_queue": "Aggiungi alla coda",
  "ui.add_to_selection": "Aggiungi alla selezione",
  "ui.added_to_liked": "Aggiunto ai preferiti",
  "ui.added_to_music_assistant_liked": "Aggiunto ai preferiti di Music Assistant",
  "ui.added_to_queue": "Aggiunto alla coda",
  "ui.added_to_studio_queue": "Aggiunto alla coda di Studio",
  "ui.adds_motion_to_the_background_layers_subtle_keeps_it_calm_strong_is_noti": "Aggiunge movimento ai livelli di sfondo. 'Tenue' lo mantiene calmo, 'Forte' è evidente ed 'Estremo' offre l'aspetto animato più audace.",
  "ui.adds_to_the_current_volume_only_during_announcements_then_restores_the_p": "Aumenta il volume attuale solo durante gli annunci, ripristinando poi il volume precedente.",
  "ui.after_run": "Dopo l'esecuzione",
  "ui.album": "Album",
  "ui.albums": "Album",
  "ui.all_albums": "Tutti gli album",
  "ui.all_artists": "Tutti gli artisti",
  "ui.all_countries": "Tutti i paesi",
  "ui.all_player_groups_disconnected": "Tutti i gruppi di riproduttori disconnessi",
  "ui.all_players": "Tutti i riproduttori",
  "ui.all_players_2": "tutti i riproduttori",
  "ui.all_podcasts": "Tutti i podcast",
  "ui.all_tracks": "Tutti i brani",
  "ui.allow_local_likes": "Consenti preferiti locali",
  "ui.always_visible": "Sempre visibile",
  "ui.announce": "Annuncia",
  "ui.announce_to_all_players": "Annuncia a tutti i riproduttori",
  "ui.announcement": "Annuncio",
  "ui.announcement_failed_with_error": "Annuncio fallito{error}",
  "ui.announcement_language": "Lingua dell'annuncio",
  "ui.announcement_presets": "Preimpostazioni annuncio",
  "ui.announcement_sent_to_player": "Annuncio inviato a {player}",
  "ui.announcement_studio": "studio annunci",
  "ui.announcement_studio_2": "Studio Annunci",
  "ui.announcement_target": "Target dell'annuncio",
  "ui.announcement_to_player_preview": "Annuncio a {player}: {preview}",
  "ui.announcement_volume_boost": "Incremento volume annuncio",
  "ui.announcements": "Annunci",
  "ui.appearance": "Aspetto",
  "ui.alphabetical": "Alfabetico",
  "ui.auxiliary_button": "Pulsante ausiliario",
  "ui.auxiliary_button_action": "Azione pulsante ausiliario",
  "ui.auxiliary_button_entity": "Entità pulsante ausiliario",
  "ui.auxiliary_button_icon": "Icona pulsante ausiliario",
  "ui.auxiliary_button_name": "Nome pulsante ausiliario",
  "ui.auxiliary_buttons": "Pulsanti ausiliari",
  "ui.apply_group": "Applica gruppo",
  "ui.apply_schedule": "Applica programmazione",
  "ui.artist": "Artista",
  "ui.artist_radio": "Radio artista",
  "ui.artists": "Artisti",
  "ui.artwork": "Copertina",
  "ui.artwork_swipe": "Scorrimento copertina",
  "ui.ascending": "Crescente",
  "ui.at_least_one_player_must_stay_selected": "Almeno un riproduttore deve rimanere selezionato",
  "ui.australia": "Australia",
  "ui.auto_chooses_mobile_or_tablet_based_on_actual_width": "Sceglie automaticamente tra smartphone o tablet in base alla larghezza effettiva.",
  "ui.auto_cloud_default": "Automatico / Predefinito Cloud",
  "ui.auto_extracts_colors_from_the_current_artwork_and_keeps_the_effect_subtl": "Estrae automaticamente i colori dalla copertina corrente mantenendo l'effetto tenue. 'Forte' rende la tavolozza più ricca e luminosa.",
  "ui.auto_leaves_home_assistant_cloud_voice_defaults_untouched_manual_choices": "Automatico lascia invariati i valori predefiniti della voce di Home Assistant Cloud. Le scelte manuali inviano una lingua esplicita.",
  "ui.available": "Disponibile",
  "ui.back": "Indietro",
  "ui.back_2": "Indietro",
  "ui.back_to_countries": "Torna ai paesi",
  "ui.back_to_queue": "Torna alla coda",
  "ui.background_motion": "Movimento di sfondo",
  "ui.behavior": "Comportamento",
  "ui.browse_covers": "Sfoglia copertine",
  "ui.browse_playlists_artists_albums_and_radio": "Sfoglia playlist, artisti, album e radio",
  "ui.browser_players": "Riproduttori del browser",
  "ui.build_custom_mix": "Crea mix personalizzato",
  "ui.building_studio_mix": "Creazione del mix di Studio...",
  "ui.button": "Pulsante",
  "ui.by_mood": "Per stato d'animo",
  "ui.cache_duration_in_milliseconds_for_selected_data_requests": "Durata della cache in millisecondi per le richieste di dati selezionate.",
  "ui.cache_ttl": "TTL della cache",
  "ui.calm": "Calmo",
  "ui.canada": "Canada",
  "ui.cancel": "Annulla",
  "ui.cancel_2": "Annulla",
  "ui.cancel_selection": "Annulla selezione",
  "ui.card_configuration": "Configurazione della scheda",
  "ui.card_height": "Altezza della scheda",
  "ui.card_height_in_pixels": "Altezza della scheda in pixel.",
  "ui.card_settings_are_managed_from_the_visual_editor": "Le impostazioni della scheda sono gestite dall'editor visuale",
  "ui.change_song": "Cambia canzone",
  "ui.change_track": "Cambia brano",
  "ui.chill_mix": "Mix relax",
  "ui.choose_a_country_or_all_countries_to_browse_every_country_inside_the_rad": "Scegli un paese, o 'Tutti i paesi' per sfogliare ogni stato all'interno della scheda Radio.",
  "ui.choose_a_queue_position": "Scegli una posizione in coda",
  "ui.choose_a_source_player": "Scegli un riproduttore sorgente",
  "ui.choose_a_target_player": "Scegli un riproduttore di destinazione",
  "ui.choose_at_least_one_player": "Scegli almeno un riproduttore",
  "ui.choose_icons_text_or_both_for_the_footer": "Scegli icone, testo o entrambi per il piè di pagina.",
  "ui.choose_music_assistant_players_only_the_in_card_pinning_list_shows_only": "Scegli solo riproduttori di Music Assistant. L'elenco di fissaggio nella scheda mostra solo i riproduttori di Music Assistant per evitare confusione.",
  "ui.choose_one_clear_option": "Scegli un'opzione di svuotamento",
  "ui.choose_player": "Scegli riproduttore",
  "ui.choose_something_from_the_quick_shelf_or_tap_the_wand_for_a_random_playl": "Scegli qualcosa dallo scaffale rapido o tocca la bacchetta per una playlist casuale.",
  "ui.choose_source": "Scegli sorgente",
  "ui.choose_target": "Scegli destinazione",
  "ui.choose_target_player": "Scegli riproduttore di destinazione",
  "ui.choose_the_accent_color_for_the_mobile_layout": "Scegli il colore d'accento per il layout mobile.",
  "ui.choose_the_music": "Scegli la musica",
  "ui.choose_the_small_buttons_shown_under_the_song_title_timer_appears_first": "Scegli e ordina i piccoli pulsanti mostrati sotto il titolo della canzone.",
  "ui.choose_the_source_first_playback_will_use_the_current_target": "Scegli prima la sorgente. La riproduzione utilizzerà la destinazione corrente.",
  "ui.choose_where_to_play": "Scegli dove riprodurre",
  "ui.choose_whether_artwork_swipe_changes_track_or_browses_covers": "Scegli se lo scorrimento della copertina cambia brano o sfoglia le copertine.",
  "ui.choose_whether_settings_are_controlled_from_the_in_card_ui_or_from_the_c": "Scegli se le impostazioni sono controllate dall'interfaccia utente nella scheda o dalla configurazione della scheda nella dashboard.",
  "ui.choose_which_actions_appear_in_the_main_bar": "Scegli quali azioni appaiono nella barra principale.",
  "ui.choose_which_days_the_auto_night_mode_window_applies_to": "Scegli a quali giorni si applica la finestra della modalità notturna automatica.",
  "ui.choose_which_icons_appear_in_the_quick_action_row": "Scegli quali icone appaiono nella riga delle azioni rapide. 'Svuota tutto' chiede conferma prima di disconnettere i riproduttori attivi.",
  "ui.choose_which_players_appear_as_tiles_in_the_room": "Scegli quali riproduttori appaiono come riquadri nella stanza.",
  "ui.choose_which_players_stay_in_the_current_control_selection": "Scegli quali riproduttori rimangono nella selezione di controllo corrente.",
  "ui.choose_which_tabs_are_available_in_the_library_screen": "Scegli quali schede sono disponibili nella schermata della libreria.",
  "ui.choose_who_is_controlled": "Scegli chi controllare",
  "ui.choosing_visual_disables_the_in_card_settings_screen": "La scelta di 'Visuale' disabilita la schermata delle impostazioni all'interno della scheda.",
  "ui.clean_all": "Svuota tutto",
  "ui.clean_all_confirm_action": "Svuota tutto",
  "ui.clean_all_confirm_copy": "Questo disconnetterà tutti i riproduttori attivi, interromperà la riproduzione e svuoterà le loro code. Continuare?",
  "ui.clean_all_confirm_title": "Svuotare tutti i riproduttori?",
  "ui.clean_the_studio_wall": "Pulisci la parete dello Studio",
  "ui.clear": "Cancella",
  "ui.clear_queue": "Svuota coda",
  "ui.clear_search": "Cancella ricerca",
  "ui.clone_queue": "Clona coda",
  "ui.close": "Chiudi",
  "ui.collapse_compact_player": "Riduci riproduttore compatto",
  "ui.compact_mode": "Modalità compatta",
  "ui.configure_ready_made_announcement_phrases": "Configura frasi di annuncio pronte all'uso.",
  "ui.connect_this_device": "Connetti questo dispositivo",
  "ui.connect_this_device_2": "Connetti questo dispositivo",
  "ui.connected": "Connesso",
  "ui.connected_2": "Connesso",
  "ui.connected_players": "riproduttori connessi",
  "ui.connected_players_2": "Riproduttori connessi",
  "ui.connecting": "Connessione in corso",
  "ui.connecting_2": "Connessione in corso...",
  "ui.confirm": "Conferma",
  "ui.connection_and_behavior": "Connessione e comportamento",
  "ui.connects_directly_from_this_card_using_sendspin": "Si connette direttamente da questa scheda usando Sendspin",
  "ui.continue": "Continua",
  "ui.continue_2": "Continua",
  "ui.continue_from_recent_music_assistant_activity": "Continua dalle recenti attività di Music Assistant.",
  "ui.continue_listening": "Continua ad ascoltare",
  "ui.continue_what_was_played_recently": "Continua quello che è stato riprodotto di recente",
  "ui.control_whether_the_card_background_moves_gently_and_how_strong_the_moti": "Controlla se lo sfondo della scheda si muove delicatamente e l'intensità del movimento.",
  "ui.controlling": "Controllo di",
  "ui.could_not_build_quick_mix_from_the_current_song": "Impossibile creare un Mix Rapido dalla canzone corrente",
  "ui.could_not_build_studio_mix": "Impossibile creare il mix di Studio",
  "ui.could_not_choose_media": "Impossibile scegliere i contenuti multimediali",
  "ui.could_not_clone_the_queue": "Impossibile clonare la coda",
  "ui.could_not_find_music": "Impossibile trovare musica",
  "ui.could_not_play_label": "Impossibile riprodurre: {label}",
  "ui.could_not_start_chill_mix": "Impossibile avviare il mix relax",
  "ui.could_not_start_playback": "Impossibile avviare la riproduzione",
  "ui.could_not_start_playback_2": "Impossibile avviare la riproduzione",
  "ui.could_not_start_playback_in_studio": "Impossibile avviare la riproduzione in Studio",
  "ui.could_not_start_quick_mix": "Impossibile avviare il Mix Rapido",
  "ui.could_not_start_radio_playback": "Impossibile avviare la riproduzione radio",
  "ui.could_not_transfer_the_queue": "Impossibile trasferire la coda",
  "ui.could_not_update_active_player_helper": "Impossibile aggiornare l'aiutante del riproduttore attivo",
  "ui.create_schedule": "Crea programmazione",
  "ui.current_path": "Percorso corrente",
  "ui.custom": "Personalizzato",
  "ui.dark": "Scuro",
  "ui.delete_scene": "Elimina scena",
  "ui.delete_schedule": "Elimina programmazione",
  "ui.descending": "Decrescente",
  "ui.dictate": "Detta",
  "ui.disabled": "Disabilitato",
  "ui.disables_blur_animations_dynamic_backgrounds_and_heavy_shadows_recommend": "Disabilita sfocatura, animazioni, sfondi dinamici e ombre intense. Consigliato per Nest Hub e tablet meno potenti.",
  "ui.disconnect": "Disconnetti",
  "ui.disconnect_all": "Disconnetti tutto",
  "ui.disconnect_groups": "Disconnetti gruppi",
  "ui.disconnect_player_groups": "Disconnetti gruppi di riproduttori",
  "ui.disconnect_this_device": "Disconnetti questo dispositivo",
  "ui.disconnected": "Disconnesso",
  "ui.disconnecting": "Disconnessione in corso",
  "ui.disconnecting_player_groups": "Disconnessione dei gruppi di riproduttori...",
  "ui.discover": "Scopri",
  "ui.down": "Giù",
  "ui.dynamic_theme": "Tema dinamico",
  "ui.edit_schedule": "Modifica programmazione",
  "ui.enable": "Abilita",
  "ui.enable_or_disable_the_footer_search_button": "Abilita o disabilita il pulsante di ricerca nel piè di pagina.",
  "ui.enable_or_disable_the_studio_button_in_the_footer_bar": "Abilita o disabilita il pulsante Studio nella barra del piè di pagina.",
  "ui.enable_the_floating_home_shortcut_button": "Abilita la scorciatoia Home nelle Azioni Rapide.",
  "ui.enabled": "Abilitato",
  "ui.enables_switching_to_local_liked_mode": "Abilita il passaggio alla modalità dei preferiti locali.",
  "ui.end_time": "Ora di fine",
  "ui.excluded_players": "Riproduttori esclusi",
  "ui.energetic": "Energetico",
  "ui.energy_and_rhythm": "Energia e ritmo",
  "ui.enter_an_announcement_first": "Inserisci prima un annuncio",
  "ui.example_quiet_jazz_greek_music_workout": "Esempio: jazz calmo, musica greca, allenamento",
  "ui.existing_content": "Contenuto esistente",
  "ui.expand_player": "Espandi riproduttore",
  "ui.extract_colors_from_the_current_artwork_and_apply_them_to_the_interface": "Estrai i colori dalla copertina corrente e applicali all'interfaccia.",
  "ui.extreme": "Estremo",
  "ui.fallback_for_setups_that_need_an_alternate_queue_service_path": "Fallback per configurazioni che necessitano di un percorso alternativo per il servizio di coda.",
  "ui.fallback_mode": "Modalità di fallback",
  "ui.family_friendly": "Adatto alle famiglie",
  "ui.favorite": "Preferito",
  "ui.favorite_action_failed": "Azione preferito fallita",
  "ui.favorite_action_sent": "Azione preferito inviata",
  "ui.favorite_button_entity": "Entità pulsante preferito",
  "ui.favorite_center": "centro preferiti",
  "ui.favorite_center_2": "Centro Preferiti",
  "ui.favorite_radio": "Radio preferita",
  "ui.favorite_updated": "Preferito aggiornato",
  "ui.favorites_and_liked_music": "Preferiti e musica gradita",
  "ui.feature_detection_player_context_and_this_device_playback_tools": "Rilevamento delle funzionalità, contesto del riproduttore e strumenti di riproduzione per questo dispositivo.",
  "ui.find_music": "Trova musica",
  "ui.finding_music": "Ricerca musica in corso",
  "ui.fixed": "Fisso",
  "ui.flow_mix": "FLOW Mix",
  "ui.font_scale": "Scala carattere",
  "ui.font_size": "Dimensione carattere",
  "ui.footer_search": "Ricerca nel piè di pagina",
  "ui.footer_style": "Stile piè di pagina",
  "ui.footer_style_2": "Stile piè di pagina",
  "ui.for_example_lovelace_home_or_any_other_home_assistant_path": "Per esempio /lovelace/home o qualsiasi altro percorso di Home Assistant.",
  "ui.for_weaker_displays_turns_off_heavy_blur_animations_dynamic_theme_extrac": "Per schermi meno potenti: disattiva sfocatura intensa, animazioni, estrazione del tema dinamico e movimento dello sfondo.",
  "ui.france": "Francia",
  "ui.free_style": "Stile libero",
  "ui.free_style_quiet_jazz_greek_music_workout": "Stile libero: jazz calmo, musica greca, allenamento...",
  "ui.fresh_start": "Nuovo inizio",
  "ui.fresh_start_2": "Nuovo inizio",
  "ui.fri": "Ven",
  "ui.friendly_and_simple": "Intuitivo e semplice",
  "ui.from": "Da",
  "ui.general": "Generale",
  "ui.general_and_display": "Generale e Display",
  "ui.germany": "Germania",
  "ui.global_scale_for_every_interface_font_1_is_the_default_size": "Scala globale per tutti i caratteri dell'interfaccia. 1 è la dimensione predefinita.",
  "ui.greece": "Grecia",
  "ui.grid": "Griglia",
  "ui.group": "Gruppo",
  "ui.group_cleared": "Gruppo svuotato",
  "ui.group_cleared_2": "Gruppo svuotato",
  "ui.group_speakers": "Raggruppa altoparlanti",
  "ui.group_speakers_2": "Raggruppa altoparlanti",
  "ui.group_updated": "Gruppo aggiornato",
  "ui.group_volume": "Volume di gruppo",
  "ui.group_volume_up_energetic_mix": "Gruppo, alza il volume, mix energetico",
  "ui.grouped_players": "Riproduttori raggruppati",
  "ui.hebrew": "Ebraico",
  "ui.history": "Cronologia",
  "ui.history_tabs": "Schede cronologia",
  "ui.home": "Home",
  "ui.home_party_night_presets": "Preimpostazioni casa, festa, notte",
  "ui.home_path": "Percorso Home",
  "ui.home_scene_prepared": "Scena Home preparata",
  "ui.home_shortcut": "Scorciatoia Home",
  "ui.home_shortcut_path": "Percorso scorciatoia Home",
  "ui.icon_and_text": "Icona e testo",
  "ui.icon_only": "Solo icona",
  "ui.icon_plus_text": "Icona + testo",
  "ui.idle": "Inattivo",
  "ui.idle_2": "Inattivo",
  "ui.in_card_ui": "UI nella scheda",
  "ui.includes_the_custom_theme_mode_from_the_in_card_settings_screen": "Include la modalità del tema personalizzato dalla schermata delle impostazioni della scheda.",
  "ui.info": "Info",
  "ui.israel": "Israele",
  "ui.israeli": "Israeliano",
  "ui.italy": "Italia",
  "ui.items": "elementi",
  "ui.join_selected_players": "Unisci i riproduttori selezionati",
  "ui.kids": "Bambini",
  "ui.language": "Lingua",
  "ui.larger_lyrics": "Testo più grande",
  "ui.layout_adapted_to_height": "Layout adattato all'altezza",
  "ui.layout_mode": "Modalità layout",
  "ui.leave_empty_if_the_card_should_use_home_assistant_only": "Lascia vuoto se la scheda deve utilizzare solo Home Assistant.",
  "ui.library": "Libreria",
  "ui.library_2": "Libreria",
  "ui.library_pages": "Pagine della libreria",
  "ui.default_library_layout": "Layout predefinito della libreria",
  "ui.choose_how_library_pages_open_grid_or_list_can_still_be_changed_manually": "Scegli come aprire le pagine della libreria. Puoi comunque passare da Griglia a Elenco all'interno della libreria.",
  "ui.library_radio": "Radio della libreria",
  "ui.library_surprise": "Sorpresa della libreria",
  "ui.library_tabs": "Schede Libreria",
  "ui.library_tabs_2": "Schede libreria",
  "ui.light": "Chiaro",
  "ui.like": "Metti mi piace",
  "ui.like_2": "Metti mi piace",
  "ui.like_3": "Metti mi piace",
  "ui.liked": "Piaciuti",
  "ui.liked_mode": "Modalità preferiti",
  "ui.liked_sync": "Sincronizzazione preferiti",
  "ui.list": "Elenco",
  "ui.listening": "Ascolto in corso...",
  "ui.loading": "Caricamento...",
  "ui.loading_favorites": "Caricamento preferiti...",
  "ui.loading_library": "Caricamento libreria...",
  "ui.loading_lyrics": "Caricamento testo...",
  "ui.loading_players": "Caricamento riproduttori...",
  "ui.loading_queue": "Caricamento coda...",
  "ui.loading_recent_items": "Caricamento elementi recenti...",
  "ui.loading_schedules": "Caricamento programmazioni...",
  "ui.local": "Locale",
  "ui.local_favorites": "Preferiti locali",
  "ui.local_favorites_2": "Preferiti locali",
  "ui.local_mode_is_only_meaningful_when_local_likes_are_enabled": "La modalità locale ha senso solo quando i preferiti locali sono abilitati.",
  "ui.low_light_listening": "Ascolto a bassa luminosità",
  "ui.low_volume_and_quiet_mix": "Volume basso e mix tranquillo",
  "ui.lower_volume_mood": "Stato d'animo a volume ridotto",
  "ui.lyrics": "Testo",
  "ui.lyrics_earlier": "Anticipa testo",
  "ui.lyrics_font_size": "Dimensione carattere del testo",
  "ui.lyrics_later": "Ritarda testo",
  "ui.lyrics_timing": "Sincronizzazione testo",
  "ui.lyrics_unavailable_right_now": "Testo non disponibile in questo momento",
  "ui.ma_favorite_action_failed_with_error": "Azione preferito di Music Assistant fallita{error}",
  "ui.ma_interface_path": "Percorso interfaccia MA",
  "ui.main_bar": "Barra principale",
  "ui.main_bar_items": "Elementi barra principale",
  "ui.main_bar_items_2": "Elementi barra principale",
  "ui.main_opacity": "Opacità principale",
  "ui.mainly_relevant_on_larger_layouts": "Rilevante principalmente su layout più grandi.",
  "ui.mass_queue_send_command_fallback": "Fallback mass_queue/send_command",
  "ui.matches_the_microphone_setting_from_the_in_card_settings_screen": "Corrisponde all'impostazione del microfono dalla schermata delle impostazioni della scheda.",
  "ui.media": "Media",
  "ui.media_2": "Media",
  "ui.media_actions": "Azioni multimediali",
  "ui.media_layout": "Layout multimediale",
  "ui.media_selected_target": "Selezionato: {media} ? Destinazione: {target}",
  "ui.menu": "Menu",
  "ui.message": "Messaggio",
  "ui.microphone": "Microfono",
  "ui.microphone_2": "Microfono",
  "ui.microphone_is_disabled": "Il microfono è disabilitato",
  "ui.missing_url": "URL mancante",
  "ui.mobile": "Mobile",
  "ui.mon": "Lun",
  "ui.mood_style_or_free_text": "Stato d'animo, stile o testo libero",
  "ui.more_info": "Maggiori informazioni",
  "ui.more_info_is_unavailable_for_this_player": "Maggiori informazioni non disponibili per questo riproduttore",
  "ui.morning": "Mattina",
  "ui.morning_mix": "Mix mattutino",
  "ui.move_to_next": "Sposta al successivo",
  "ui.move_to_position": "Sposta alla posizione",
  "ui.music": "Musica",
  "ui.music_assistant_required": "Music Assistant richiesto",
  "ui.music_assistant_config_entry_id_if_you_want_direct_integration_lookup_th": "ID voce di configurazione di Music Assistant, se desideri la ricerca dell'integrazione diretta tramite Home Assistant.",
  "ui.music_assistant_config_entry_was_not_found": "La voce di configurazione di Music Assistant non è stata trovata",
  "ui.music_assistant_token": "Token di Music Assistant",
  "ui.music_assistant_url": "URL di Music Assistant",
  "ui.music_hub": "hub musicale",
  "ui.music_hub_2": "Hub Musicale",
  "ui.mute": "Silenzia",
  "ui.mute_command_failed": "Comando di silenziamento fallito",
  "ui.my_studio_scene": "La mia scena di Studio",
  "ui.name_or_keyword": "Nome o parola chiave",
  "ui.name_this_studio_scene": "Dai un nome a questa scena di Studio...",
  "ui.netherlands": "Paesi Bassi",
  "ui.new_schedule": "Nuova programmazione",
  "ui.new_wake_schedule": "Nuova programmazione risveglio",
  "ui.newest": "Più recenti",
  "ui.next": "Successivo",
  "ui.next_track_failed": "Brano successivo fallito",
  "ui.night": "Notte",
  "ui.night_end_time": "Ora di fine notte",
  "ui.night_mode": "Modalità notturna",
  "ui.night_mode_auto_window": "Modalità notturna auto {start}-{end}",
  "ui.night_mode_days": "Giorni modalità notturna",
  "ui.night_mode_is_always_on": "La modalità notturna è sempre attiva",
  "ui.night_mode_is_off": "La modalità notturna è disattivata",
  "ui.night_mode_is_off_until_you_choose_another_mode": "La modalità notturna è disattivata finché non si sceglie un'altra modalità.",
  "ui.night_mode_stays_on_until_you_choose_another_mode": "La modalità notturna rimane attiva finché non si sceglie un'altra modalità.",
  "ui.night_schedule_updated": "Programmazione notturna aggiornata",
  "ui.night_start_time": "Ora di inizio notte",
  "ui.no_active_media": "Nessun contenuto multimediale attivo",
  "ui.no_active_players": "Nessun riproduttore attivo",
  "ui.no_available_players": "Nessun riproduttore disponibile",
  "ui.no_content_found": "Nessun contenuto trovato",
  "ui.no_dynamic_player_groups_to_disconnect": "Nessun gruppo di riproduttori dinamici da disconnettere",
  "ui.no_extra_ma_players": "Nessun riproduttore MA aggiuntivo",
  "ui.no_extra_ma_players_2": "Nessun riproduttore MA aggiuntivo",
  "ui.no_favorites_found": "Nessun preferito trovato.",
  "ui.no_liked_media_yet": "Ancore nessun contenuto tra i preferiti",
  "ui.no_liked_tracks_to_play": "Nessun brano preferito da riprodurre",
  "ui.no_light_entities_found": "Nessuna entità di illuminazione trovata.",
  "ui.no_lyrics_found": "Testo non trovato",
  "ui.no_matching_content_was_found": "Nessun contenuto corrispondente trovato",
  "ui.no_media_found": "Nessun contenuto multimediale trovato.",
  "ui.no_media_found_for_this_search": "Nessun contenuto multimediale trovato per questa ricerca.",
  "ui.no_mix_content_found": "Nessun contenuto mix trovato",
  "ui.no_music_assistant_players_were_found_check_music_assistant_and_media_pl": "Music Assistant è richiesto. Abilita l'integrazione di Music Assistant in Home Assistant ed esponi almeno un riproduttore multimediale Music Assistant. Gli altri riproduttori di Home Assistant sono intenzionalmente nascosti.",
  "ui.no_music_assistant_players_were_found_for_pinning": "Nessun riproduttore di Music Assistant trovato da fissare.",
  "ui.no_next_track_in_queue": "Nessun brano successivo in coda",
  "ui.no_player_groups_to_disconnect": "Nessun gruppo di riproduttori da disconnettere",
  "ui.no_player_light_pairs_yet": "Nessuna associazione riproduttore-luce definita.",
  "ui.no_player_selected": "Nessun riproduttore selezionato",
  "ui.no_players_found": "Nessun riproduttore trovato",
  "ui.no_players_found_yet": "Nessun riproduttore ancora trovato",
  "ui.no_playlists_found": "Nessuna playlist trovata",
  "ui.no_queue": "Nessuna coda",
  "ui.no_queue_item_to_rebuild": "Nessun elemento in coda da ricostruire",
  "ui.no_queue_to_clone": "Nessuna coda da clonare",
  "ui.no_radio_browser_countries_found": "Nessun paese trovato in Radio Browser",
  "ui.no_radio_stations_found": "Nessuna stazione radio trovata",
  "ui.no_recent_listening_yet": "Nessun ascolto recente.",
  "ui.no_results": "Nessun risultato",
  "ui.no_results_found": "Nessun risultato trovato",
  "ui.no_saved_studio_scenes_yet": "Nessuna scena di Studio salvata.",
  "ui.no_scheduled_start_is_active": "Nessun avvio programmato attivo",
  "ui.no_selected_tracks_to_play": "Nessun brano selezionato da riprodurre",
  "ui.no_sleep_timer_is_active": "Nessun timer di spegnimento attivo",
  "ui.no_speech_was_captured": "Nessun discorso è stato acquisito",
  "ui.no_target_players_available": "Nessun riproduttore di destinazione disponibile",
  "ui.no_target_players_available_2": "Nessun riproduttore di destinazione disponibile",
  "ui.no_tts_service_or_entity_is_configured": "Nessun servizio o entità TTS configurata",
  "ui.no_wake_schedules_yet": "Nessuna programmazione risveglio presente",
  "ui.none": "Nessuno",
  "ui.nothing_is_playing_right_now": "Nulla è in riproduzione in questo momento",
  "ui.nothing_playing": "Nulla in riproduzione",
  "ui.now_playing": "In riproduzione",
  "ui.now_playing_2": "In riproduzione",
  "ui.off": "Spento",
  "ui.off_2": "Spento",
  "ui.off_disables_it_on_keeps_it_active_and_auto_follows_the_configured_time": "'Spento' lo disabilita, 'Acceso' lo mantiene attivo e 'Auto' segue la finestra temporale configurata.",
  "ui.oldest": "Più datati",
  "ui.on": "Acceso",
  "ui.one_tap_prepares_players_grouping_volume_and_content_save_your_own_curre": "Un solo tocco prepara i riproduttori, il raggruppamento, il volume e il contenuto. Salva la tua destinazione Studio corrente come scena locale.",
  "ui.only_actions_for_the_current_target_are_shown_here": "Qui vengono mostrate solo le azioni per la destinazione corrente.",
  "ui.only_music_assistant_players_are_shown_here_browser_and_local_sendspin_p": "Qui vengono mostrati solo i riproduttori di Music Assistant. I riproduttori del browser e quelli locali di Sendspin sono nascosti per evitare confusione.",
  "ui.only_needed_when_using_a_direct_music_assistant_url": "Necessario solo quando si utilizza un URL diretto di Music Assistant.",
  "ui.opacity_for_popups_and_overlays": "Opacità per finestre a comparsa e sovrapposizioni.",
  "ui.opacity_for_the_main_card_background": "Opacità per lo sfondo della scheda principale.",
  "ui.open_full_interface": "Apri l'interfaccia completa",
  "ui.open_full_queue": "Apri la coda completa",
  "ui.open_interface_in": "Apri l'interfaccia in",
  "ui.open_ma": "Apri MA",
  "ui.open_music_assistant": "Apri Music Assistant",
  "ui.open_music_assistant_2": "Apri Music Assistant?",
  "ui.open_music_assistant_on_this_device_to_activate_the_browser_player": "Apri Music Assistant su questo dispositivo per attivare il riproduttore del browser",
  "ui.open_player_picker": "Apri selettore riproduttori",
  "ui.open_queue": "Apri coda",
  "ui.open_saved_songs": "Apri canzoni salvate",
  "ui.open_the_full_music_assistant_interface": "Apri l'interfaccia completa di Music Assistant?",
  "ui.open_the_full_music_assistant_interface_2": "Apri l'interfaccia completa di Music Assistant",
  "ui.opening_studio_library": "Apertura libreria di Studio",
  "ui.opening_timers": "Apertura timer",
  "ui.option": "Opzione",
  "ui.optional": "Opzionale",
  "ui.optional_2": "Opzionale",
  "ui.optional_entity_used_for_an_external_favorite_button": "Entità opzionale utilizzata per un pulsante dei preferiti esterno.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for": "Aiutante input_text opzionale aggiornato con l'entity_id del riproduttore attivo per automazioni e modelli.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for_2": "Aiutante input_text opzionale aggiornato con l'entity_id del riproduttore attivo per automazioni e modelli.",
  "ui.other": "Altro",
  "ui.other_players": "Altri riproduttori",
  "ui.party": "Festa",
  "ui.path_used_when_opening_the_music_assistant_interface": "Percorso utilizzato per l'apertura dell'interfaccia di Music Assistant.",
  "ui.pause": "Pausa",
  "ui.paused": "In pausa",
  "ui.per_device_in_card": "Per dispositivo / nella scheda",
  "ui.performance_mode": "Modalità prestazioni",
  "ui.performance_mode_for_weak_devices": "Modalità prestazioni per dispositivi deboli",
  "ui.performance_profile": "Profilo prestazioni",
  "ui.performance_profile_helper": "Scegli quanto carico grafico consentire alla scheda. 'Ultra leggero' riduce trasparenze, sfocature, copertine dinamiche e movimenti per i dispositivi meno potenti.",
  "ui.pick_a_mood_or_type_your_own_style_studio_will_search_music_assistant_an": "Scegli uno stato d'animo o digita il tuo stile. Studio cercherà su Music Assistant e creerà una coda.",
  "ui.pinned": "Fissati",
  "ui.pinned_players": "Riproduttori fissati",
  "ui.play": "Riproduci",
  "ui.play_2": "Riproduci",
  "ui.play_a_few_tracks_and_they_will_appear_here": "Riproduci qualche brano e compariranno qui.",
  "ui.play_a_saved_list": "Riproduci un elenco salvato",
  "ui.play_all": "Riproduci tutto",
  "ui.play_an_artist": "Riproduci un artista",
  "ui.play_artwork_action": "Azione di riproduzione copertina",
  "ui.play_everywhere": "Riproduci ovunque",
  "ui.play_next": "Riproduci successivo",
  "ui.play_next_and_clear_queue": "Riproduci successivo e svuota coda",
  "ui.play_now": "Riproduci ora",
  "ui.play_now_and_clear_queue": "Riproduci ora e svuota coda",
  "ui.play_pause": "Riproduci / Pausa",
  "ui.play_queue_radio_or_remove_favorites_directly_from_studio": "Riproduci, metti in coda, avvia la radio o rimuovi i preferiti direttamente da Studio.",
  "ui.play_selected": "Riproduci selezionati",
  "ui.playback_command_failed": "Comando di riproduzione fallito",
  "ui.playback_command_failed_2": "Comando di riproduzione fallito",
  "ui.playback_started": "Riproduzione avviata",
  "ui.player": "riproduttore",
  "ui.player_2": "Riproduttore",
  "ui.player_count_many": "{count} riproduttori",
  "ui.player_count_one": "1 riproduttore",
  "ui.player_groups_could_not_be_disconnected": "Impossibile disconnettere i gruppi di riproduttori",
  "ui.player_is_pinned_from_settings": "Il riproduttore è fissato dalle impostazioni",
  "ui.player_is_ready": "Il riproduttore è pronto",
  "ui.player_is_ready_nothing_is_playing_right_now": "Il riproduttore è pronto - nulla è in riproduzione al momento",
  "ui.player_order": "Ordine riproduttori",
  "ui.player_on_this_device": "Riproduttore su questo dispositivo",
  "ui.player_selected": "Riproduttore selezionato",
  "ui.player_settings_and_dsp_presets_stay_read_only_until_music_assistant_exp": "Le impostazioni del riproduttore e i preset DSP rimangono in sola lettura finché Music Assistant non espone uno schema affidabile per questo riproduttore.",
  "ui.player_sort": "Ordinamento riproduttori",
  "ui.players": "Riproduttori",
  "ui.players_queue_and_groups": "Riproduttori, coda e gruppi",
  "ui.playing": "In riproduzione",
  "ui.playing_a_random_playlist": "Riproduzione di una playlist casuale",
  "ui.playing_a_random_radio_station": "Riproduzione di una stazione radio casuale",
  "ui.playing_on": "In riproduzione su",
  "ui.playing_on_2": "In riproduzione su",
  "ui.playlist": "Playlist",
  "ui.playlists": "Playlist",
  "ui.podcast": "Podcast",
  "ui.podcasts": "Podcast",
  "ui.popup_opacity": "Opacità popup",
  "ui.preset_message": "Messaggio preimpostato",
  "ui.previous": "Precedente",
  "ui.primary": "Primario",
  "ui.primary_target": "Destinazione primaria",
  "ui.pro_tools": "Strumenti Pro",
  "ui.queue": "Coda",
  "ui.queue_2": "Coda",
  "ui.queue_action_failed": "Azione sulla coda fallita",
  "ui.queue_action_is_not_available_for_this_player": "L'azione sulla coda non è disponibile per questo riproduttore",
  "ui.queue_actions": "Azioni sulla coda",
  "ui.queue_cleared": "Coda svuotata",
  "ui.queue_cleared_and_item_moved_next": "Coda svuotata ed elemento spostato al successivo",
  "ui.queue_cloned": "Coda clonata",
  "ui.queue_cockpit": "cabina di pilotaggio coda",
  "ui.queue_cockpit_2": "Pannello della Coda",
  "ui.queue_is_empty": "La coda è vuota",
  "ui.queue_is_unavailable_for_this_player": "La coda non è disponibile per questo riproduttore",
  "ui.queue_item": "Elemento in coda",
  "ui.queue_item_id_is_not_ready_yet_refresh_the_queue_and_try_again": "L'ID dell'elemento in coda non è ancora pronto. Aggiorna la coda e riprova.",
  "ui.queue_results": "Risultati della coda",
  "ui.queue_transferred": "Coda trasferita",
  "ui.queues_refreshed": "Code aggiornate",
  "ui.quick_actions": "Azioni rapide",
  "ui.quick_actions_2": "Azioni Rapide",
  "ui.quick_mix": "Mix rapido",
  "ui.quick_mix_started": "Mix rapido avviato",
  "ui.quick_play": "Riproduzione rapida",
  "ui.radio": "Radio",
  "ui.radio_browser": "Radio Browser",
  "ui.radio_browser_countries": "Paesi di Radio Browser",
  "ui.radio_browser_country": "Paese di Radio Browser",
  "ui.radio_browser_country_2": "Paese di Radio Browser",
  "ui.radio_mode_is_not_available_for_this_media_type": "La modalità radio non è disponibile per questo tipo di contenuto multimediale",
  "ui.radio_mode_started": "Modalità radio avviata",
  "ui.radio_station_changed": "Stazione radio cambiata",
  "ui.radio_stations": "Stazioni Radio",
  "ui.random": "Casuale",
  "ui.random_gentle_morning_mix": "Mix mattutino delicato casuale",
  "ui.random_playlist": "Playlist casuale",
  "ui.random_radio": "Radio casuale",
  "ui.ready": "Pronto",
  "ui.ready_to_play": "Pronto a riprodurre",
  "ui.recent": "Recenti",
  "ui.recent_continue": "Recenti / Continua",
  "ui.recent_listening": "ascolti recenti",
  "ui.recent_track": "Brano recente",
  "ui.recently_added": "Aggiunti di recente",
  "ui.recently_played": "Riprodotti di recente",
  "ui.recently_played_2": "Riprodotti di recente",
  "ui.recommendations_will_appear_once_homeii_flow_sees_your_queue_or_recent_l": "I consigli appariranno non appena HOMEii Flow rileverà la tua coda o gli ascolti recenti.",
  "ui.recommended": "Consigliati",
  "ui.recommended_format_hh_mm_such_as_06_00_crossing_midnight_is_supported": "Formato consigliato: HH:MM ad esempio 06:00. Il passaggio oltre la mezzanotte è supportato.",
  "ui.recommended_format_hh_mm_such_as_22_00": "Formato consigliato: HH:MM ad esempio 22:00.",
  "ui.recommended_playlist": "Playlist consigliata",
  "ui.recommended_track": "Brano consigliato",
  "ui.reconnects_when_you_return_to_this_dashboard": "Si riconnette quando ritorni in questa dashboard",
  "ui.refresh": "Aggiorna",
  "ui.remember_as_this_device": "Ricorda come questo dispositivo",
  "ui.remove": "Rimuovi",
  "ui.remove_from_selection": "Rimuovi dalla selezione",
  "ui.removed_from_liked": "Rimosso dai preferiti",
  "ui.removed_from_music_assistant_liked": "Rimosso dai preferiti di Music Assistant",
  "ui.reorder_queue": "Riordina coda",
  "ui.repeat": "Ripeti",
  "ui.repeat_all": "Ripeti tutti",
  "ui.repeat_off": "Ripetizione disattivata",
  "ui.repeat_one": "Ripeti uno",
  "ui.reset": "Ripristina",
  "ui.reset_lyrics_font_size": "Ripristina dimensione carattere del testo",
  "ui.reset_lyrics_timing": "Ripristina sincronizzazione del testo",
  "ui.results": "Risultati",
  "ui.rtl": "RTL",
  "ui.sat": "Sab",
  "ui.save_current_target": "Salva destinazione corrente",
  "ui.save_schedule": "Salva programmazione",
  "ui.scene_players_are_not_available": "I riproduttori della scena non sono disponibili",
  "ui.scene_presets": "preimpostazioni della scena",
  "ui.scene_presets_2": "Preimpostazioni della Scena",
  "ui.scenes": "Scene",
  "ui.scales_interface_icons_without_changing_button_sizes": "Scala le icone dell'interfaccia senza modificare la dimensione dei pulsanti o il layout.",
  "ui.scheduled_start": "Avvio programmato",
  "ui.scheduled_start_activated_label": "Avvio programmato attivato: {label}",
  "ui.scheduled_start_cleared": "Avvio programmato annullato",
  "ui.scheduled_start_failed": "Avvio programmato fallito",
  "ui.scheduled_start_saved": "Avvio programmato salvato",
  "ui.scheduled_starts_active_count": "{count} avvii programmati attivi",
  "ui.schedules": "Programmazioni",
  "ui.search": "Cerca",
  "ui.search_and_choose_play_next_add_radio_or_like": "Cerca e scegli Riproduci, Successivo, Aggiungi, Radio o Mi Piace.",
  "ui.search_everything": "Cerca ovunque...",
  "ui.search_failed": "Ricerca fallita",
  "ui.search_in_queue": "Cerca nella coda",
  "ui.search_queue_and_library": "Cerca nella coda e nella libreria...",
  "ui.search_the_library": "Cerca nella libreria...",
  "ui.search_tracks_albums_artists_and_playlists": "Cerca brani, album, artisti e playlist",
  "ui.searching": "Ricerca in corso...",
  "ui.searching_library": "Ricerca nella libreria...",
  "ui.searching_smart_selection": "Ricerca selezione intelligente...",
  "ui.seek": "Posiziona",
  "ui.select": "Seleziona",
  "ui.select_lights": "Seleziona una o più luci",
  "ui.select_player": "Seleziona riproduttore",
  "ui.select_2": "Seleziona",
  "ui.select_a_player_first": "Seleziona prima un riproduttore",
  "ui.select_at_least_one_studio_player": "Seleziona almeno un riproduttore di Studio",
  "ui.select_at_least_two_players_to_create_a_group": "Seleziona almeno due riproduttori per creare un gruppo",
  "ui.selected": "Selezionato",
  "ui.selected_music": "Musica selezionata",
  "ui.selected_player": "Riproduttore Selezionato",
  "ui.selected_player_2": "Riproduttore selezionato",
  "ui.selected_player_3": "Riproduttore selezionato",
  "ui.selected_players_at_comfortable_volume": "Riproduttori selezionati a volume confortevole",
  "ui.selected_playlist": "Playlist selezionata",
  "ui.send_a_short_voice_message_or_announcement_url": "Invia un breve messaggio vocale o un URL di annuncio.",
  "ui.send_a_voice_message": "Invia un messaggio vocale",
  "ui.send_announcement": "Invia annuncio",
  "ui.sendspin_and_diagnostics": "Sendspin e diagnostica",
  "ui.set_sleep_timer": "Imposta timer di spegnimento",
  "ui.set_volume": "Imposta volume",
  "ui.set_the_visual_order_of_quick_actions": "Imposta l'ordine visivo. Verranno mostrate solo le Azioni Rapide selezionate; gli elementi non selezionati saranno ignorati.",
  "ui.settings": "Impostazioni",
  "ui.settings_source": "Sorgente impostazioni",
  "ui.show_confirmation_toasts": "Mostra i messaggi di conferma",
  "ui.show_confirmation_toasts_helper": "Mostra brevi messaggi di conferma dopo azioni come la selezione di un lettore o l'aggiunta ai preferiti. Disattivare per sopprimere questi messaggi; i messaggi di errore appaiono comunque.",
  "ui.show_ma_button": "Mostra pulsante MA",
  "ui.show_or_hide_the_inline_next_track_row_in_now_playing": "Mostra o nascondi la riga integrata del brano successivo in 'In Riproduzione'.",
  "ui.show_theme_toggle": "Mostra interruttore tema",
  "ui.show_up_next": "Mostra successivo",
  "ui.show_up_next_2": "Mostra successivo",
  "ui.shows_a_standalone_compact_player_tile_with_artwork_basic_controls_volum": "Mostra un riquadro indipendente del riproduttore compatto con copertina, controlli di base, volume e un'azione di espansione.",
  "ui.shuffle": "Riproduzione casuale",
  "ui.shuffle_all": "Riproduzione casuale tutto",
  "ui.shuffle_favorites": "Riproduzione casuale preferiti",
  "ui.shuffle_play": "Riproduci in modo casuale",
  "ui.skipped_to_up_next": "Passato al brano successivo",
  "ui.sleep_timer": "Timer di spegnimento",
  "ui.sleep_timer_2": "Timer di Spegnimento",
  "ui.sleep_timer_active_remaining": "Timer di spegnimento attivo: {remaining}",
  "ui.sleep_timer_added_minutes": "Aggiunti {minutes} minuti al timer",
  "ui.sleep_timer_and_morning_playback": "Timer di spegnimento e riproduzione mattutina",
  "ui.sleep_timer_and_scheduled_playback": "Timer di spegnimento e riproduzione programmata",
  "ui.sleep_timer_cleared": "Timer di spegnimento annullato",
  "ui.sleep_timer_finished": "Timer di spegnimento terminato",
  "ui.sleep_timer_presets": "Preimpostazioni timer di spegnimento",
  "ui.sleep_timer_set_for_15_minutes": "Timer di spegnimento impostato su 15 minuti",
  "ui.sleep_timer_set_minutes": "Timer di spegnimento impostato su {minutes} minuti",
  "ui.sleep_timer_updated_minutes": "Timer di spegnimento aggiornato a {minutes} minuti",
  "ui.smaller_lyrics": "Testo più piccolo",
  "ui.smart": "Intelligente",
  "ui.smart_mix": "mix intelligente",
  "ui.smart_mix_builder": "Creatore Mix Intelligente",
  "ui.smart_voice_selection": "Selezione vocale intelligente",
  "ui.soft_and_relaxed": "Morbida e rilassante",
  "ui.soft_relaxed_music": "Musica morbida e rilassante",
  "ui.some_players_could_not_be_stopped_or_cleared": "Impossibile arrestare o svuotare alcuni riproduttori",
  "ui.songs_around_an_artist": "Brani correlati a un artista",
  "ui.sort": "Ordina",
  "ui.sort_ascending": "Ordina in modo crescente",
  "ui.sort_descending": "Ordina in modo decrescente",
  "ui.source_queue": "Coda sorgente",
  "ui.spain": "Spagna",
  "ui.speak_to_target_players": "Parla ai riproduttori di destinazione",
  "ui.start_radio_mode": "Avvia modalità radio",
  "ui.start_time": "Ora di inizio",
  "ui.start_time_2": "Ora di inizio",
  "ui.started_on_selected_player": "Avviato sul riproduttore selezionato",
  "ui.starting_a_chill_mix": "Avvio di un mix relax",
  "ui.starting_quick_mix": "Avvio Mix Rapido...",
  "ui.stations": "stazioni",
  "ui.stay_active": "Rimani attivo",
  "ui.stays_active": "Rimane attivo",
  "ui.stop_all": "Ferma tutto",
  "ui.stop_all_players": "Ferma tutti i riproduttori",
  "ui.stop_command_failed": "Comando di arresto fallito",
  "ui.stop_playback_clear_queues_and_disconnect_groups": "Interrompi la riproduzione, svuota le code e disconnetti i gruppi",
  "ui.stopped_all_players_cleared_playlists_and_disconnected_groups": "Arrestati tutti i riproduttori, svuotate le playlist e disconnessi i gruppi",
  "ui.stops_this_browser_player": "Arresta questo riproduttore del browser",
  "ui.strong": "Forte",
  "ui.studio": "Studio",
  "ui.studio_closed": "Studio chiuso",
  "ui.studio_media_action_failed": "Azione multimediale Studio fallita",
  "ui.studio_mix_started": "Mix di Studio avviato",
  "ui.studio_opened": "Studio aperto",
  "ui.studio_pro": "studio pro",
  "ui.studio_pro_2": "Studio Pro",
  "ui.studio_scene": "Scena di Studio",
  "ui.studio_scene_deleted": "Scena di Studio eliminata",
  "ui.studio_scene_saved": "Scena di Studio salvata",
  "ui.studio_scene_was_not_found": "La scena di Studio non è stata trovata",
  "ui.studio_search": "ricerca studio",
  "ui.studio_shortcut": "Scorciatoia Studio",
  "ui.subtle": "Tenue",
  "ui.sun": "Dom",
  "ui.surprise_me": "Sorprendimi",
  "ui.sync": "Sincronizza",
  "ui.sync_lyrics": "Sincronizza testo",
  "ui.tablet": "Tablet",
  "ui.tap_to_start_a_sleep_timer": "Tocca per avviare un timer di spegnimento",
  "ui.target_players": "Riproduttori di destinazione",
  "ui.target_queue": "Coda di destinazione",
  "ui.text_announcements_use_home_assistant_tts_into_the_selected_music_assist": "Gli annunci di testo utilizzano il TTS di Home Assistant sul riproduttore Music Assistant selezionato. Gli annunci via URL utilizzano la riproduzione degli annunci di Music Assistant.",
  "ui.text_only": "Solo testo",
  "ui.text_tone": "Tono del testo",
  "ui.theme": "Tema",
  "ui.theme_2": "Tema",
  "ui.theme_mode": "Modalità tema",
  "ui.theme_toggle": "Interruttore tema",
  "ui.theme_toggle_2": "Interruttore tema",
  "ui.this_device": "Questo Dispositivo",
  "ui.this_device_2": "Questo dispositivo",
  "ui.this_device_player_connected": "Riproduttore di questo dispositivo connesso",
  "ui.this_device_player_disconnected": "Riproduttore di questo dispositivo disconnesso",
  "ui.thu": "Gio",
  "ui.timer": "Timer",
  "ui.timer_active_remaining": "Timer attivo: {remaining}",
  "ui.timers": "Timer",
  "ui.to": "A",
  "ui.today": "Oggi",
  "ui.track": "Brano",
  "ui.track_lyrics": "Testo del brano",
  "ui.tracks": "Brani",
  "ui.transfer_clone_inspect_or_clear_queues_without_hiding_the_studio": "Trasferisci, clona, ispeziona o svuota le code senza nascondere lo Studio.",
  "ui.transfer_is_unavailable_while_a_pinned_player_is_configured": "Il trasferimento non è disponibile quando è configurato un riproduttore fissato",
  "ui.transfer_queue": "Trasferisci Coda",
  "ui.transfer_queue_2": "Trasferisci coda",
  "ui.transfer_queue_3": "Trasferisci coda",
  "ui.try_again": "Riprova",
  "ui.tts_entity": "Entità TTS",
  "ui.tts_entity_used_by_the_announcement_screen": "Entità TTS utilizzata dalla schermata degli annunci.",
  "ui.tts_language": "Lingua TTS",
  "ui.tue": "Mar",
  "ui.turkey": "Turchia",
  "ui.turn_off": "Spegni",
  "ui.turns_off_after_run": "Si spegne dopo l'esecuzione",
  "ui.turns_off_heavy_visuals_so_the_card_runs_smoother_on_nest_hub_older_tabl": "Disattiva gli elementi grafici complessi per rendere la scheda più fluida su Nest Hub, tablet datati e schermi meno potenti.",
  "ui.type_a_free_style_first": "Digita prima uno stile libero",
  "ui.type_an_announcement": "Digita un annuncio...",
  "ui.type_anything": "Digita qualsiasi cosa",
  "ui.type_what_should_be_announced": "Digita cosa annunciare...",
  "ui.ungroup": "Separa",
  "ui.ungroup_2": "Separa",
  "ui.united_kingdom": "Regno Unito",
  "ui.united_states": "Stati Uniti",
  "ui.unknown": "Sconosciuto",
  "ui.up": "Su",
  "ui.move_down": "Sposta giù",
  "ui.move_up": "Sposta su",
  "ui.up_next": "Prossimo brano",
  "ui.up_next_2": "Prossimo brano",
  "ui.up_next_title": "Prossimo brano: {title}",
  "ui.upbeat_and_moving": "Incalzante e movimentata",
  "ui.use_any_home_assistant_path_example_lovelace_home": "Usa qualsiasi percorso di Home Assistant. Esempio: /lovelace/home",
  "ui.use_current_view_for_home_button": "Usa la vista corrente per il pulsante Home",
  "ui.use_expand_to_open_the_full_player": "Usa espandi per aprire il riproduttore completo",
  "ui.uses_the_same_base_country_list_shown_in_the_in_card_settings_screen": "Utilizza lo stesso elenco di paesi base mostrato nella schermata delle impostazioni della scheda.",
  "ui.visible_tiles": "riquadri visibili",
  "ui.visible_tiles_2": "Riquadri visibili",
  "ui.visual_editor": "Editor visuale",
  "ui.assist_agent": "Agente Assist",
  "ui.assist_agent_id": "ID agente Assist",
  "ui.assist_only": "Solo Assist",
  "ui.default_assist_agent": "Assistente predefinito di Home Assistant",
  "ui.default_order": "Ordine predefinito",
  "ui.hybrid_handles_music_locally_and_sends_unknown_commands_to_assist": "Consigliato: i comandi musicali vengono eseguiti localmente sul riproduttore selezionato. Tutto ciò che la scheda non comprende viene inviato ad Assist di Home Assistant.",
  "ui.hybrid_music_plus_assist": "Ibrido: Musica + Assist",
  "ui.icon_size": "Dimensione icona",
  "ui.music_only": "Solo musica",
  "ui.music_plus_assist": "Musica + Assist",
  "ui.optional_assist_agent_id_leave_empty_for_home_assistant_default": "ID agente Assist opzionale. Lascia vuoto per utilizzare l'agente predefinito di Home Assistant.",
  "ui.optional_assist_agent_leave_empty_for_home_assistant_default": "Opzionale. Lascia l'agente predefinito a meno che tu non disponga di più agenti Assist e desideri che questa scheda ne utilizzi uno specifico.",
  "ui.show_a_push_to_talk_button_for_music_and_assist_commands": "Mostra un pulsante push-to-talk per i comandi musicali e il fallback di Assist.",
  "ui.show_home_inside_quick_actions": "Mostra Home come Azione Rapida invece di un pulsante fluttuante.",
  "ui.show_plus_minus_buttons_next_to_the_volume_slider": "Mostra i pulsanti più e meno accanto al cursore del volume.",
  "ui.speak_voice_assistant_responses_out_loud": "Pronuncia la risposta riconosciuta ad alta voce tramite questo browser quando supportato.",
  "ui.flow_assistant": "FLOW ASSISTANT",
  "ui.voice_assistant": "Assistente vocale",
  "ui.voice_assistant_disabled": "L'assistente vocale è disabilitato",
  "ui.voice_assistant_listening": "In ascolto di un comando...",
  "ui.voice_assistant_mode": "Modalità assistente vocale",
  "ui.voice_command_executed": "Comando vocale eseguito",
  "ui.voice_command_completed_action": "Fatto: {action}",
  "ui.voice_command_failed": "Comando vocale fallito",
  "ui.voice_command_no_player": "Seleziona un riproduttore o pronuncia il nome del riproduttore.",
  "ui.voice_command_not_understood": "Non ho capito questo comando.",
  "ui.voice_command_sent": "Comando vocale inviato",
  "ui.voice_done_status": "Fatto",
  "ui.voice_error_status": "Richiede attenzione",
  "ui.voice_feedback": "Feedback vocale",
  "ui.voice_group_connect_needs_players": "Pronuncia almeno due nomi di riproduttori, oppure selezionane uno e pronuncia l'altro.",
  "ui.voice_group_connected_players": "Connesso {primary} con {members}",
  "ui.voice_group_disconnect_needs_player": "Pronuncia quale gruppo di riproduttori disconnettere.",
  "ui.voice_group_disconnected_player": "Disconnesso il gruppo per {player}",
  "ui.voice_input_failed": "Input vocale fallito",
  "ui.voice_input_is_not_supported_on_this_device": "L'input vocale non è supportato su questo dispositivo",
  "ui.voice_language_is_not_supported": "Questo browser non supporta la lingua di riconoscimento vocale selezionata.",
  "ui.voice_match_not_confident": "Ho trovato {title}, ma non corrisponde abbastanza a \"{query}\". Prova a pronunciare nuovamente il brano e l'artista.",
  "ui.voice_music_searching": "Ricerca musica: {query}",
  "ui.voice_playing_result": "Riproduzione di {title}",
  "ui.voice_queue_transfer_needs_players": "Pronuncia il riproduttore di origine e di destinazione, ad esempio: trasferisci la coda dal soggiorno alla cucina.",
  "ui.voice_queue_transferred_between": "Coda trasferita da {source} a {target}",
  "ui.voice_starting_playback": "Avvio di {title}...",
  "ui.voice_processing_status": "Elaborazione del comando...",
  "ui.voice_ready_status": "Pronto",
  "ui.voice_recognition_network_failed": "Il servizio di riconoscimento vocale non è disponibile. I permessi del microfono potrebbero essere corretti; verifica il browser, VPN, DNS, firewall o la rete.",
  "ui.voice_response": "Risposta",
  "ui.voice_response_will_appear_here": "La risposta apparirà qui.",
  "ui.voice_search": "Ricerca vocale",
  "ui.voice_search_failed": "Ricerca vocale fallita",
  "ui.voice_search_is_not_supported_on_this_device": "La ricerca vocale non è supportata su questo dispositivo",
  "ui.voice_transcript": "Trascrizione",
  "ui.voice_listening_status": "In ascolto...",
  "ui.waiting_for_speech": "In attesa del parlato...",
  "ui.microphone_permission_or_browser_blocked": "Il browser ha bloccato il riconoscimento vocale. Controlla le impostazioni del microfono e della voce del browser.",
  "ui.volume": "Volume",
  "ui.volume_and_player_target": "Volume e riproduttore di destinazione",
  "ui.volume_boost": "Incremento volume",
  "ui.volume_control_large_screen_only": "Controllo volume (solo schermi grandi)",
  "ui.volume_down": "Abbassa volume",
  "ui.volume_mode": "Modalità volume",
  "ui.volume_presets": "Preimpostazioni volume",
  "ui.volume_step_between_1_and_10_percent_default_5": "Passo del volume tra 1% e 10%. Il valore predefinito è 5%.",
  "ui.volume_step_buttons": "Pulsanti volume +/-",
  "ui.volume_step_percent": "Passo del volume",
  "ui.volume_up": "Alza volume",
  "ui.waiting_for_this_device_player": "In attesa del riproduttore di questo dispositivo...",
  "ui.wake": "Risveglio",
  "ui.wake_schedules": "Programmazioni risveglio",
  "ui.wed": "Mer",
  "ui.week": "Settimana",
  "ui.what_would_you_like_to_listen_to": "Cosa ti piacerebbe ascoltare?",
  "ui.will_play_next": "Sarà riprodotto successivamente",
  "ui.will_play_next_in_studio": "Sarà riprodotto successivamente in Studio",
  "ui.worldwide_popular": "Popolari in tutto il mondo",
  "ui.add_player_light_pair": "Aggiungi associazione",
  "ui.ambient_light": "Luce d'ambiente",
  "ui.ambient_light_brightness": "Luminosità della luce",
  "ui.ambient_light_cooldown": "Tempo di ricarica aggiornamento luce",
  "ui.ambient_light_entities": "Luci colorate predefinite",
  "ui.ambient_light_player_map": "Mappatura Riproduttore -> luce",
  "ui.ambient_light_player_map_helper": "Usa i selettori di riproduttori e luci colorate riportati di seguito. Ogni riga completata diventa un'associazione; cancella un riproduttore o le sue luci per rimuovere l'associazione.",
  "ui.ambient_light_transition": "Transizione della luce",
  "ui.analog": "Analogico",
  "ui.choose_only_the_lights_that_should_follow_the_music": "Scegli solo le luci in grado di gestire il colore che devono seguire la musica quando non esiste un'associazione specifica per il riproduttore.",
  "ui.digital": "Digitale",
  "ui.discover_albums": "Scopri album",
  "ui.discover_music": "Scopri",
  "ui.discover_subtitle": "Playlist, album e radio consigliati.",
  "ui.discovery": "Scoperta",
  "ui.discovery_failed": "Modalità scoperta fallita",
  "ui.discovery_mode": "Modalità scoperta",
  "ui.discovery_started": "Scoperta avviata: {mood}",
  "ui.maximum_brightness_for_music_lighting": "Luminosità massima per l'illuminazione musicale.",
  "ui.minimum_seconds_between_light_updates": "Secondi minimi tra gli aggiornamenti della luce.",
  "ui.player_light_pair_lights": "Luci colorate {number}",
  "ui.player_light_pair_lights_helper": "Scegli le luci colorate per questo riproduttore di Music Assistant. Cancella questo campo o il riproduttore per rimuovere l'associazione.",
  "ui.player_light_pair_player": "Riproduttore Music Assistant {number}",
  "ui.player_light_pair_player_helper": "Scegli il riproduttore di Music Assistant per questa associazione di luci.",
  "ui.all": "Tutti",
  "ui.all_genres": "Tutti i generi",
  "ui.genres_and_styles": "Generi e stili",
  "ui.compact_widget_mode": "Stile widget compatto",
  "ui.choose_when_compact_mode_uses_the_two_row_mobile_widget": "Scegli quando la modalità compatta deve utilizzare il widget mobile più piccolo a due righe.",
  "ui.full": "Completo",
  "ui.mini_widget": "Mini widget",
  "ui.genre": "Genere",
  "ui.mood_and_genre": "Stato d'animo e genere",
  "ui.music_by_mood_and_genre": "Musica per stato d'animo e genere",
  "ui.optional_entity_for_the_power_button_leave_empty_to_stop_the_active_player": "Entità opzionale per il pulsante ausiliario. Lascia vuoto per arrestare il riproduttore attivo.",
  "ui.optional_name_for_the_auxiliary_button": "Nome opzionale mostrato come suggerimento per il pulsante ausiliario.",
  "ui.choose_the_auxiliary_button_icon": "Scegli l'icona mostrata per il pulsante ausiliario.",
  "ui.choose_how_players_are_sorted": "Scegli l'ordine dei riproduttori tra predefinito, alfabetico o personalizzato.",
  "ui.choose_music_assistant_players_to_hide_from_the_card": "Scegli i riproduttori di Music Assistant da non mostrare mai nella scheda.",
  "ui.custom_order": "Ordine personalizzato",
  "ui.no_visible_music_assistant_players_after_exclusions": "Tutti i riproduttori di Music Assistant sono nascosti dall'impostazione dei riproduttori esclusi.",
  "ui.set_custom_player_order": "Imposta l'ordine personalizzato dei riproduttori. Gli slot vuoti verranno ignorati.",
  "ui.show_auxiliary_button_in_quick_actions": "Mostra questo pulsante ausiliario nella riga delle Azioni Rapide.",
  "ui.power": "Alimentazione",
  "ui.power_action_failed": "Azione di accensione/spegnimento fallita",
  "ui.power_action_sent": "Azione di accensione/spegnimento inviata",
  "ui.power_button": "Pulsante ausiliario",
  "ui.power_button_action": "Azione pulsante ausiliario",
  "ui.power_button_entity": "Entità pulsante ausiliario",
  "ui.scene": "Scena",
  "ui.screensaver": "Salvaschermo",
  "ui.screensaver_buttons": "Pulsanti salvaschermo",
  "ui.screensaver_controls": "Controlli salvaschermo",
  "ui.screensaver_clock_mode": "Modalità orologio salvaschermo",
  "ui.screensaver_clock_size": "Dimensione orologio salvaschermo",
  "ui.screensaver_clock_size_helper": "Scala l'orologio del salvaschermo del tablet senza spostare la copertina.",
  "ui.screensaver_clock_x": "Posizione orologio - SINISTRA / DESTRA",
  "ui.screensaver_clock_x_helper": "Valori più bassi spostano a sinistra, valori più alti spostano a destra.",
  "ui.screensaver_clock_y": "Posizione orologio - SU / GIÙ",
  "ui.screensaver_clock_y_helper": "Valori più bassi spostano verso l'alto, valori più alti spostano verso il basso.",
  "ui.screensaver_message": "Messaggio salvaschermo",
  "ui.screensaver_timeout": "Timeout salvaschermo",
  "ui.script": "Script",
  "ui.short_optional_message_shown_on_the_screensaver": "Breve messaggio opzionale mostrato sul salvaschermo.",
  "ui.show_previous_next_controls_on_the_screensaver": "Mostra i pulsanti precedente e successivo sul salvaschermo.",
  "ui.choose_which_buttons_appear_on_the_screensaver": "Scegli esattamente quali pulsanti mostrare sul salvaschermo, inclusi FLOW ASSISTANT, precedente e successivo.",
  "ui.show_a_calm_clock_artwork_display_after_idle_time": "Mostra un orologio discreto e la copertina dopo un periodo di inattività.",
  "ui.show_power_button_in_the_player_controls": "Mostra un pulsante ausiliario nelle Azioni Rapide.",
  "ui.show_the_fullscreen_discovery_mode_in_actions": "Mostra la modalità scoperta a schermo intero nelle Azioni.",
  "ui.smart_home": "Smart home",
  "ui.soft_transition_time_for_music_lighting": "Tempo di transizione morbida per l'illuminazione musicale.",
  "ui.stop_player": "Ferma riproduttore",
  "ui.sync_selected_lights_to_the_current_artwork_color": "Sincronizza le luci selezionate con il colore della copertina corrente.",
  "ui.toggle": "Inverti",
  "ui.turn_on": "Accendi",
  "ui.choose_a_category_to_browse_provider_playlists": "Scegli una categoria per sfogliare le playlist del fornitore prima di riprodurle.",
  "ui.new_and_recommended": "Novità e consigliati",
  "ui.provider_playlists": "Playlist del fornitore",
  "ui.hotel_mode": "Modalità hotel",
  "ui.hotel_mode_helper": "Interfaccia minima sicura per hotel: solo controlli del riproduttore, volume, ricerca, navigazione copertine e selezione del riproduttore.",
  "ui.style_and_genres": "Stili e generi",
});

export default messages;
