// Generated HOMEii Music Flow localization dictionary.
// Keep keys stable. Translate only the string values.
const messages = Object.freeze({
  "ui.action_menu_labels": "Veiksmų pavadinimai po piktogramomis",
  "ui.a_guided_music_wizard": "Valdomas muzikos vedlys",
  "ui.a_radio_station": "Radijo stotis",
  "ui.accent_color": "Akcento spalva",
  "ui.actions": "veiksmai",
  "ui.actions_2": "Veiksmai",
  "ui.active_days": "Aktyvios dienos",
  "ui.active_player_helper": "Aktyvaus grotuvo pagalbininkas",
  "ui.active_player_helper_must_be_an_input_text_entity": "Aktyvaus grotuvo pagalbininkas turi būti „input_text“ objektas",
  "ui.active_players": "Aktyvūs grotuvai",
  "ui.add": "Pridėti",
  "ui.add_to_queue": "Pridėti į eilę",
  "ui.add_to_selection": "Pridėti prie pasirinkimo",
  "ui.added_to_liked": "Pridėta prie patinkančių",
  "ui.added_to_music_assistant_liked": "Pridėta prie „Music Assistant“ patinkančių",
  "ui.added_to_queue": "Pridėta į eilę",
  "ui.added_to_studio_queue": "Pridėta į „Studio“ eilę",
  "ui.adds_motion_to_the_background_layers_subtle_keeps_it_calm_strong_is_noti": "Prideda judesio fono sluoksniams. „Subtilus“ išlaiko ramybę, „Stiprus“ yra pastebimas, o „Ekstremalus“ – pati drąsiausia animacija.",
  "ui.adds_to_the_current_volume_only_during_announcements_then_restores_the_p": "Garsumas padidinamas tik pranešimų metu, vėliau grąžinamas ankstesnis garso lygis.",
  "ui.after_run": "Po paleidimo",
  "ui.album": "Albumas",
  "ui.albums": "Albumai",
  "ui.all_albums": "Visi albumai",
  "ui.all_artists": "Visi atlikėjai",
  "ui.all_countries": "Visos šalys",
  "ui.all_player_groups_disconnected": "Visos grotuvų grupės atjungtos",
  "ui.all_players": "Visi grotuvai",
  "ui.all_players_2": "visi grotuvai",
  "ui.all_podcasts": "Visos tinklalaidės",
  "ui.all_tracks": "Visi kūriniai",
  "ui.always_visible": "Visada matoma",
  "ui.announce": "Pranešti",
  "ui.announce_to_all_players": "Pranešti per visus grotuvus",
  "ui.announcement": "Pranešimas",
  "ui.announcement_failed_with_error": "Pranešimo klaida: {error}",
  "ui.announcement_language": "Pranešimo kalba",
  "ui.announcement_presets": "Pranešimų šablonai",
  "ui.announcement_sent_to_player": "Pranešimas išsiųstas į {player}",
  "ui.announcement_studio": "pranešimų studija",
  "ui.announcement_studio_2": "Pranešimų studija",
  "ui.announcement_target": "Pranešimo tikslas",
  "ui.announcement_to_player_preview": "Pranešimas į {player}: {preview}",
  "ui.announcement_volume_boost": "Pranešimo garso padidinimas",
  "ui.announcements": "Pranešimai",
  "ui.appearance": "Išvaizda",
  "ui.apply_group": "Pritaikyti grupę",
  "ui.apply_schedule": "Pritaikyti tvarkaraštį",
  "ui.artist": "Atlikėjas",
  "ui.artist_radio": "Atlikėjo radijas",
  "ui.artists": "Atlikėjai",
  "ui.artwork": "Viršelis",
  "ui.artwork_swipe": "Braukimas per viršelį",
  "ui.ascending": "Didėjančiai",
  "ui.at_least_one_player_must_stay_selected": "Bent vienas grotuvas turi likti pasirinktas",
  "ui.australia": "Australija",
  "ui.auto_chooses_mobile_or_tablet_based_on_actual_width": "Automatiškai parenka telefono arba planšetės režimą pagal plotį.",
  "ui.auto_cloud_default": "Auto / Debesies numatytasis",
  "ui.auto_extracts_colors_from_the_current_artwork_and_keeps_the_effect_subtl": "Automatiškai ištraukia spalvas iš viršelio ir išlaiko subtilų efektą. „Stiprus“ padaro spalvas sodresnes.",
  "ui.auto_leaves_home_assistant_cloud_voice_defaults_untouched_manual_choices": "„Auto“ nekeičia Home Assistant Cloud balso nustatymų. Rankiniai pasirinkimai nurodo konkrečią kalbą.",
  "ui.available": "Pasiekiama",
  "ui.back": "Atgal",
  "ui.back_2": "Atgal",
  "ui.back_to_countries": "Atgal į šalis",
  "ui.back_to_queue": "Atgal į eilę",
  "ui.background_motion": "Fono judėjimas",
  "ui.behavior": "Elgsena",
  "ui.browse_covers": "Naršyti viršelius",
  "ui.browse_playlists_artists_albums_and_radio": "Naršyti grojaraščius, atlikėjus, albumus ir radiją",
  "ui.browser_players": "Naršyklės grotuvai",
  "ui.build_custom_mix": "Kurti asmeninį miksą",
  "ui.building_studio_mix": "Kuriamas „Studio“ miksas...",
  "ui.button": "Mygtukas",
  "ui.by_mood": "Pagal nuotaiką",
  "ui.cache_duration_in_milliseconds_for_selected_data_requests": "Talpyklos trukmė (ms) pasirinktoms duomenų užklausoms.",
  "ui.cache_ttl": "Talpyklos trukmė (TTL)",
  "ui.calm": "Ramu",
  "ui.canada": "Kanada",
  "ui.cancel": "Atšaukti",
  "ui.cancel_2": "Atšaukti",
  "ui.cancel_selection": "Atšaukti pasirinkimą",
  "ui.card_configuration": "Kortelės konfigūracija",
  "ui.card_height": "Kortelės aukštis",
  "ui.card_height_in_pixels": "Kortelės aukštis pikseliais.",
  "ui.card_settings_are_managed_from_the_visual_editor": "Kortelės nustatymai valdomi per vizualų redaktorių",
  "ui.change_song": "Pakeisti dainą",
  "ui.change_track": "Pakeisti kūrinį",
  "ui.chill_mix": "Atpalaiduojantis miksas",
  "ui.choose_a_country_or_all_countries_to_browse_every_country_inside_the_rad": "Pasirinkite šalį arba „Visos šalys“, norėdami naršyti viską radijo skiltyje.",
  "ui.choose_a_queue_position": "Pasirinkite eilės poziciją",
  "ui.choose_a_source_player": "Pasirinkite šaltinio grotuvą",
  "ui.choose_a_target_player": "Pasirinkite tikslo grotuvą",
  "ui.choose_at_least_one_player": "Pasirinkite bent vieną grotuvą",
  "ui.choose_icons_text_or_both_for_the_footer": "Pasirinkite piktogramas, tekstą arba abu apatinėje juostoje.",
  "ui.choose_music_assistant_players_only_the_in_card_pinning_list_shows_only": "Pasirinkite tik Music Assistant grotuvus. Sąrašas rodo tik juos, kad išvengtumėte painiavos.",
  "ui.choose_one_clear_option": "Pasirinkite vieną išvalymo parinktį",
  "ui.choose_player": "Pasirinkti grotuvą",
  "ui.choose_something_from_the_quick_shelf_or_tap_the_wand_for_a_random_playl": "Pasirinkite kažką iš greitojo sąrašo arba burtų lazdelę atsitiktiniam grojaraščiui.",
  "ui.choose_source": "Pasirinkite šaltinį",
  "ui.choose_target": "Pasirinkite tikslą",
  "ui.choose_target_player": "Pasirinkite tikslo grotuvą",
  "ui.choose_the_accent_color_for_the_mobile_layout": "Pasirinkite akcento spalvą mobiliajam vaizdui.",
  "ui.choose_the_music": "Pasirinkite muziką",
  "ui.choose_the_small_buttons_shown_under_the_song_title_timer_appears_first": "Pasirinkite mažus mygtukus, rodomus po dainos pavadinimu.",
  "ui.choose_the_source_first_playback_will_use_the_current_target": "Pirmiausia pasirinkite šaltinį. Grojimas naudos dabartinį tikslą.",
  "ui.choose_where_to_play": "Pasirinkite, kur groti",
  "ui.choose_whether_artwork_swipe_changes_track_or_browses_covers": "Pasirinkite, ar braukimas per viršelį perjungia dainą, ar naršo viršelius.",
  "ui.choose_whether_settings_are_controlled_from_the_in_card_ui_or_from_the_c": "Pasirinkite, ar nustatymai valdomi kortelės lange, ar per skydelio konfigūraciją.",
  "ui.choose_which_actions_appear_in_the_main_bar": "Pasirinkite pagrindinės juostos veiksmus.",
  "ui.choose_which_days_the_auto_night_mode_window_applies_to": "Pasirinkite, kuriomis dienomis veikia automatinis nakties režimas.",
  "ui.choose_which_icons_appear_in_the_quick_action_row": "Pasirinkite greitųjų veiksmų piktogramas. „Išvalyti viską“ paprašys patvirtinimo.",
  "ui.choose_which_players_appear_as_tiles_in_the_room": "Pasirinkite, kurie grotuvai rodomi kaip plytelės.",
  "ui.choose_which_players_stay_in_the_current_control_selection": "Pasirinkite, kurie grotuvai lieka aktyviame valdyme.",
  "ui.choose_which_tabs_are_available_in_the_library_screen": "Pasirinkite matomus skirtukus bibliotekos lange.",
  "ui.choose_who_is_controlled": "Pasirinkite valdomą įrenginį",
  "ui.choosing_visual_disables_the_in_card_settings_screen": "Vizualus režimas išjungia kortelės vidinių nustatymų langą.",
  "ui.clean_all": "Išvalyti viską",
  "ui.clean_all_confirm_action": "Išvalyti viską",
  "ui.clean_all_confirm_copy": "Tai atjungs visus aktyvius grotuvus, sustabdys muziką ir išvalys eiles. Tęsti?",
  "ui.clean_all_confirm_title": "Išvalyti visus grotuvus?",
  "ui.clean_the_studio_wall": "Išvalyti „Studio“ sieną",
  "ui.clear": "Išvalyti",
  "ui.clear_queue": "Išvalyti eilę",
  "ui.clear_search": "Išvalyti paiešką",
  "ui.clone_queue": "Klonuoti eilę",
  "ui.close": "Uždaryti",
  "ui.collapse_compact_player": "Suskleisti kompaktinį grotuvą",
  "ui.compact_mode": "Kompaktiškas režimas",
  "ui.configure_ready_made_announcement_phrases": "Konfigūruoti iš anksto paruoštas pranešimų frazes.",
  "ui.connect_this_device": "Prijungti šį įrenginį",
  "ui.connect_this_device_2": "Prijungti šį įrenginį",
  "ui.connected": "Prijungtas",
  "ui.connected_2": "Prijungtas",
  "ui.connected_players": "prijungti grotuvai",
  "ui.connected_players_2": "Prijungti grotuvai",
  "ui.connecting": "Jungiamasi",
  "ui.connecting_2": "Jungiamasi...",
  "ui.confirm": "Patvirtinti",
  "ui.connection_and_behavior": "Ryšys ir elgsena",
  "ui.connects_directly_from_this_card_using_sendspin": "Jungiasi tiesiogiai iš šios kortelės (Sendspin)",
  "ui.continue": "Tęsti",
  "ui.continue_2": "Tęsti",
  "ui.continue_from_recent_music_assistant_activity": "Tęsti neseną „Music Assistant“ veiklą.",
  "ui.continue_listening": "Tęsti klausymą",
  "ui.continue_what_was_played_recently": "Tęsti tai, kas neseniai grojo",
  "ui.control_whether_the_card_background_moves_gently_and_how_strong_the_moti": "Valdykite, ar kortelės fonas juda ir kaip stipriai.",
  "ui.controlling": "Valdoma",
  "ui.could_not_build_quick_mix_from_the_current_song": "Nepavyko sukurti greito mikso iš šios dainos",
  "ui.could_not_build_studio_mix": "Nepavyko sukurti „Studio“ mikso",
  "ui.could_not_choose_media": "Nepavyko pasirinkti medijos",
  "ui.could_not_clone_the_queue": "Nepavyko klonuoti eilės",
  "ui.could_not_find_music": "Muzika nerasta",
  "ui.could_not_play_label": "Nepavyko paleisti: {label}",
  "ui.could_not_start_chill_mix": "Nepavyko pradėti atpalaiduojančio mikso",
  "ui.could_not_start_playback": "Nepavyko pradėti grojimo",
  "ui.could_not_start_playback_2": "Nepavyko pradėti grojimo",
  "ui.could_not_start_playback_in_studio": "Nepavyko pradėti grojimo „Studio“ lange",
  "ui.could_not_start_quick_mix": "Nepavyko pradėti greito mikso",
  "ui.could_not_start_radio_playback": "Nepavyko pradėti radijo",
  "ui.could_not_transfer_the_queue": "Nepavyko perkelti eilės",
  "ui.could_not_update_active_player_helper": "Nepavyko atnaujinti aktyvaus grotuvo pagalbininko",
  "ui.create_schedule": "Sukurti tvarkaraštį",
  "ui.current_path": "Dabartinis kelias",
  "ui.custom": "Pasirinktinis",
  "ui.dark": "Tamsus",
  "ui.delete_scene": "Ištrinti sceną",
  "ui.delete_schedule": "Ištrinti tvarkaraštį",
  "ui.descending": "Mažėjančiai",
  "ui.dictate": "Diktuoti",
  "ui.disabled": "Išjungta",
  "ui.disables_blur_animations_dynamic_backgrounds_and_heavy_shadows_recommend": "Išjungia suliejimą, animacijas ir šešėlius. Rekomenduojama silpnesniems įrenginiams.",
  "ui.disconnect": "Atjungti",
  "ui.disconnect_all": "Atjungti viską",
  "ui.disconnect_groups": "Atjungti grupes",
  "ui.disconnect_player_groups": "Atjungti grotuvų grupes",
  "ui.disconnect_this_device": "Atjungti šį įrenginį",
  "ui.disconnected": "Atjungta",
  "ui.disconnecting": "Atjungiama",
  "ui.disconnecting_player_groups": "Atjungiamos grotuvų grupės...",
  "ui.discover": "Atrasti",
  "ui.down": "Žemyn",
  "ui.dynamic_theme": "Dinaminė tema",
  "ui.edit_schedule": "Redaguoti tvarkaraštį",
  "ui.enable": "Įjungti",
  "ui.enable_or_disable_the_footer_search_button": "Įjungti/išjungti paieškos mygtuką apačioje.",
  "ui.enable_or_disable_the_studio_button_in_the_footer_bar": "Įjungti/išjungti „Studio“ mygtuką apačioje.",
  "ui.enable_the_floating_home_shortcut_button": "Įjungti plaukiojantį pradžios mygtuką.",
  "ui.enabled": "Įjungta",
  "ui.enables_switching_to_local_liked_mode": "Leidžia perjungti į vietinį patikdymų režimą.",
  "ui.end_time": "Pabaigos laikas",
  "ui.energetic": "Energingas",
  "ui.energy_and_rhythm": "Energija ir ritmas",
  "ui.enter_an_announcement_first": "Pirmiausia įveskite pranešimą",
  "ui.example_quiet_jazz_greek_music_workout": "Pavyzdžiui: ramus džiazas, graikiška muzika, treniruotė",
  "ui.existing_content": "Esamas turinys",
  "ui.expand_player": "Išplėsti grotuvą",
  "ui.extract_colors_from_the_current_artwork_and_apply_them_to_the_interface": "Ištraukti spalvas iš viršelio ir pritaikyti jas sąsajai.",
  "ui.extreme": "Ekstremalus",
  "ui.fallback_for_setups_that_need_an_alternate_queue_service_path": "Atsarginis variantas sistemoms su alternatyviu eilės keliu.",
  "ui.fallback_mode": "Atsarginis režimas",
  "ui.family_friendly": "Visai šeimai",
  "ui.favorite": "Mėgstamiausias",
  "ui.favorite_action_failed": "Mėgstamiausio veiksmas nepavyko",
  "ui.favorite_action_sent": "Mėgstamiausio veiksmas išsiųstas",
  "ui.favorite_center": "mėgstamiausių centras",
  "ui.favorite_center_2": "Mėgstamiausių centras",
  "ui.favorite_radio": "Mėgstamiausių radijas",
  "ui.favorite_updated": "Mėgstamiausi atnaujinti",
  "ui.favorites_and_liked_music": "Mėgstamiausia ir patinkanti muzika",
  "ui.feature_detection_player_context_and_this_device_playback_tools": "Funkcijų aptikimas, grotuvo kontekstas ir šio įrenginio atkūrimo įrankiai.",
  "ui.find_music": "Rasti muziką",
  "ui.finding_music": "Ieškoma muzikos",
  "ui.fixed": "Fiksuotas",
  "ui.flow_mix": "FLOW miksas",
  "ui.font_scale": "Šrifto mastelis",
  "ui.font_size": "Šrifto dydis",
  "ui.footer_search": "Paieška apačioje",
  "ui.footer_style": "Apatinės juostos stilius",
  "ui.footer_style_2": "Apatinės juostos stilius",
  "ui.for_example_lovelace_home_or_any_other_home_assistant_path": "Pavyzdžiui: /lovelace/home ar kitas Home Assistant kelias.",
  "ui.for_weaker_displays_turns_off_heavy_blur_animations_dynamic_theme_extrac": "Silpnesniems ekranams: išjungia foninius efektus ir animacijas.",
  "ui.france": "Prancūzija",
  "ui.free_style": "Laisvas stilius",
  "ui.free_style_quiet_jazz_greek_music_workout": "Laisvai: ramus džiazas, graikiška muzika...",
  "ui.fresh_start": "Nauja pradžia",
  "ui.fresh_start_2": "Nauja pradžia",
  "ui.fri": "Pen",
  "ui.friendly_and_simple": "Draugiškas ir paprastas",
  "ui.from": "Iš",
  "ui.general": "Bendra",
  "ui.general_and_display": "Bendra ir ekranas",
  "ui.germany": "Vokietija",
  "ui.global_scale_for_every_interface_font_1_is_the_default_size": "Bendras šrifto mastelis. 1 yra numatytasis dydis.",
  "ui.greece": "Graikija",
  "ui.grid": "Tinklelis",
  "ui.group": "Grupė",
  "ui.group_cleared": "Grupė išvalyta",
  "ui.group_cleared_2": "Grupė išvalyta",
  "ui.group_speakers": "Grupuoti garsiakalbius",
  "ui.group_speakers_2": "Grupuoti garsiakalbius",
  "ui.group_updated": "Grupė atnaujinta",
  "ui.group_volume": "Grupės garsumas",
  "ui.group_volume_up_energetic_mix": "Grupė, garsiau, energingas miksas",
  "ui.grouped_players": "Sugrupuoti grotuvai",
  "ui.hebrew": "Hebrajų",
  "ui.history": "Istorija",
  "ui.history_tabs": "Istorijos skirtukai",
  "ui.home": "Pradžia",
  "ui.home_party_night_presets": "Pradžia, vakarėlis, nakties šablonai",
  "ui.home_path": "Pradžios kelias",
  "ui.home_scene_prepared": "Namų scena paruošta",
  "ui.home_shortcut": "Pradžios nuoroda",
  "ui.home_shortcut_path": "Pradžios nuorodos kelias",
  "ui.icon_and_text": "Piktograma ir tekstas",
  "ui.icon_only": "Tik piktograma",
  "ui.icon_plus_text": "Piktograma + tekstas",
  "ui.idle": "Neveiklus",
  "ui.idle_2": "Neveiklus",
  "ui.in_card_ui": "Kortelės sąsaja",
  "ui.includes_the_custom_theme_mode_from_the_in_card_settings_screen": "Apima pasirinktinį temos režimą iš kortelės nustatymų.",
  "ui.info": "Informacija",
  "ui.israel": "Izraelis",
  "ui.israeli": "Izraelietiška",
  "ui.italy": "Italija",
  "ui.items": "elementai",
  "ui.join_selected_players": "Sujungti pasirinktus grotuvus",
  "ui.kids": "Vaikams",
  "ui.language": "Kalba",
  "ui.larger_lyrics": "Didesni žodžiai",
  "ui.layout_adapted_to_height": "Išdėstymas pritaikytas aukščiui",
  "ui.layout_mode": "Išdėstymo režimas",
  "ui.leave_empty_if_the_card_should_use_home_assistant_only": "Palikite tuščią, jei kortelė naudos tik Home Assistant.",
  "ui.library": "Biblioteka",
  "ui.library_2": "Biblioteka",
  "ui.library_pages": "Bibliotekos puslapiai",
  "ui.default_library_layout": "Numatytasis bibliotekos išdėstymas",
  "ui.choose_how_library_pages_open_grid_or_list_can_still_be_changed_manually": "Pasirinkite, kaip atidaromi bibliotekos puslapiai. Bibliotekoje vis tiek galite rankiniu būdu perjungti tinklelį / sąrašą.",
  "ui.library_radio": "Bibliotekos radijas",
  "ui.library_surprise": "Bibliotekos staigmena",
  "ui.library_tabs": "Bibliotekos skirtukai",
  "ui.library_tabs_2": "Bibliotekos skirtukai",
  "ui.light": "Šviesus",
  "ui.like": "Patinka",
  "ui.like_2": "Patinka",
  "ui.like_3": "Patinka",
  "ui.liked": "Pamėgti",
  "ui.liked_mode": "Pamėgtų režimas",
  "ui.liked_sync": "Pamėgtų sinchronizacija",
  "ui.list": "Sąrašas",
  "ui.listening": "Klausomasi...",
  "ui.loading": "Kraunama...",
  "ui.loading_favorites": "Kraunami mėgstamiausi...",
  "ui.loading_library": "Kraunama biblioteka...",
  "ui.loading_lyrics": "Kraunami žodžiai...",
  "ui.loading_players": "Kraunami grotuvai...",
  "ui.loading_queue": "Kraunama eilė...",
  "ui.loading_recent_items": "Kraunami naujausi...",
  "ui.loading_schedules": "Kraunami tvarkaraščiai...",
  "ui.local": "Vietinis",
  "ui.local_favorites": "Vietiniai mėgstamiausi",
  "ui.local_favorites_2": "Vietiniai mėgstamiausi",
  "ui.local_mode_is_only_meaningful_when_local_likes_are_enabled": "Vietinis režimas prasmingas tik įjungus vietinius pamėgtus.",
  "ui.low_light_listening": "Klausymasis prietemoje",
  "ui.low_volume_and_quiet_mix": "Tylus garsas ir ramus miksas",
  "ui.lower_volume_mood": "Tylesnio garso nuotaika",
  "ui.lyrics": "Dainų žodžiai",
  "ui.lyrics_earlier": "Žodžiai anksčiau",
  "ui.lyrics_font_size": "Žodžių šrifto dydis",
  "ui.lyrics_later": "Žodžiai vėliau",
  "ui.lyrics_timing": "Žodžių laikas",
  "ui.lyrics_unavailable_right_now": "Žodžiai šiuo metu nepasiekiami",
  "ui.ma_favorite_action_failed_with_error": "Music Assistant mėgstamiausių veiksmo klaida: {error}",
  "ui.ma_interface_path": "MA sąsajos kelias",
  "ui.main_bar": "Pagrindinė juosta",
  "ui.main_bar_items": "Pagrindinės juostos elementai",
  "ui.main_bar_items_2": "Pagrindinės juostos elementai",
  "ui.main_opacity": "Pagrindinis permatomumas",
  "ui.mainly_relevant_on_larger_layouts": "Aktualu didesniuose ekranuose.",
  "ui.matches_the_microphone_setting_from_the_in_card_settings_screen": "Atitinka mikrofono nustatymą iš kortelės nustatymų.",
  "ui.media": "Medija",
  "ui.media_2": "Medija",
  "ui.media_actions": "Medijos veiksmai",
  "ui.media_layout": "Medijos išdėstymas",
  "ui.media_selected_target": "Pasirinkta: {media} ? Tikslas: {target}",
  "ui.menu": "Meniu",
  "ui.message": "Pranešimas",
  "ui.microphone": "Mikrofonas",
  "ui.microphone_2": "Mikrofonas",
  "ui.microphone_is_disabled": "Mikrofonas išjungtas",
  "ui.missing_url": "Trūksta URL",
  "ui.mobile": "Mobilus",
  "ui.mon": "Pir",
  "ui.mood_style_or_free_text": "Nuotaika, stilius ar laisvas tekstas",
  "ui.more_info": "Daugiau informacijos",
  "ui.more_info_is_unavailable_for_this_player": "Šiam grotuvui papildomos informacijos nėra",
  "ui.morning": "Rytas",
  "ui.morning_mix": "Ryto miksas",
  "ui.move_to_next": "Perkelti į kitą",
  "ui.move_to_position": "Perkelti į poziciją",
  "ui.music": "Muzika",
  "ui.music_assistant_config_entry_id_if_you_want_direct_integration_lookup_th": "Music Assistant integracijos ID.",
  "ui.music_assistant_config_entry_was_not_found": "Music Assistant integracija nerasta",
  "ui.music_assistant_token": "Music Assistant raktas (Token)",
  "ui.music_assistant_url": "Music Assistant URL",
  "ui.music_hub": "muzikos centras",
  "ui.music_hub_2": "Muzikos centras",
  "ui.mute": "Nutildyti",
  "ui.mute_command_failed": "Nutildyti nepavyko",
  "ui.my_studio_scene": "Mano Studio scena",
  "ui.name_or_keyword": "Pavadinimas ar raktažodis",
  "ui.name_this_studio_scene": "Pavadinkite šią Studio sceną...",
  "ui.netherlands": "Nyderlandai",
  "ui.new_schedule": "Naujas tvarkaraštis",
  "ui.new_wake_schedule": "Naujas žadinimo tvarkaraštis",
  "ui.newest": "Naujausi",
  "ui.next": "Kitas",
  "ui.next_track_failed": "Nepavyko perjungti dainos",
  "ui.night": "Naktis",
  "ui.night_end_time": "Nakties pabaigos laikas",
  "ui.night_mode": "Nakties režimas",
  "ui.night_mode_auto_window": "Automatinė naktis {start}-{end}",
  "ui.night_mode_days": "Nakties režimo dienos",
  "ui.night_mode_is_always_on": "Nakties režimas visada įjungtas",
  "ui.night_mode_is_off": "Nakties režimas išjungtas",
  "ui.night_mode_is_off_until_you_choose_another_mode": "Nakties režimas išjungtas, kol nepasirinksite kito.",
  "ui.night_mode_stays_on_until_you_choose_another_mode": "Nakties režimas įjungtas, kol nepasirinksite kito.",
  "ui.night_schedule_updated": "Nakties tvarkaraštis atnaujintas",
  "ui.night_start_time": "Nakties pradžios laikas",
  "ui.no_active_media": "Nėra aktyvios medijos",
  "ui.no_active_players": "Nėra aktyvių grotuvų",
  "ui.no_available_players": "Nėra pasiekiamų grotuvų",
  "ui.no_content_found": "Turinys nerastas",
  "ui.no_dynamic_player_groups_to_disconnect": "Nėra dinaminių grupių, kurias būtų galima atjungti",
  "ui.no_extra_ma_players": "Nėra papildomų MA grotuvų",
  "ui.no_extra_ma_players_2": "Nėra papildomų MA grotuvų",
  "ui.no_favorites_found": "Mėgstamiausių nerasta.",
  "ui.no_liked_media_yet": "Dar nėra patinkančios medijos",
  "ui.no_liked_tracks_to_play": "Nėra patinkančių kūrinių grojimui",
  "ui.no_light_entities_found": "Šviesos objektų nerasta.",
  "ui.no_lyrics_found": "Žodžių nerasta",
  "ui.no_matching_content_was_found": "Atitinkančio turinio nerasta",
  "ui.no_media_found": "Medijos nerasta.",
  "ui.no_media_found_for_this_search": "Pagal šią paiešką medijos nerasta.",
  "ui.no_mix_content_found": "Mikso turinio nerasta",
  "ui.no_music_assistant_players_were_found_check_music_assistant_and_media_pl": "Music Assistant grotuvų nerasta. Patikrinkite media_player objektus.",
  "ui.no_music_assistant_players_were_found_for_pinning": "MA grotuvų nerasta prisegimui.",
  "ui.no_next_track_in_queue": "Eilėje nėra kito kūrinio",
  "ui.no_player_groups_to_disconnect": "Nėra grotuvų grupių atjungimui",
  "ui.no_player_light_pairs_yet": "Dar nėra grotuvo-šviesos porų.",
  "ui.no_player_selected": "Grotuvas nepasirinktas",
  "ui.no_players_found": "Grotuvų nerasta",
  "ui.no_players_found_yet": "Grotuvų dar nerasta",
  "ui.no_playlists_found": "Grojaraščių nerasta",
  "ui.no_queue": "Nėra eilės",
  "ui.no_queue_item_to_rebuild": "Nėra eilės elemento atstatymui",
  "ui.no_queue_to_clone": "Nėra eilės klonavimui",
  "ui.no_radio_browser_countries_found": "Radijo šalių nerasta",
  "ui.no_radio_stations_found": "Radijo stočių nerasta",
  "ui.no_recent_listening_yet": "Dar nėra neseniai klausytų.",
  "ui.no_results": "Nėra rezultatų",
  "ui.no_results_found": "Rezultatų nerasta",
  "ui.no_saved_studio_scenes_yet": "Dar nėra išsaugotų Studio scenų.",
  "ui.no_scheduled_start_is_active": "Nėra aktyvaus suplanuoto starto",
  "ui.no_selected_tracks_to_play": "Nepasirinkta kūrinių grojimui",
  "ui.no_sleep_timer_is_active": "Išsijungimo laikmatis neaktyvus",
  "ui.no_speech_was_captured": "Kalba neužfiksuota",
  "ui.no_target_players_available": "Nėra pasiekiamų tikslo grotuvų",
  "ui.no_target_players_available_2": "Nėra pasiekiamų tikslo grotuvų",
  "ui.no_tts_service_or_entity_is_configured": "TTS paslauga arba objektas nesukonfigūruotas",
  "ui.no_wake_schedules_yet": "Dar nėra žadinimo tvarkaraščių",
  "ui.none": "Nėra",
  "ui.nothing_is_playing_right_now": "Šiuo metu nieko negroja",
  "ui.nothing_playing": "Nieko negroja",
  "ui.now_playing": "Dabar groja",
  "ui.now_playing_2": "Dabar groja",
  "ui.off": "Išjungta",
  "ui.off_2": "Išjungta",
  "ui.off_disables_it_on_keeps_it_active_and_auto_follows_the_configured_time": "„Išjungta“ atjungia, „Įjungta“ palieka aktyvų, „Auto“ seka pagal nustatytą laiką.",
  "ui.oldest": "Seniausi",
  "ui.on": "Įjungta",
  "ui.one_tap_prepares_players_grouping_volume_and_content_save_your_own_curre": "Vienu paspaudimu paruoškite grotuvus ir garsą. Išsaugokite kaip vietinę sceną.",
  "ui.only_actions_for_the_current_target_are_shown_here": "Čia rodomi tik dabartinio tikslo veiksmai.",
  "ui.only_music_assistant_players_are_shown_here_browser_and_local_sendspin_p": "Rodomi tik MA grotuvai. Naršyklės ir vietiniai grotuvai slepiami.",
  "ui.only_needed_when_using_a_direct_music_assistant_url": "Reikalinga tik naudojant tiesioginį Music Assistant URL.",
  "ui.opacity_for_popups_and_overlays": "Iššokančių langų permatomumas.",
  "ui.opacity_for_the_main_card_background": "Pagrindinio kortelės fono permatomumas.",
  "ui.open_full_interface": "Atidaryti pilną sąsają",
  "ui.open_full_queue": "Atidaryti pilną eilę",
  "ui.open_interface_in": "Atidaryti sąsają",
  "ui.open_ma": "Atidaryti MA",
  "ui.open_music_assistant": "Atidaryti Music Assistant",
  "ui.open_music_assistant_2": "Atidaryti Music Assistant?",
  "ui.open_music_assistant_on_this_device_to_activate_the_browser_player": "Atidarykite MA šiame įrenginyje, kad aktyvuotumėte naršyklės grotuvą",
  "ui.open_player_picker": "Atidaryti grotuvo parinkiklį",
  "ui.open_queue": "Atidaryti eilę",
  "ui.open_saved_songs": "Atidaryti išsaugotas dainas",
  "ui.open_the_full_music_assistant_interface": "Atidaryti pilną Music Assistant sąsają?",
  "ui.open_the_full_music_assistant_interface_2": "Atidaryti pilną Music Assistant sąsają",
  "ui.opening_studio_library": "Atidaroma Studio biblioteka",
  "ui.opening_timers": "Atidaromi laikmačiai",
  "ui.option": "Parinktis",
  "ui.optional": "Neprivaloma",
  "ui.optional_2": "Neprivaloma",
  "ui.optional_entity_used_for_an_external_favorite_button": "Neprivalomas objektas išoriniam mėgstamiausių mygtukui.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for": "Neprivalomas pagalbininkas atnaujinamas pagal aktyvų grotuvą (automatizacijoms).",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for_2": "Neprivalomas pagalbininkas atnaujinamas pagal aktyvų grotuvą.",
  "ui.other": "Kiti",
  "ui.other_players": "Kiti grotuvai",
  "ui.party": "Vakarėlis",
  "ui.path_used_when_opening_the_music_assistant_interface": "Kelias naudojamas atidarant Music Assistant sąsają.",
  "ui.pause": "Pauzė",
  "ui.paused": "Pauzė",
  "ui.per_device_in_card": "Šiame įrenginyje / kortelėje",
  "ui.performance_mode": "Našumo režimas",
  "ui.performance_mode_for_weak_devices": "Našumo režimas silpniems įrenginiams",
  "ui.performance_profile": "Našumo profilis",
  "ui.performance_profile_helper": "Pasirinkite, kiek vizualinių efektų kortelė gali naudoti. Ultra Lite sumažina skaidrumą, suliejimą, dinaminius fonus ir judėjimą silpniems įrenginiams.",
  "ui.pick_a_mood_or_type_your_own_style_studio_will_search_music_assistant_an": "Pasirinkite nuotaiką arba įveskite savo. Studio suras ir sukurs eilę.",
  "ui.pinned": "Prisegtas",
  "ui.pinned_players": "Prisegti grotuvai",
  "ui.play": "Groti",
  "ui.play_2": "Groti",
  "ui.play_a_few_tracks_and_they_will_appear_here": "Paklausykite kelis kūrinius ir jie atsiras čia.",
  "ui.play_a_saved_list": "Paleisti išsaugotą sąrašą",
  "ui.play_all": "Groti viską",
  "ui.play_an_artist": "Paleisti atlikėją",
  "ui.play_artwork_action": "Viršelio paspaudimo veiksmas",
  "ui.play_everywhere": "Groti visur",
  "ui.play_next": "Groti kitą",
  "ui.play_next_and_clear_queue": "Groti kitą ir išvalyti eilę",
  "ui.play_now": "Groti dabar",
  "ui.play_now_and_clear_queue": "Groti dabar ir išvalyti eilę",
  "ui.play_pause": "Groti / Pauzė",
  "ui.play_queue_radio_or_remove_favorites_directly_from_studio": "Grokite, eilė, radijas arba šalinkite iš mėgstamiausių tiesiai per Studio.",
  "ui.play_selected": "Groti pasirinktus",
  "ui.playback_command_failed": "Grojimo komanda nepavyko",
  "ui.playback_command_failed_2": "Grojimo komanda nepavyko",
  "ui.playback_started": "Grojimas pradėtas",
  "ui.player": "grotuvas",
  "ui.player_2": "Grotuvas",
  "ui.player_count_many": "{count} grotuvai",
  "ui.player_count_one": "1 grotuvas",
  "ui.player_groups_could_not_be_disconnected": "Nepavyko atjungti grotuvų grupių",
  "ui.player_is_pinned_from_settings": "Grotuvas prisegtas iš nustatymų",
  "ui.player_is_ready": "Grotuvas paruoštas",
  "ui.player_is_ready_nothing_is_playing_right_now": "Grotuvas paruoštas - šiuo metu nieko negroja",
  "ui.player_on_this_device": "Grotuvas šiame įrenginyje",
  "ui.player_selected": "Grotuvas pasirinktas",
  "ui.player_settings_and_dsp_presets_stay_read_only_until_music_assistant_exp": "Grotuvo nustatymai rodomi tik skaitymui, kol bus palaikoma modifikacija.",
  "ui.players": "Grotuvai",
  "ui.players_queue_and_groups": "Grotuvai, eilė ir grupės",
  "ui.playing": "Groja",
  "ui.playing_a_random_playlist": "Grojamas atsitiktinis grojaraštis",
  "ui.playing_a_random_radio_station": "Grojama atsitiktinė radijo stotis",
  "ui.playing_on": "Groja per",
  "ui.playing_on_2": "Groja per",
  "ui.playlist": "Grojaraštis",
  "ui.playlists": "Grojaraščiai",
  "ui.podcast": "Tinklalaidė",
  "ui.podcasts": "Tinklalaidės",
  "ui.popup_opacity": "Iššokančio lango permatomumas",
  "ui.preset_message": "Šablono pranešimas",
  "ui.previous": "Ankstesnis",
  "ui.primary": "Pagrindinis",
  "ui.primary_target": "Pagrindinis tikslas",
  "ui.pro_tools": "Pro įrankiai",
  "ui.queue": "Eilė",
  "ui.queue_2": "Eilė",
  "ui.queue_action_failed": "Nepavyko atlikti veiksmo su eile",
  "ui.queue_action_is_not_available_for_this_player": "Eilės veiksmai šiam grotuvui negalimi",
  "ui.queue_actions": "Eilės veiksmai",
  "ui.queue_cleared": "Eilė išvalyta",
  "ui.queue_cleared_and_item_moved_next": "Eilė išvalyta ir elementas perkeltas į priekį",
  "ui.queue_cloned": "Eilė klonuota",
  "ui.queue_cockpit": "Eilės valdymas",
  "ui.queue_cockpit_2": "Eilės valdymas",
  "ui.queue_is_empty": "Eilė tuščia",
  "ui.queue_is_unavailable_for_this_player": "Eilė nepasiekiama šiam grotuvui",
  "ui.queue_item": "Eilės elementas",
  "ui.queue_item_id_is_not_ready_yet_refresh_the_queue_and_try_again": "Elemento ID dar neparuoštas. Atnaujinkite eilę ir bandykite dar kartą.",
  "ui.queue_results": "Eilės rezultatai",
  "ui.queue_transferred": "Eilė pervesta",
  "ui.queues_refreshed": "Eilės atnaujintos",
  "ui.quick_actions": "Greitieji veiksmai",
  "ui.quick_actions_2": "Greitieji veiksmai",
  "ui.quick_mix": "Greitas miksas",
  "ui.quick_mix_started": "Greitas miksas pradėtas",
  "ui.quick_play": "Greitas grojimas",
  "ui.radio": "Radijas",
  "ui.radio_browser": "Radijo naršyklė",
  "ui.radio_browser_countries": "Radijo šalys",
  "ui.radio_browser_country": "Radijo šalis",
  "ui.radio_browser_country_2": "Radijo šalis",
  "ui.radio_mode_is_not_available_for_this_media_type": "Radijo režimas nepasiekiamas šiam medijos tipui",
  "ui.radio_mode_started": "Radijo režimas pradėtas",
  "ui.radio_station_changed": "Radijo stotis pakeista",
  "ui.radio_stations": "Radijo stotys",
  "ui.random": "Atsitiktinis",
  "ui.random_gentle_morning_mix": "Atsitiktinis švelnus ryto miksas",
  "ui.random_playlist": "Atsitiktinis grojaraštis",
  "ui.random_radio": "Atsitiktinis radijas",
  "ui.ready": "Paruošta",
  "ui.ready_to_play": "Paruošta groti",
  "ui.recent": "Naujausi",
  "ui.recent_continue": "Naujausi / Tęsti",
  "ui.recent_listening": "neseniai klausyta",
  "ui.recent_track": "Naujausias kūrinys",
  "ui.recently_added": "Neseniai pridėta",
  "ui.recently_played": "Neseniai grota",
  "ui.recently_played_2": "Neseniai grota",
  "ui.recommendations_will_appear_once_homeii_flow_sees_your_queue_or_recent_l": "Rekomendacijos atsiras, kai HOMEii Flow matys jūsų eilę arba klausymo istoriją.",
  "ui.recommended": "Rekomenduojama",
  "ui.recommended_format_hh_mm_such_as_06_00_crossing_midnight_is_supported": "Rekomenduojamas formatas: HH:MM, pvz. 06:00. Vidurnakčio peržengimas palaikomas.",
  "ui.recommended_format_hh_mm_such_as_22_00": "Rekomenduojamas formatas: HH:MM, pvz. 22:00.",
  "ui.recommended_playlist": "Rekomenduojamas grojaraštis",
  "ui.recommended_track": "Rekomenduojamas kūrinys",
  "ui.reconnects_when_you_return_to_this_dashboard": "Prisijungia iš naujo, kai grįžtate į šį skydelį",
  "ui.refresh": "Atnaujinti",
  "ui.remember_as_this_device": "Prisiminti kaip šį įrenginį",
  "ui.remove": "Pašalinti",
  "ui.remove_from_selection": "Pašalinti iš pasirinkimo",
  "ui.removed_from_liked": "Pašalinta iš patinkančių",
  "ui.removed_from_music_assistant_liked": "Pašalinta iš Music Assistant patinkančių",
  "ui.reorder_queue": "Perrūšiuoti eilę",
  "ui.repeat": "Kartoti",
  "ui.repeat_all": "Kartoti viską",
  "ui.repeat_off": "Kartoti išjungta",
  "ui.repeat_one": "Kartoti vieną",
  "ui.reset": "Atstatyti",
  "ui.reset_lyrics_font_size": "Atstatyti žodžių šrifto dydį",
  "ui.reset_lyrics_timing": "Atstatyti žodžių laiką",
  "ui.results": "Rezultatai",
  "ui.rtl": "Iš dešinės į kairę (RTL)",
  "ui.sat": "Šeš",
  "ui.save_current_target": "Išsaugoti dabartinį tikslą",
  "ui.save_schedule": "Išsaugoti tvarkaraštį",
  "ui.scene_players_are_not_available": "Scenos grotuvai nepasiekiami",
  "ui.scene_presets": "scenų šablonai",
  "ui.scene_presets_2": "Scenų šablonai",
  "ui.scenes": "Scenos",
  "ui.scales_interface_icons_without_changing_button_sizes": "Keičia sąsajos piktogramų mastelį nekeičiant mygtukų dydžio.",
  "ui.scheduled_start": "Suplanuotas startas",
  "ui.scheduled_start_activated_label": "Suplanuotas startas aktyvuotas: {label}",
  "ui.scheduled_start_cleared": "Suplanuotas startas išvalytas",
  "ui.scheduled_start_failed": "Suplanuotas startas nepavyko",
  "ui.scheduled_start_saved": "Suplanuotas startas išsaugotas",
  "ui.scheduled_starts_active_count": "Aktyvūs suplanuoti startai: {count}",
  "ui.schedules": "Tvarkaraščiai",
  "ui.search": "Ieškoti",
  "ui.search_and_choose_play_next_add_radio_or_like": "Ieškokite ir pasirinkite: Groti, Kitas, Pridėti, Radijas arba Patinka.",
  "ui.search_everything": "Ieškoti visko...",
  "ui.search_failed": "Paieška nepavyko",
  "ui.search_in_queue": "Ieškoti eilėje",
  "ui.search_queue_and_library": "Ieškoti eilėje ir bibliotekoje...",
  "ui.search_the_library": "Ieškoti bibliotekoje...",
  "ui.search_tracks_albums_artists_and_playlists": "Ieškoti kūrinių, albumų, atlikėjų ir grojaraščių",
  "ui.searching": "Ieškoma...",
  "ui.searching_library": "Ieškoma bibliotekoje...",
  "ui.searching_smart_selection": "Ieškoma išmaniajame pasirinkime...",
  "ui.seek": "Slinkti",
  "ui.select": "Pasirinkti",
  "ui.select_lights": "Pasirinkti apšvietimą",
  "ui.select_player": "Pasirinkti grotuvą",
  "ui.select_2": "Pasirinkti",
  "ui.select_a_player_first": "Pirmiausia pasirinkite grotuvą",
  "ui.select_at_least_one_studio_player": "Pasirinkite bent vieną Studio grotuvą",
  "ui.select_at_least_two_players_to_create_a_group": "Pasirinkite bent du grotuvus grupei sukurti",
  "ui.selected": "Pasirinkta",
  "ui.selected_music": "Pasirinkta muzika",
  "ui.selected_player": "Pasirinktas grotuvas",
  "ui.selected_player_2": "Pasirinktas grotuvas",
  "ui.selected_player_3": "Pasirinktas grotuvas",
  "ui.selected_players_at_comfortable_volume": "Pasirinkti grotuvai patogiu garsumu",
  "ui.selected_playlist": "Pasirinktas grojaraštis",
  "ui.send_a_short_voice_message_or_announcement_url": "Siųsti trumpą balso pranešimą arba URL.",
  "ui.send_a_voice_message": "Siųsti balso pranešimą",
  "ui.send_announcement": "Siųsti pranešimą",
  "ui.sendspin_and_diagnostics": "Sendspin ir diagnostika",
  "ui.set_sleep_timer": "Nustatyti išsijungimo laikmatį",
  "ui.set_volume": "Nustatyti garsumą",
  "ui.settings": "Nustatymai",
  "ui.settings_section_announcements": "Skelbimai",
  "ui.settings_section_display": "Ekranas",
  "ui.settings_section_music_assistant": "Music Assistant",
  "ui.settings_section_players_library": "Grotuvai ir biblioteka",
  "ui.settings_section_quick_actions_bar": "Greitieji veiksmai ir juosta",
  "ui.settings_section_smart_home": "Smart Home & ekrano užsklanda",
  "ui.settings_section_voice_assistant": "Balso asistentas",
  "ui.settings_source": "Nustatymų šaltinis",
  "ui.show_ma_button": "Rodyti MA mygtuką",
  "ui.show_or_hide_the_inline_next_track_row_in_now_playing": "Rodyti/slėpti sekančio kūrinio eilutę grojimo lange.",
  "ui.show_theme_toggle": "Rodyti temos perjungiklį",
  "ui.show_up_next": "Rodyti „Kitas“",
  "ui.show_up_next_2": "Rodyti „Kitas“",
  "ui.shows_a_standalone_compact_player_tile_with_artwork_basic_controls_volum": "Rodo atskirą kompaktinio grotuvo plytelę su valdymu.",
  "ui.shuffle": "Maišyti",
  "ui.shuffle_all": "Maišyti viską",
  "ui.shuffle_favorites": "Maišyti mėgstamiausius",
  "ui.shuffle_play": "Maišyti ir groti",
  "ui.skipped_to_up_next": "Peršokta prie sekančio",
  "ui.sleep_timer": "Išsijungimo laikmatis",
  "ui.sleep_timer_2": "Išsijungimo laikmatis",
  "ui.sleep_timer_active_remaining": "Laikmatis aktyvus: {remaining}",
  "ui.sleep_timer_added_minutes": "Pridėta {minutes} min. prie laikmačio",
  "ui.sleep_timer_and_morning_playback": "Laikmatis ir rytinis grojimas",
  "ui.sleep_timer_and_scheduled_playback": "Laikmatis ir suplanuotas grojimas",
  "ui.sleep_timer_cleared": "Laikmatis išvalytas",
  "ui.sleep_timer_finished": "Laikmatis baigėsi",
  "ui.sleep_timer_presets": "Laikmačio šablonai",
  "ui.sleep_timer_set_for_15_minutes": "Laikmatis nustatytas 15 minučių",
  "ui.sleep_timer_set_minutes": "Laikmatis nustatytas {minutes} minutėms",
  "ui.sleep_timer_updated_minutes": "Laikmatis atnaujintas į {minutes} minučių",
  "ui.smaller_lyrics": "Mažesni žodžiai",
  "ui.smart": "Išmanusis",
  "ui.smart_mix": "išmanusis miksas",
  "ui.smart_mix_builder": "Išmaniojo mikso kūrėjas",
  "ui.smart_voice_selection": "Išmanusis balso pasirinkimas",
  "ui.soft_and_relaxed": "Švelnus ir atsipalaidavęs",
  "ui.soft_relaxed_music": "Švelni, atsipalaidavimo muzika",
  "ui.some_players_could_not_be_stopped_or_cleared": "Kai kurių grotuvų nepavyko sustabdyti ar išvalyti",
  "ui.songs_around_an_artist": "Dainos pagal atlikėją",
  "ui.sort": "Rūšiuoti",
  "ui.sort_ascending": "Rūšiuoti didėjančiai",
  "ui.sort_descending": "Rūšiuoti mažėjančiai",
  "ui.source_queue": "Šaltinio eilė",
  "ui.spain": "Ispanija",
  "ui.speak_to_target_players": "Kalbėti per tikslo grotuvus",
  "ui.start_radio_mode": "Pradėti radijo režimą",
  "ui.start_time": "Pradžios laikas",
  "ui.start_time_2": "Pradžios laikas",
  "ui.started_on_selected_player": "Pradėta pasirinktame grotuve",
  "ui.starting_a_chill_mix": "Pradedamas atpalaiduojantis miksas",
  "ui.starting_quick_mix": "Pradedamas greitas miksas...",
  "ui.stations": "stotys",
  "ui.stay_active": "Likti aktyviam",
  "ui.stays_active": "Lieka aktyvus",
  "ui.stop_all": "Sustabdyti viską",
  "ui.stop_all_players": "Sustabdyti visus grotuvus",
  "ui.stop_command_failed": "Sustabdymo komanda nepavyko",
  "ui.stop_playback_clear_queues_and_disconnect_groups": "Sustabdyti grojimą, išvalyti eiles ir atjungti grupes",
  "ui.stopped_all_players_cleared_playlists_and_disconnected_groups": "Sustabdyti visi grotuvai, išvalyti grojaraščiai ir atjungtos grupės",
  "ui.stops_this_browser_player": "Sustabdo šį naršyklės grotuvą",
  "ui.strong": "Stiprus",
  "ui.studio": "Studio",
  "ui.studio_closed": "Studio uždaryta",
  "ui.studio_media_action_failed": "Studio medijos veiksmas nepavyko",
  "ui.studio_mix_started": "Studio miksas pradėtas",
  "ui.studio_opened": "Studio atidaryta",
  "ui.studio_pro": "studio pro",
  "ui.studio_pro_2": "Studio Pro",
  "ui.studio_scene": "Studio scena",
  "ui.studio_scene_deleted": "Studio scena ištrinta",
  "ui.studio_scene_saved": "Studio scena išsaugota",
  "ui.studio_scene_was_not_found": "Studio scena nerasta",
  "ui.studio_search": "studio paieška",
  "ui.studio_shortcut": "Studio nuoroda",
  "ui.subtle": "Subtilus",
  "ui.sun": "Sek",
  "ui.surprise_me": "Nustebink mane",
  "ui.sync": "Sinchronizuoti",
  "ui.sync_lyrics": "Sinchronizuoti žodžius",
  "ui.tablet": "Planšetė",
  "ui.tap_to_start_a_sleep_timer": "Bakstelėkite laikmačiui pradėti",
  "ui.target_players": "Tikslo grotuvai",
  "ui.target_queue": "Tikslo eilė",
  "ui.text_announcements_use_home_assistant_tts_into_the_selected_music_assist": "Tekstiniai pranešimai naudoja Home Assistant TTS, nukreiptą į Music Assistant grotuvus.",
  "ui.text_only": "Tik tekstas",
  "ui.text_tone": "Teksto tonas",
  "ui.theme": "Tema",
  "ui.theme_2": "Tema",
  "ui.theme_mode": "Temos režimas",
  "ui.theme_toggle": "Temos perjungiklis",
  "ui.theme_toggle_2": "Temos perjungiklis",
  "ui.this_device": "Šis įrenginys",
  "ui.this_device_2": "Šis įrenginys",
  "ui.this_device_player_connected": "Šio įrenginio grotuvas prijungtas",
  "ui.this_device_player_disconnected": "Šio įrenginio grotuvas atjungtas",
  "ui.thu": "Ket",
  "ui.timer": "Laikmatis",
  "ui.timer_active_remaining": "Laikmatis aktyvus: {remaining}",
  "ui.timers": "Laikmačiai",
  "ui.to": "Iki",
  "ui.today": "Šiandien",
  "ui.track": "Kūrinys",
  "ui.track_lyrics": "Kūrinio žodžiai",
  "ui.tracks": "Kūriniai",
  "ui.transfer_clone_inspect_or_clear_queues_without_hiding_the_studio": "Perkelkite, klonuokite arba išvalykite eiles nepaslėpdami Studio.",
  "ui.transfer_is_unavailable_while_a_pinned_player_is_configured": "Perkėlimas nepasiekiamas, kol konfigūruotas prisegtas grotuvas",
  "ui.transfer_queue": "Perkelti eilę",
  "ui.transfer_queue_2": "Perkelti eilę",
  "ui.transfer_queue_3": "Perkelti eilę",
  "ui.try_again": "Bandykite dar kartą",
  "ui.tts_entity": "TTS objektas",
  "ui.tts_entity_used_by_the_announcement_screen": "TTS objektas pranešimų ekranui.",
  "ui.tts_language": "TTS kalba",
  "ui.tue": "Ant",
  "ui.turkey": "Turkija",
  "ui.turn_off": "Išjungti",
  "ui.turns_off_after_run": "Išsijungia po paleidimo",
  "ui.turns_off_heavy_visuals_so_the_card_runs_smoother_on_nest_hub_older_tabl": "Išjungia sunkius vaizdus sklandesniam veikimui Nest Hub ir silpnesnėse planšetėse.",
  "ui.type_a_free_style_first": "Pirmiausia įveskite laisvą stilių",
  "ui.type_an_announcement": "Įveskite pranešimą...",
  "ui.type_anything": "Įveskite bet ką",
  "ui.type_what_should_be_announced": "Įveskite, kas turėtų būti pranešta...",
  "ui.ungroup": "Išgrupuoti",
  "ui.ungroup_2": "Išgrupuoti",
  "ui.united_kingdom": "Jungtinė Karalystė",
  "ui.united_states": "Jungtinės Valstijos",
  "ui.unknown": "Nežinoma",
  "ui.up": "Aukštyn",
  "ui.up_next": "Kitas",
  "ui.up_next_2": "Kitas",
  "ui.up_next_title": "Kitas: {title}",
  "ui.upbeat_and_moving": "Ritmingas ir judrus",
  "ui.use_any_home_assistant_path_example_lovelace_home": "Naudokite bet kurį Home Assistant kelią. Pvz.: /lovelace/home",
  "ui.use_current_view_for_home_button": "Naudoti esamą vaizdą pradžios mygtukui",
  "ui.use_expand_to_open_the_full_player": "Naudoti išplėtimą atidarant pilną grotuvą",
  "ui.uses_the_same_base_country_list_shown_in_the_in_card_settings_screen": "Naudoja tą patį šalių sąrašą kaip ir kortelės nustatymuose.",
  "ui.visible_tiles": "matomos plytelės",
  "ui.visible_tiles_2": "Matomos plytelės",
  "ui.visual_editor": "Vizualus redaktorius",
  "ui.assist_agent": "Assist agentas",
  "ui.assist_agent_id": "Assist agento ID",
  "ui.assist_only": "Tik Assist",
  "ui.default_assist_agent": "Numatytasis Home Assistant agentas",
  "ui.hybrid_handles_music_locally_and_sends_unknown_commands_to_assist": "Rekomenduojama: muzikos komandos vykdomos lokaliai. Kitos komandos siunčiamos į Assist.",
  "ui.hybrid_music_plus_assist": "Hibridinis: Muzika + Assist",
  "ui.icon_size": "Piktogramos dydis",
  "ui.music_only": "Tik muzika",
  "ui.music_plus_assist": "Muzika + Assist",
  "ui.optional_assist_agent_id_leave_empty_for_home_assistant_default": "Neprivalomas Assist agento ID. Palikite tuščią numatytajam Home Assistant agentui.",
  "ui.optional_assist_agent_leave_empty_for_home_assistant_default": "Neprivaloma. Palikite numatytąjį agentą.",
  "ui.show_a_push_to_talk_button_for_music_and_assist_commands": "Rodyti „spausk ir kalbėk“ mygtuką muzikos komandoms ir Assist.",
  "ui.speak_voice_assistant_responses_out_loud": "Skaityti atpažintus atsakymus garsiai per šią naršyklę.",
  "ui.flow_assistant": "FLOW ASISTENTAS",
  "ui.voice_assistant": "Balso asistentas",
  "ui.voice_assistant_disabled": "Balso asistentas išjungtas",
  "ui.voice_assistant_listening": "Klausomasi komandos...",
  "ui.voice_assistant_mode": "Balso asistento režimas",
  "ui.voice_command_executed": "Balso komanda įvykdyta",
  "ui.voice_command_completed_action": "Atlikta: {action}",
  "ui.voice_command_failed": "Balso komanda nepavyko",
  "ui.voice_command_no_player": "Pasirinkite grotuvą arba pasakykite jo pavadinimą.",
  "ui.voice_command_not_understood": "Nesulaukiau jokios komandos.",
  "ui.voice_command_sent": "Balso komanda išsiųsta",
  "ui.voice_done_status": "Atlikta",
  "ui.voice_error_status": "Reikia dėmesio",
  "ui.voice_feedback": "Balso atgalinis ryšys",
  "ui.voice_group_connect_needs_players": "Pasakykite bent dviejų grotuvų pavadinimus.",
  "ui.voice_group_connected_players": "Sujungta {primary} su {members}",
  "ui.voice_group_disconnect_needs_player": "Pasakykite, kurią grupę atjungti.",
  "ui.voice_group_disconnected_player": "Atjungta grupė grotuvui {player}",
  "ui.voice_input_failed": "Balso įvestis nepavyko",
  "ui.voice_input_is_not_supported_on_this_device": "Balso įvestis nepalaikoma šiame įrenginyje",
  "ui.voice_language_is_not_supported": "Ši naršyklė nepalaiko pasirinktos kalbos atpažinimo.",
  "ui.voice_match_not_confident": "Radau {title}, bet tai neatitinka \"{query}\". Bandykite dar kartą.",
  "ui.voice_music_searching": "Ieškoma muzikos: {query}",
  "ui.voice_playing_result": "Groja {title}",
  "ui.voice_queue_transfer_needs_players": "Pasakykite šaltinio ir tikslo grotuvus.",
  "ui.voice_queue_transferred_between": "Eilė pervesta iš {source} į {target}",
  "ui.voice_starting_playback": "Pradedama {title}...",
  "ui.voice_processing_status": "Apdorojama komanda...",
  "ui.voice_ready_status": "Paruošta",
  "ui.voice_recognition_network_failed": "Kalbos atpažinimo paslauga nepasiekiama. Patikrinkite tinklą.",
  "ui.voice_response": "Atsakymas",
  "ui.voice_response_will_appear_here": "Atsakymas atsiras čia.",
  "ui.voice_search": "Paieška balsu",
  "ui.voice_search_failed": "Paieška balsu nepavyko",
  "ui.voice_search_is_not_supported_on_this_device": "Paieška balsu šiame įrenginyje nepalaikoma",
  "ui.voice_transcript": "Tekstas",
  "ui.voice_listening_status": "Klausomasi...",
  "ui.waiting_for_speech": "Laukiama kalbos...",
  "ui.microphone_permission_or_browser_blocked": "Naršyklė užblokavo kalbos atpažinimą. Patikrinkite mikrofono leidimus.",
  "ui.volume": "Garsumas",
  "ui.volume_and_player_target": "Garsumas ir grotuvo tikslas",
  "ui.volume_boost": "Garso padidinimas",
  "ui.volume_control_large_screen_only": "Garso valdymas (tik dideliame ekrane)",
  "ui.volume_mode": "Garsumo režimas",
  "ui.volume_presets": "Garsumo šablonai",
  "ui.waiting_for_this_device_player": "Laukiama šio įrenginio grotuvo...",
  "ui.wake": "Pabusti",
  "ui.wake_schedules": "Žadinimo tvarkaraščiai",
  "ui.wed": "Tre",
  "ui.week": "Savaitė",
  "ui.what_would_you_like_to_listen_to": "Ko norėtumėte paklausyti?",
  "ui.will_play_next": "Gros po to",
  "ui.will_play_next_in_studio": "Gros po to (Studio)",
  "ui.worldwide_popular": "Populiaru pasaulyje",
  "ui.add_player_light_pair": "Pridėti porą",
  "ui.ambient_light": "Foninis apšvietimas",
  "ui.ambient_light_brightness": "Apšvietimo ryškumas",
  "ui.ambient_light_cooldown": "Apšvietimo atnaujinimo vėlinimas",
  "ui.ambient_light_entities": "Numatytieji spalvų žibintai",
  "ui.ambient_light_player_map": "Grotuvo -> šviesos susiejimas",
  "ui.ambient_light_player_map_helper": "Naudokite grotuvo ir šviesos parinkiklius. Išvalykite norėdami pašalinti porą.",
  "ui.ambient_light_transition": "Apšvietimo perėjimas",
  "ui.analog": "Analoginis",
  "ui.choose_only_the_lights_that_should_follow_the_music": "Pasirinkite šviesas, kurios seks muziką, kai nėra konkrečios grotuvo poros.",
  "ui.digital": "Skaitmeninis",
  "ui.discover_albums": "Atrasti albumus",
  "ui.discover_music": "Atrasti",
  "ui.discover_subtitle": "Rekomenduojami grojaraščiai, albumai ir radijas.",
  "ui.discovery": "Atradimas",
  "ui.discovery_failed": "Atradimo režimas nepavyko",
  "ui.discovery_mode": "Atradimo režimas",
  "ui.discovery_started": "Atradimas pradėtas: {mood}",
  "ui.maximum_brightness_for_music_lighting": "Maksimalus ryškumas muzikos apšvietimui.",
  "ui.minimum_seconds_between_light_updates": "Minimalus laikas sekundėmis tarp apšvietimo atnaujinimų.",
  "ui.player_light_pair_lights": "Spalvų žibintai {number}",
  "ui.player_light_pair_lights_helper": "Pasirinkite žibintus šiam Music Assistant grotuvui.",
  "ui.player_light_pair_player": "Music Assistant grotuvas {number}",
  "ui.player_light_pair_player_helper": "Pasirinkite Music Assistant grotuvą šiai šviesų porai.",
  "ui.all": "Visi",
  "ui.all_genres": "Visi žanrai",
  "ui.genres_and_styles": "Žanrai ir stiliai",
  "ui.compact_widget_mode": "Kompaktiško valdiklio stilius",
  "ui.choose_when_compact_mode_uses_the_two_row_mobile_widget": "Pasirinkite, kada kompaktiškas režimas naudoja mažesnį dviejų eilučių mobilųjį valdiklį.",
  "ui.full": "Pilnas",
  "ui.mini_widget": "Mini valdiklis",
  "ui.genre": "Žanras",
  "ui.mood_and_genre": "Nuotaika ir žanras",
  "ui.music_by_mood_and_genre": "Muzika pagal nuotaiką ir žanrą",
  "ui.optional_entity_for_the_power_button_leave_empty_to_stop_the_active_player": "Neprivalomas objektas maitinimo mygtukui. Palikite tuščią, kad sustabdytumėte aktyvų grotuvą.",
  "ui.power": "Maitinimas",
  "ui.power_action_failed": "Maitinimo veiksmas nepavyko",
  "ui.power_action_sent": "Maitinimo veiksmas išsiųstas",
  "ui.power_button": "Maitinimo mygtukas",
  "ui.power_button_action": "Maitinimo mygtuko veiksmas",
  "ui.power_button_entity": "Maitinimo mygtuko objektas",
  "ui.scene": "Scena",
  "ui.screensaver": "Ekrano užsklanda",
  "ui.screensaver_controls": "Ekrano užsklandos valdymas",
  "ui.screensaver_clock_mode": "Laikrodžio režimas",
  "ui.screensaver_clock_size": "Laikrodžio dydis",
  "ui.screensaver_clock_size_helper": "Keičia laikrodžio mastelį nekeičiant viršelio.",
  "ui.screensaver_clock_x": "Laikrodžio pozicija - KAIRĖ / DEŠINĖ",
  "ui.screensaver_clock_x_helper": "Mažesnės reikšmės perkelia į kairę, didesnės į dešinę.",
  "ui.screensaver_clock_y": "Laikrodžio pozicija - VIRŠUS / APAČIA",
  "ui.screensaver_clock_y_helper": "Mažesnės reikšmės perkelia į viršų, didesnės į apačią.",
  "ui.screensaver_message": "Ekrano užsklandos pranešimas",
  "ui.screensaver_timeout": "Ekrano užsklandos laukimo laikas",
  "ui.script": "Skriptas",
  "ui.short_optional_message_shown_on_the_screensaver": "Trumpas papildomas pranešimas ekrano užsklandoje.",
  "ui.show_previous_next_controls_on_the_screensaver": "Rodyti ankstesnio ir kito mygtukus ekrano užsklandoje.",
  "ui.show_a_calm_clock_artwork_display_after_idle_time": "Rodyti ramų laikrodį ir viršelį po ramybės laiko.",
  "ui.show_power_button_in_the_player_controls": "Rodyti maitinimo mygtuką grotuvo valdyme.",
  "ui.show_the_fullscreen_discovery_mode_in_actions": "Rodyti pilno ekrano atradimo režimą veiksmuose.",
  "ui.smart_home": "Išmanieji namai",
  "ui.soft_transition_time_for_music_lighting": "Minkštas perėjimo laikas muzikos apšvietimui.",
  "ui.stop_player": "Sustabdyti grotuvą",
  "ui.sync_selected_lights_to_the_current_artwork_color": "Sinchronizuoti pasirinktas šviesas su viršelio spalva.",
  "ui.toggle": "Perjungti",
  "ui.turn_on": "Įjungti",
  "ui.choose_a_category_to_browse_provider_playlists": "Pasirinkite kategoriją tiekėjo grojaraščiams naršyti.",
  "ui.new_and_recommended": "Nauja ir rekomenduojama",
  "ui.provider_playlists": "Tiekėjo grojaraščiai",
  "ui.alphabetical": "Alphabetical",
  "ui.auxiliary_button": "Auxiliary button",
  "ui.auxiliary_button_action": "Auxiliary button action",
  "ui.auxiliary_button_entity": "Auxiliary button entity",
  "ui.auxiliary_button_icon": "Auxiliary button icon",
  "ui.auxiliary_button_name": "Auxiliary button name",
  "ui.auxiliary_buttons": "Auxiliary buttons",
  "ui.excluded_players": "Excluded players",
  "ui.music_assistant_required": "Music Assistant required",
  "ui.player_order": "Player order",
  "ui.player_sort": "Player sort",
  "ui.set_the_visual_order_of_quick_actions": "Set the visual order. Only selected Quick Actions are shown; unselected items are ignored.",
  "ui.move_down": "Move down",
  "ui.move_up": "Move up",
  "ui.default_order": "Default order",
  "ui.show_home_inside_quick_actions": "Shows Home as a Quick Action instead of a floating button.",
  "ui.show_plus_minus_buttons_next_to_the_volume_slider": "Show plus and minus buttons next to the volume slider.",
  "ui.volume_down": "Volume down",
  "ui.volume_step_between_1_and_10_percent_default_5": "Volume step between 1% and 10%. Default is 5%.",
  "ui.volume_step_buttons": "Volume +/- buttons",
  "ui.volume_step_percent": "Volume step",
  "ui.volume_up": "Volume up",
  "ui.optional_name_for_the_auxiliary_button": "Optional label shown as the auxiliary button tooltip.",
  "ui.choose_the_auxiliary_button_icon": "Choose the icon shown for the auxiliary button.",
  "ui.choose_how_players_are_sorted": "Choose default, alphabetical, or custom player order.",
  "ui.choose_music_assistant_players_to_hide_from_the_card": "Choose Music Assistant players that should never appear in the card.",
  "ui.custom_order": "Custom order",
  "ui.no_visible_music_assistant_players_after_exclusions": "All Music Assistant players are hidden by the excluded players setting.",
  "ui.set_custom_player_order": "Set the custom player order. Empty slots are ignored.",
  "ui.show_auxiliary_button_in_quick_actions": "Shows this auxiliary button in the Quick Actions row.",
  "ui.screensaver_buttons": "Screensaver buttons",
  "ui.choose_which_buttons_appear_on_the_screensaver": "Choose exactly which buttons appear on the screensaver, including FLOW ASSISTANT, previous and next.",
  "ui.hotel_mode": "Viešbučio režimas",
  "ui.hotel_mode_helper": "Minimali viešbučiui saugi sąsaja: tik grotuvo valdymas, garsumas, paieška, viršelių naršymas ir grotuvo pasirinkimas.",
  "ui.style_and_genres": "Stiliai ir žanrai",
  "ui.card_id": "Card ID",
  "ui.card_id_helper": "Unique slug (letters, digits, '-', '_'). Set this when running multiple HOMEii Flow dashboards in the same browser so each dashboard keeps its own player picker, theme, layout, and other in-card settings. Leave blank to share state with every other HOMEii Flow card in this browser (the original behaviour).",
});

export default messages;
