// Generated HOMEii Music Flow localization dictionary.
// Keep keys stable. Translate only the string values.
const messages = Object.freeze({
  "ui.a_guided_music_wizard": "Um assistente de música guiado",
  "ui.a_radio_station": "Uma estação de rádio",
  "ui.accent_color": "Cor de destaque",
  "ui.actions": "ações",
  "ui.action_menu_labels": "Nomes das ações abaixo dos ícones",
  "ui.actions_2": "Ações",
  "ui.active_days": "Dias ativos",
  "ui.active_player_helper": "Ajudante do player ativo",
  "ui.active_player_helper_must_be_an_input_text_entity": "O ajudante do player ativo deve ser uma entidade input_text",
  "ui.active_players": "Players Ativos",
  "ui.add": "Adicionar",
  "ui.add_to_queue": "Adicionar à fila",
  "ui.add_to_selection": "Adicionar à seleção",
  "ui.added_to_liked": "Adicionado aos curtidos",
  "ui.added_to_music_assistant_liked": "Adicionado aos curtidos do Music Assistant",
  "ui.added_to_queue": "Adicionado à fila",
  "ui.added_to_studio_queue": "Adicionado à fila do Studio",
  "ui.adds_motion_to_the_background_layers_subtle_keeps_it_calm_strong_is_noti": "Adiciona movimento às camadas de fundo. 'Sutil' mantém a calma, 'Forte' é perceptível e 'Extremo' é o visual animado mais ousado.",
  "ui.adds_to_the_current_volume_only_during_announcements_then_restores_the_p": "Aumenta o volume atual apenas durante os anúncios e depois restaura o volume anterior.",
  "ui.after_run": "Após execução",
  "ui.album": "Álbum",
  "ui.albums": "Álbuns",
  "ui.all_albums": "Todos os Álbuns",
  "ui.all_artists": "Todos os Artistas",
  "ui.all_countries": "Todos os países",
  "ui.all_player_groups_disconnected": "Todos os grupos de players desconectados",
  "ui.all_players": "Todos os players",
  "ui.all_players_2": "todos os players",
  "ui.all_podcasts": "Todos os Podcasts",
  "ui.all_tracks": "Todas as Faixas",
  "ui.always_visible": "Sempre visível",
  "ui.announce": "Anunciar",
  "ui.announce_to_all_players": "Anunciar para todos os players",
  "ui.announcement": "Anúncio",
  "ui.announcement_failed_with_error": "Falha no anúncio{error}",
  "ui.announcement_language": "Idioma do anúncio",
  "ui.announcement_presets": "Predefinições de anúncio",
  "ui.announcement_sent_to_player": "Anúncio enviado para {player}",
  "ui.announcement_studio": "estúdio de anúncios",
  "ui.announcement_studio_2": "Estúdio de Anúncios",
  "ui.announcement_target": "Alvo do anúncio",
  "ui.announcement_to_player_preview": "Anúncio para {player}: {preview}",
  "ui.announcement_volume_boost": "Aumento de volume do anúncio",
  "ui.announcements": "Anúncios",
  "ui.appearance": "Aparência",
  "ui.alphabetical": "Alfabético",
  "ui.auxiliary_button": "Botão auxiliar",
  "ui.auxiliary_button_action": "Ação do botão auxiliar",
  "ui.auxiliary_button_entity": "Entidade do botão auxiliar",
  "ui.auxiliary_button_icon": "Ícone do botão auxiliar",
  "ui.auxiliary_button_name": "Nome do botão auxiliar",
  "ui.auxiliary_buttons": "Botões auxiliares",
  "ui.apply_group": "Aplicar Grupo",
  "ui.apply_schedule": "Aplicar agendamento",
  "ui.artist": "Artista",
  "ui.artist_radio": "Rádio do artista",
  "ui.artists": "Artistas",
  "ui.artwork": "Capa",
  "ui.artwork_swipe": "Deslizar a capa",
  "ui.ascending": "Ascendente",
  "ui.at_least_one_player_must_stay_selected": "Pelo menos um player deve permanecer selecionado",
  "ui.australia": "Austrália",
  "ui.auto_chooses_mobile_or_tablet_based_on_actual_width": "Escolhe automaticamente mobile ou tablet com base na largura real.",
  "ui.auto_cloud_default": "Auto / Padrão da Nuvem",
  "ui.auto_extracts_colors_from_the_current_artwork_and_keeps_the_effect_subtl": "Extrai automaticamente as cores da capa atual e mantém o efeito sutil. 'Forte' torna a paleta mais rica e brilhante.",
  "ui.auto_leaves_home_assistant_cloud_voice_defaults_untouched_manual_choices": "Auto deixa os padrões de voz do Home Assistant Cloud intactos. Escolhas manuais enviam um idioma explícito.",
  "ui.available": "Disponível",
  "ui.back": "Voltar",
  "ui.back_2": "Voltar",
  "ui.back_to_countries": "Voltar para países",
  "ui.back_to_queue": "Voltar para a fila",
  "ui.background_motion": "Movimento do fundo",
  "ui.behavior": "Comportamento",
  "ui.browse_covers": "Navegar pelas capas",
  "ui.browse_playlists_artists_albums_and_radio": "Navegue por playlists, artistas, álbuns e rádios",
  "ui.browser_players": "Players do Navegador",
  "ui.build_custom_mix": "Criar mix personalizado",
  "ui.building_studio_mix": "Criando mix do Studio...",
  "ui.button": "Botão",
  "ui.by_mood": "Por humor",
  "ui.cache_duration_in_milliseconds_for_selected_data_requests": "Duração do cache em milissegundos para requisições de dados selecionadas.",
  "ui.cache_ttl": "TTL do Cache",
  "ui.calm": "Calmo",
  "ui.canada": "Canadá",
  "ui.cancel": "Cancelar",
  "ui.cancel_2": "Cancelar",
  "ui.cancel_selection": "Cancelar seleção",
  "ui.card_configuration": "Configuração do cartão",
  "ui.card_height": "Altura do cartão",
  "ui.card_height_in_pixels": "Altura do cartão em pixels.",
  "ui.card_settings_are_managed_from_the_visual_editor": "As configurações do cartão são gerenciadas a partir do editor visual",
  "ui.change_song": "Mudar de música",
  "ui.change_track": "Mudar de faixa",
  "ui.chill_mix": "Mix relaxante",
  "ui.choose_a_country_or_all_countries_to_browse_every_country_inside_the_rad": "Escolha um país, ou 'Todos os países' para navegar por todos eles na aba Rádio.",
  "ui.choose_a_queue_position": "Escolha uma posição na fila",
  "ui.choose_a_source_player": "Escolha um player de origem",
  "ui.choose_a_target_player": "Escolha um player de destino",
  "ui.choose_at_least_one_player": "Escolha pelo menos um player",
  "ui.choose_icons_text_or_both_for_the_footer": "Escolha ícones, texto ou ambos para o rodapé.",
  "ui.choose_music_assistant_players_only_the_in_card_pinning_list_shows_only": "Escolha apenas players do Music Assistant. A lista de fixação no cartão mostra apenas players do Music Assistant para evitar confusão.",
  "ui.choose_one_clear_option": "Escolha uma opção de limpar",
  "ui.choose_player": "Escolher Player",
  "ui.choose_something_from_the_quick_shelf_or_tap_the_wand_for_a_random_playl": "Escolha algo na prateleira rápida ou toque em 'Surpreenda-me' para uma playlist aleatória.",
  "ui.choose_source": "Escolher origem",
  "ui.choose_target": "Escolher destino",
  "ui.choose_target_player": "Escolher player de destino",
  "ui.choose_the_accent_color_for_the_mobile_layout": "Escolha a cor de destaque para o layout mobile.",
  "ui.choose_the_music": "Escolha a música",
  "ui.choose_the_small_buttons_shown_under_the_song_title_timer_appears_first": "Escolha e ordene os botões pequenos exibidos abaixo do título da música.",
  "ui.choose_the_source_first_playback_will_use_the_current_target": "Escolha a origem primeiro. A reprodução usará o destino atual.",
  "ui.choose_where_to_play": "Escolha onde tocar",
  "ui.choose_whether_artwork_swipe_changes_track_or_browses_covers": "Escolha se deslizar a capa muda de faixa ou navega pelas capas.",
  "ui.choose_whether_settings_are_controlled_from_the_in_card_ui_or_from_the_c": "Escolha se as configurações são controladas pela interface do cartão ou pela configuração do cartão no painel.",
  "ui.choose_which_actions_appear_in_the_main_bar": "Escolha quais ações aparecem na barra principal.",
  "ui.choose_which_days_the_auto_night_mode_window_applies_to": "Escolha a quais dias a janela de modo noturno automático se aplica.",
  "ui.choose_which_icons_appear_in_the_quick_action_row": "Escolha quais ícones aparecem na linha de ações rápidas. 'Limpar tudo' pede confirmação antes de desconectar os players ativos.",
  "ui.choose_which_players_appear_as_tiles_in_the_room": "Escolha quais players aparecem como blocos no ambiente.",
  "ui.choose_which_players_stay_in_the_current_control_selection": "Escolha quais players permanecem na seleção de controle atual.",
  "ui.choose_which_tabs_are_available_in_the_library_screen": "Escolha quais abas estão disponíveis na tela da biblioteca.",
  "ui.choose_who_is_controlled": "Escolha quem será controlado",
  "ui.choosing_visual_disables_the_in_card_settings_screen": "Escolher Visual desativa a tela de configurações do cartão.",
  "ui.clean_all": "Limpar tudo",
  "ui.clean_all_confirm_action": "Limpar tudo",
  "ui.clean_all_confirm_copy": "Isso desconectará todos os players ativos, interromperá a reprodução e limpará as filas. Continuar?",
  "ui.clean_all_confirm_title": "Limpar todos os players?",
  "ui.clean_the_studio_wall": "Limpar o mural do Studio",
  "ui.clear": "Limpar",
  "ui.clear_queue": "Limpar fila",
  "ui.clear_search": "Limpar busca",
  "ui.clone_queue": "Clonar fila",
  "ui.close": "Fechar",
  "ui.collapse_compact_player": "Recolher player compacto",
  "ui.compact_mode": "Modo compacto",
  "ui.configure_ready_made_announcement_phrases": "Configure frases de anúncio prontas.",
  "ui.connect_this_device": "Conectar Este Dispositivo",
  "ui.connect_this_device_2": "Conectar este dispositivo",
  "ui.connected": "Conectado",
  "ui.connected_2": "Conectado",
  "ui.connected_players": "players conectados",
  "ui.connected_players_2": "Players conectados",
  "ui.connecting": "Conectando",
  "ui.connecting_2": "Conectando...",
  "ui.confirm": "Confirmar",
  "ui.connection_and_behavior": "Conexão e Comportamento",
  "ui.connects_directly_from_this_card_using_sendspin": "Conecta diretamente a partir deste cartão usando Sendspin",
  "ui.continue": "Continuar",
  "ui.continue_2": "Continuar",
  "ui.continue_from_recent_music_assistant_activity": "Continuar a partir da atividade recente do Music Assistant.",
  "ui.continue_listening": "Continuar ouvindo",
  "ui.continue_what_was_played_recently": "Continuar o que foi tocado recentemente",
  "ui.control_whether_the_card_background_moves_gently_and_how_strong_the_moti": "Controle se o fundo do cartão se move suavemente e quão forte é a sensação do movimento.",
  "ui.controlling": "Controlando",
  "ui.could_not_build_quick_mix_from_the_current_song": "Não foi possível criar o Quick Mix a partir da música atual",
  "ui.could_not_build_studio_mix": "Não foi possível criar o mix do Studio",
  "ui.could_not_choose_media": "Não foi possível escolher a mídia",
  "ui.could_not_clone_the_queue": "Não foi possível clonar a fila",
  "ui.could_not_find_music": "Não foi possível encontrar a música",
  "ui.could_not_play_label": "Não foi possível tocar: {label}",
  "ui.could_not_start_chill_mix": "Não foi possível iniciar o mix relaxante",
  "ui.could_not_start_playback": "Não foi possível iniciar a reprodução",
  "ui.could_not_start_playback_2": "Não foi possível iniciar a reprodução",
  "ui.could_not_start_playback_in_studio": "Não foi possível iniciar a reprodução no Studio",
  "ui.could_not_start_quick_mix": "Não foi possível iniciar o Quick Mix",
  "ui.could_not_start_radio_playback": "Não foi possível iniciar a reprodução da rádio",
  "ui.could_not_transfer_the_queue": "Não foi possível transferir a fila",
  "ui.could_not_update_active_player_helper": "Não foi possível atualizar o ajudante do player ativo",
  "ui.create_schedule": "Criar agendamento",
  "ui.current_path": "Caminho atual",
  "ui.custom": "Personalizado",
  "ui.dark": "Escuro",
  "ui.delete_scene": "Excluir cena",
  "ui.delete_schedule": "Excluir agendamento",
  "ui.descending": "Descendente",
  "ui.dictate": "Ditar",
  "ui.disabled": "Desativado",
  "ui.disables_blur_animations_dynamic_backgrounds_and_heavy_shadows_recommend": "Desativa desfoque, animações, fundos dinâmicos e sombras fortes. Recomendado para Nest Hub e tablets mais fracos.",
  "ui.disconnect": "Desconectar",
  "ui.disconnect_all": "Desconectar todos",
  "ui.disconnect_groups": "Desconectar grupos",
  "ui.disconnect_player_groups": "Desconectar grupos de players",
  "ui.disconnect_this_device": "Desconectar Este Dispositivo",
  "ui.disconnected": "Desconectado",
  "ui.disconnecting": "Desconectando",
  "ui.disconnecting_player_groups": "Desconectando grupos de players...",
  "ui.discover": "Descobrir",
  "ui.down": "Para baixo",
  "ui.dynamic_theme": "Tema dinâmico",
  "ui.edit_schedule": "Editar agendamento",
  "ui.enable": "Ativar",
  "ui.enable_or_disable_the_footer_search_button": "Ative ou desative o botão de busca no rodapé.",
  "ui.enable_or_disable_the_studio_button_in_the_footer_bar": "Ative ou desative o botão do Studio na barra de rodapé.",
  "ui.enable_the_floating_home_shortcut_button": "Ative o atalho de Início nas Ações Rápidas.",
  "ui.enabled": "Ativado",
  "ui.enables_switching_to_local_liked_mode": "Permite alternar para o modo de curtidas locais.",
  "ui.end_time": "Hora de término",
  "ui.excluded_players": "Players excluídos",
  "ui.energetic": "Enérgico",
  "ui.energy_and_rhythm": "Energia e ritmo",
  "ui.enter_an_announcement_first": "Insira um anúncio primeiro",
  "ui.example_quiet_jazz_greek_music_workout": "Exemplo: jazz tranquilo, música grega, treino",
  "ui.existing_content": "Conteúdo existente",
  "ui.expand_player": "Expandir player",
  "ui.extract_colors_from_the_current_artwork_and_apply_them_to_the_interface": "Extrai cores da capa atual e as aplica à interface.",
  "ui.extreme": "Extremo",
  "ui.fallback_for_setups_that_need_an_alternate_queue_service_path": "Alternativa para configurações que precisam de um caminho alternativo para o serviço de fila.",
  "ui.fallback_mode": "Modo de contingência",
  "ui.family_friendly": "Para a família",
  "ui.favorite": "Favorito",
  "ui.favorite_action_failed": "Falha na ação de favorito",
  "ui.favorite_action_sent": "Ação de favorito enviada",
  "ui.favorite_center": "central de favoritos",
  "ui.favorite_center_2": "Central de Favoritos",
  "ui.favorite_radio": "Rádio favorita",
  "ui.favorite_updated": "Favorito atualizado",
  "ui.favorites_and_liked_music": "Favoritos e músicas curtidas",
  "ui.feature_detection_player_context_and_this_device_playback_tools": "Detecção de recursos, contexto do player e ferramentas de reprodução deste dispositivo.",
  "ui.find_music": "Encontrar música",
  "ui.finding_music": "Encontrando música",
  "ui.fixed": "Fixo",
  "ui.flow_mix": "FLOW Mix",
  "ui.font_scale": "Escala da fonte",
  "ui.font_size": "Tamanho da fonte",
  "ui.footer_search": "Busca no rodapé",
  "ui.footer_style": "Estilo do rodapé",
  "ui.footer_style_2": "Estilo do rodapé",
  "ui.for_example_lovelace_home_or_any_other_home_assistant_path": "Por exemplo /lovelace/home ou qualquer outro caminho do Home Assistant.",
  "ui.for_weaker_displays_turns_off_heavy_blur_animations_dynamic_theme_extrac": "Para displays mais fracos: desativa desfoque pesado, animações, extração de tema dinâmico e movimento do fundo.",
  "ui.france": "França",
  "ui.free_style": "Estilo livre",
  "ui.free_style_quiet_jazz_greek_music_workout": "Estilo livre: jazz tranquilo, música grega, treino...",
  "ui.fresh_start": "Começo do zero",
  "ui.fresh_start_2": "Começo do zero",
  "ui.fri": "Sex",
  "ui.friendly_and_simple": "Amigável e simples",
  "ui.from": "De",
  "ui.general": "Geral",
  "ui.general_and_display": "Geral e Exibição",
  "ui.germany": "Alemanha",
  "ui.global_scale_for_every_interface_font_1_is_the_default_size": "Escala global para todas as fontes da interface. 1 é o tamanho padrão.",
  "ui.greece": "Grécia",
  "ui.grid": "Grade",
  "ui.group": "Grupo",
  "ui.group_cleared": "Grupo limpo",
  "ui.group_cleared_2": "Grupo limpo",
  "ui.group_speakers": "Agrupar Alto-falantes",
  "ui.group_speakers_2": "Agrupar Alto-falantes",
  "ui.group_updated": "Grupo atualizado",
  "ui.group_volume": "Volume do grupo",
  "ui.group_volume_up_energetic_mix": "Grupo, aumentar volume, mix enérgico",
  "ui.grouped_players": "Players agrupados",
  "ui.hebrew": "Hebraico",
  "ui.history": "Histórico",
  "ui.history_tabs": "Abas de histórico",
  "ui.home": "Início",
  "ui.home_party_night_presets": "Predefinições de casa, festa e noite",
  "ui.home_path": "Caminho inicial",
  "ui.home_scene_prepared": "Cena da casa preparada",
  "ui.home_shortcut": "Atalho de Início",
  "ui.home_shortcut_path": "Caminho do atalho de Início",
  "ui.icon_and_text": "Ícone e texto",
  "ui.icon_only": "Apenas ícone",
  "ui.icon_plus_text": "Ícone + texto",
  "ui.idle": "Inativo",
  "ui.idle_2": "Inativo",
  "ui.in_card_ui": "Interface no cartão",
  "ui.includes_the_custom_theme_mode_from_the_in_card_settings_screen": "Inclui o modo de tema personalizado da tela de configurações no cartão.",
  "ui.info": "Informações",
  "ui.israel": "Israel",
  "ui.israeli": "Israelense",
  "ui.italy": "Itália",
  "ui.items": "itens",
  "ui.join_selected_players": "Juntar players selecionados",
  "ui.kids": "Crianças",
  "ui.language": "Idioma",
  "ui.larger_lyrics": "Letras maiores",
  "ui.layout_adapted_to_height": "Layout adaptado à altura",
  "ui.layout_mode": "Modo de layout",
  "ui.leave_empty_if_the_card_should_use_home_assistant_only": "Deixe em branco se o cartão deve usar apenas o Home Assistant.",
  "ui.library": "Biblioteca",
  "ui.library_2": "Biblioteca",
  "ui.library_pages": "Páginas da biblioteca",
  "ui.default_library_layout": "Layout padrão da biblioteca",
  "ui.choose_how_library_pages_open_grid_or_list_can_still_be_changed_manually": "Escolha como as páginas da biblioteca são abertas. Você ainda pode alternar entre Grade/Lista dentro da biblioteca.",
  "ui.library_radio": "Rádio da biblioteca",
  "ui.library_surprise": "Surpresa da biblioteca",
  "ui.library_tabs": "Abas da Biblioteca",
  "ui.library_tabs_2": "Abas da biblioteca",
  "ui.light": "Claro",
  "ui.like": "Curtir",
  "ui.like_2": "Curtir",
  "ui.like_3": "Curtir",
  "ui.liked": "Curtidas",
  "ui.liked_mode": "Modo de curtidas",
  "ui.liked_sync": "Sincronização de curtidas",
  "ui.list": "Lista",
  "ui.listening": "Ouvindo...",
  "ui.loading": "Carregando...",
  "ui.loading_favorites": "Carregando favoritos...",
  "ui.loading_library": "Carregando biblioteca...",
  "ui.loading_lyrics": "Carregando letras...",
  "ui.loading_players": "Carregando players...",
  "ui.loading_queue": "Carregando fila...",
  "ui.loading_recent_items": "Carregando itens recentes...",
  "ui.loading_schedules": "Carregando agendamentos...",
  "ui.local": "Local",
  "ui.local_favorites": "Favoritos locais",
  "ui.local_favorites_2": "Favoritos locais",
  "ui.local_mode_is_only_meaningful_when_local_likes_are_enabled": "O modo local só faz sentido quando as curtidas locais estão ativadas.",
  "ui.low_light_listening": "Ouvindo com pouca luz",
  "ui.low_volume_and_quiet_mix": "Baixo volume e mix tranquilo",
  "ui.lower_volume_mood": "Humor de volume mais baixo",
  "ui.lyrics": "Letras",
  "ui.lyrics_earlier": "Letras adiantadas",
  "ui.lyrics_font_size": "Tamanho da fonte das letras",
  "ui.lyrics_later": "Letras atrasadas",
  "ui.lyrics_timing": "Sincronia das letras",
  "ui.lyrics_unavailable_right_now": "Letras indisponíveis no momento",
  "ui.ma_favorite_action_failed_with_error": "Falha na ação de favorito do Music Assistant{error}",
  "ui.ma_interface_path": "Caminho da interface do MA",
  "ui.main_bar": "Barra Principal",
  "ui.main_bar_items": "Itens da barra principal",
  "ui.main_bar_items_2": "Itens da barra principal",
  "ui.main_opacity": "Opacidade principal",
  "ui.mainly_relevant_on_larger_layouts": "Relevante principalmente em layouts maiores.",
  "ui.matches_the_microphone_setting_from_the_in_card_settings_screen": "Corresponde à configuração do microfone na tela de configurações do cartão.",
  "ui.media": "Mídia",
  "ui.media_2": "Mídia",
  "ui.media_actions": "Ações de mídia",
  "ui.media_layout": "Layout de mídia",
  "ui.media_selected_target": "Selecionado: {media} ? Destino: {target}",
  "ui.menu": "Menu",
  "ui.message": "Mensagem",
  "ui.microphone": "Microfone",
  "ui.microphone_2": "Microfone",
  "ui.microphone_is_disabled": "O microfone está desativado",
  "ui.missing_url": "URL ausente",
  "ui.mobile": "Mobile",
  "ui.mon": "Seg",
  "ui.mood_style_or_free_text": "Humor, estilo ou texto livre",
  "ui.more_info": "Mais informações",
  "ui.more_info_is_unavailable_for_this_player": "Mais informações indisponíveis para este player",
  "ui.morning": "Manhã",
  "ui.morning_mix": "Mix matinal",
  "ui.move_to_next": "Mover para o próximo",
  "ui.move_to_position": "Mover para a posição",
  "ui.music": "Música",
  "ui.music_assistant_required": "Music Assistant obrigatório",
  "ui.music_assistant_config_entry_id_if_you_want_direct_integration_lookup_th": "ID da entrada de configuração do Music Assistant, se você quiser a busca direta da integração através do Home Assistant.",
  "ui.music_assistant_config_entry_was_not_found": "A entrada de configuração do Music Assistant não foi encontrada",
  "ui.music_assistant_token": "Token do Music Assistant",
  "ui.music_assistant_url": "URL do Music Assistant",
  "ui.music_hub": "central de música",
  "ui.music_hub_2": "Central de Música",
  "ui.mute": "Mudo",
  "ui.mute_command_failed": "Falha no comando de mudo",
  "ui.my_studio_scene": "Minha Cena do Studio",
  "ui.name_or_keyword": "Nome ou palavra-chave",
  "ui.name_this_studio_scene": "Dê um nome para esta cena do Studio...",
  "ui.netherlands": "Holanda",
  "ui.new_schedule": "Novo agendamento",
  "ui.new_wake_schedule": "Novo agendamento de despertar",
  "ui.newest": "Mais recentes",
  "ui.next": "Próximo",
  "ui.next_track_failed": "Falha ao passar para a próxima faixa",
  "ui.night": "Noite",
  "ui.night_end_time": "Hora de fim da noite",
  "ui.night_mode": "Modo noturno",
  "ui.night_mode_auto_window": "Modo noturno automático {start}-{end}",
  "ui.night_mode_days": "Dias de modo noturno",
  "ui.night_mode_is_always_on": "O modo noturno está sempre ativado",
  "ui.night_mode_is_off": "O modo noturno está desativado",
  "ui.night_mode_is_off_until_you_choose_another_mode": "O modo noturno fica desativado até você escolher outro modo.",
  "ui.night_mode_stays_on_until_you_choose_another_mode": "O modo noturno permanece ativado até você escolher outro modo.",
  "ui.night_schedule_updated": "Agendamento noturno atualizado",
  "ui.night_start_time": "Hora de início da noite",
  "ui.no_active_media": "Nenhuma mídia ativa",
  "ui.no_active_players": "Nenhum player ativo",
  "ui.no_available_players": "Nenhum player disponível",
  "ui.no_content_found": "Nenhum conteúdo encontrado",
  "ui.no_dynamic_player_groups_to_disconnect": "Nenhum grupo dinâmico de players para desconectar",
  "ui.no_extra_ma_players": "Sem players adicionais do MA",
  "ui.no_extra_ma_players_2": "Sem players adicionais do MA",
  "ui.no_favorites_found": "Nenhum favorito encontrado.",
  "ui.no_liked_media_yet": "Nenhuma mídia curtida ainda",
  "ui.no_liked_tracks_to_play": "Nenhuma faixa curtida para tocar",
  "ui.no_light_entities_found": "Nenhuma entidade de luz encontrada.",
  "ui.no_lyrics_found": "Nenhuma letra encontrada",
  "ui.no_matching_content_was_found": "Nenhum conteúdo correspondente foi encontrado",
  "ui.no_media_found": "Nenhuma mídia encontrada.",
  "ui.no_media_found_for_this_search": "Nenhuma mídia encontrada para esta busca.",
  "ui.no_mix_content_found": "Nenhum conteúdo de mix encontrado",
  "ui.no_music_assistant_players_were_found_check_music_assistant_and_media_pl": "Music Assistant é obrigatório. Ative a integração do Music Assistant no Home Assistant e exponha pelo menos um media_player do Music Assistant. Outros media players do Home Assistant são intencionalmente ocultados.",
  "ui.no_music_assistant_players_were_found_for_pinning": "Nenhum player do Music Assistant foi encontrado para fixar.",
  "ui.no_next_track_in_queue": "Sem próxima faixa na fila",
  "ui.no_player_groups_to_disconnect": "Nenhum grupo de players para desconectar",
  "ui.no_player_light_pairs_yet": "Nenhum par player-luz ainda.",
  "ui.no_player_selected": "Nenhum player selecionado",
  "ui.no_players_found": "Nenhum player encontrado",
  "ui.no_players_found_yet": "Nenhum player encontrado ainda",
  "ui.no_playlists_found": "Nenhuma playlist encontrada",
  "ui.no_queue": "Sem fila",
  "ui.no_queue_item_to_rebuild": "Nenhum item na fila para reconstruir",
  "ui.no_queue_to_clone": "Nenhuma fila para clonar",
  "ui.no_radio_browser_countries_found": "Nenhum país do Radio Browser encontrado",
  "ui.no_radio_stations_found": "Nenhuma estação de rádio encontrada",
  "ui.no_recent_listening_yet": "Nenhuma audição recente ainda.",
  "ui.no_results": "Sem resultados",
  "ui.no_results_found": "Nenhum resultado encontrado",
  "ui.no_saved_studio_scenes_yet": "Nenhuma cena do Studio salva ainda.",
  "ui.no_scheduled_start_is_active": "Nenhum início agendado está ativo",
  "ui.no_selected_tracks_to_play": "Nenhuma faixa selecionada para tocar",
  "ui.no_sleep_timer_is_active": "Nenhum timer de sono está ativo",
  "ui.no_speech_was_captured": "Nenhuma fala foi capturada",
  "ui.no_target_players_available": "Nenhum player de destino disponível",
  "ui.no_target_players_available_2": "Nenhum player de destino disponível",
  "ui.no_tts_service_or_entity_is_configured": "Nenhum serviço ou entidade TTS está configurado",
  "ui.no_wake_schedules_yet": "Nenhum agendamento de despertar ainda",
  "ui.none": "Nenhum",
  "ui.nothing_is_playing_right_now": "Nada está tocando no momento",
  "ui.nothing_playing": "Nada tocando",
  "ui.now_playing": "Tocando Agora",
  "ui.now_playing_2": "Tocando agora",
  "ui.off": "Desligado",
  "ui.off_2": "Desligado",
  "ui.off_disables_it_on_keeps_it_active_and_auto_follows_the_configured_time": "Desligado desativa, Ligado o mantém ativo e Auto segue a janela de tempo configurada.",
  "ui.oldest": "Mais antigos",
  "ui.on": "Ligado",
  "ui.one_tap_prepares_players_grouping_volume_and_content_save_your_own_curre": "Um toque prepara os players, o agrupamento, o volume e o conteúdo. Salve seu próprio destino atual do Studio como uma cena local.",
  "ui.only_actions_for_the_current_target_are_shown_here": "Apenas as ações para o destino atual são mostradas aqui.",
  "ui.only_music_assistant_players_are_shown_here_browser_and_local_sendspin_p": "Apenas players do Music Assistant são mostrados aqui. Players do navegador e locais do Sendspin são ocultados para evitar confusão.",
  "ui.only_needed_when_using_a_direct_music_assistant_url": "Necessário apenas ao usar uma URL direta do Music Assistant.",
  "ui.opacity_for_popups_and_overlays": "Opacidade para pop-ups e sobreposições.",
  "ui.opacity_for_the_main_card_background": "Opacidade para o fundo do cartão principal.",
  "ui.open_full_interface": "Abrir interface completa",
  "ui.open_full_queue": "Abrir fila completa",
  "ui.open_interface_in": "Abrir interface em",
  "ui.open_ma": "Abrir MA",
  "ui.open_music_assistant": "Abrir Music Assistant",
  "ui.open_music_assistant_2": "Abrir Music Assistant?",
  "ui.open_music_assistant_on_this_device_to_activate_the_browser_player": "Abra o Music Assistant neste dispositivo para ativar o player do navegador",
  "ui.open_player_picker": "Abrir Seletor de Players",
  "ui.open_queue": "Abrir fila",
  "ui.open_saved_songs": "Abrir músicas salvas",
  "ui.open_the_full_music_assistant_interface": "Abrir a interface completa do Music Assistant?",
  "ui.open_the_full_music_assistant_interface_2": "Abrir a interface completa do Music Assistant",
  "ui.opening_studio_library": "Abrindo biblioteca do Studio",
  "ui.opening_timers": "Abrindo timers",
  "ui.option": "Opção",
  "ui.optional": "Opcional",
  "ui.optional_2": "Opcional",
  "ui.optional_entity_used_for_an_external_favorite_button": "Entidade opcional usada para um botão de favorito externo.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for": "Ajudante input_text opcional atualizado com o entity_id do player ativo para automações e templates.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for_2": "Ajudante input_text opcional atualizado com o entity_id do player ativo para automações e templates.",
  "ui.other": "Outro",
  "ui.other_players": "Outros players",
  "ui.party": "Festa",
  "ui.path_used_when_opening_the_music_assistant_interface": "Caminho usado ao abrir a interface do Music Assistant.",
  "ui.pause": "Pausar",
  "ui.paused": "Pausado",
  "ui.per_device_in_card": "Por dispositivo / no cartão",
  "ui.performance_mode": "Modo de desempenho",
  "ui.performance_mode_for_weak_devices": "Modo de desempenho para dispositivos fracos",
  "ui.performance_profile": "Perfil de desempenho",
  "ui.performance_profile_helper": "Escolha a quantidade de trabalho visual que o cartão pode realizar. 'Ultra Lite' reduz a transparência, desfoque, capas dinâmicas e movimento para dispositivos fracos.",
  "ui.pick_a_mood_or_type_your_own_style_studio_will_search_music_assistant_an": "Escolha um humor ou digite seu próprio estilo. O Studio pesquisará no Music Assistant e montará uma fila.",
  "ui.pinned": "Fixados",
  "ui.pinned_players": "Players fixados",
  "ui.play": "Tocar",
  "ui.play_2": "Tocar",
  "ui.play_a_few_tracks_and_they_will_appear_here": "Toque algumas faixas e elas aparecerão aqui.",
  "ui.play_a_saved_list": "Tocar uma lista salva",
  "ui.play_all": "Tocar tudo",
  "ui.play_an_artist": "Tocar um artista",
  "ui.play_artwork_action": "Ação de tocar a capa",
  "ui.play_everywhere": "Tocar em todos os lugares",
  "ui.play_next": "Tocar a próxima",
  "ui.play_next_and_clear_queue": "Tocar a próxima e limpar a fila",
  "ui.play_now": "Tocar agora",
  "ui.play_now_and_clear_queue": "Tocar agora e limpar a fila",
  "ui.play_pause": "Tocar / Pausar",
  "ui.play_queue_radio_or_remove_favorites_directly_from_studio": "Tocar, colocar na fila, rádio ou remover dos favoritos diretamente do Studio.",
  "ui.play_selected": "Tocar selecionados",
  "ui.playback_command_failed": "Falha no comando de reprodução",
  "ui.playback_command_failed_2": "Falha no comando de reprodução",
  "ui.playback_started": "Reprodução iniciada",
  "ui.player": "player",
  "ui.player_2": "Player",
  "ui.player_count_many": "{count} players",
  "ui.player_count_one": "1 player",
  "ui.player_groups_could_not_be_disconnected": "Os grupos de players não puderam ser desconectados",
  "ui.player_is_pinned_from_settings": "O player está fixado pelas configurações",
  "ui.player_is_ready": "O player está pronto",
  "ui.player_is_ready_nothing_is_playing_right_now": "O player está pronto - nada está tocando no momento",
  "ui.player_order": "Ordem dos players",
  "ui.player_on_this_device": "Player neste dispositivo",
  "ui.player_selected": "Player selecionado",
  "ui.player_settings_and_dsp_presets_stay_read_only_until_music_assistant_exp": "As configurações do player e as predefinições de DSP permanecem somente leitura até que o Music Assistant exponha um esquema confiável para este player.",
  "ui.player_sort": "Ordenação de players",
  "ui.players": "Players",
  "ui.players_queue_and_groups": "Players, fila e grupos",
  "ui.playing": "Tocando",
  "ui.playing_a_random_playlist": "Tocando uma playlist aleatória",
  "ui.playing_a_random_radio_station": "Tocando uma estação de rádio aleatória",
  "ui.playing_on": "Tocando em",
  "ui.playing_on_2": "Tocando em",
  "ui.playlist": "Playlist",
  "ui.playlists": "Playlists",
  "ui.podcast": "Podcast",
  "ui.podcasts": "Podcasts",
  "ui.popup_opacity": "Opacidade dos pop-ups",
  "ui.preset_message": "Mensagem predefinida",
  "ui.previous": "Anterior",
  "ui.primary": "Principal",
  "ui.primary_target": "Destino principal",
  "ui.pro_tools": "Ferramentas Pro",
  "ui.queue": "Fila",
  "ui.queue_2": "Fila",
  "ui.queue_action_failed": "Falha na ação da fila",
  "ui.queue_action_is_not_available_for_this_player": "Ação da fila indisponível para este player",
  "ui.queue_actions": "Ações da fila",
  "ui.queue_cleared": "Fila limpa",
  "ui.queue_cleared_and_item_moved_next": "Fila limpa e item movido para o próximo",
  "ui.queue_cloned": "Fila clonada",
  "ui.queue_cockpit": "cockpit da fila",
  "ui.queue_cockpit_2": "Cockpit da Fila",
  "ui.queue_is_empty": "A fila está vazia",
  "ui.queue_is_unavailable_for_this_player": "A fila está indisponível para este player",
  "ui.queue_item": "Item da fila",
  "ui.queue_item_id_is_not_ready_yet_refresh_the_queue_and_try_again": "O ID do item da fila ainda não está pronto. Atualize a fila e tente novamente.",
  "ui.queue_results": "Resultados da fila",
  "ui.queue_transferred": "Fila transferida",
  "ui.queues_refreshed": "Filas atualizadas",
  "ui.quick_actions": "Ações rápidas",
  "ui.quick_actions_2": "Ações Rápidas",
  "ui.quick_mix": "Mix rápido",
  "ui.quick_mix_started": "Mix rápido iniciado",
  "ui.quick_play": "Toque rápido",
  "ui.radio": "Rádio",
  "ui.radio_browser": "Navegador de Rádios",
  "ui.radio_browser_countries": "Países do Navegador de Rádios",
  "ui.radio_browser_country": "País do Navegador de Rádios",
  "ui.radio_browser_country_2": "País do Navegador de Rádios",
  "ui.radio_mode_is_not_available_for_this_media_type": "O modo de rádio não está disponível para este tipo de mídia",
  "ui.radio_mode_started": "Modo de rádio iniciado",
  "ui.radio_station_changed": "Estação de rádio alterada",
  "ui.radio_stations": "Estações de Rádio",
  "ui.random": "Aleatório",
  "ui.random_gentle_morning_mix": "Mix matinal suave aleatório",
  "ui.random_playlist": "Playlist aleatória",
  "ui.random_radio": "Rádio aleatória",
  "ui.ready": "Pronto",
  "ui.ready_to_play": "Pronto para tocar",
  "ui.recent": "Recentes",
  "ui.recent_continue": "Recentes / Continuar",
  "ui.recent_listening": "audição recente",
  "ui.recent_track": "Faixa recente",
  "ui.recently_added": "Adicionados Recentemente",
  "ui.recently_played": "Tocados Recentemente",
  "ui.recently_played_2": "Tocados recentemente",
  "ui.recommendations_will_appear_once_homeii_flow_sees_your_queue_or_recent_l": "As recomendações aparecerão assim que o HOMEii Flow vir sua fila ou audições recentes.",
  "ui.recommended": "Recomendado",
  "ui.recommended_format_hh_mm_such_as_06_00_crossing_midnight_is_supported": "Formato recomendado: HH:MM, como 06:00. Passar da meia-noite é suportado.",
  "ui.recommended_format_hh_mm_such_as_22_00": "Formato recomendado: HH:MM, como 22:00.",
  "ui.recommended_playlist": "Playlist recomendada",
  "ui.recommended_track": "Faixa recomendada",
  "ui.reconnects_when_you_return_to_this_dashboard": "Reconecta quando você retorna a este painel",
  "ui.refresh": "Atualizar",
  "ui.remember_as_this_device": "Lembrar como este dispositivo",
  "ui.remove": "Remover",
  "ui.remove_from_selection": "Remover da seleção",
  "ui.removed_from_liked": "Removido das curtidas",
  "ui.removed_from_music_assistant_liked": "Removido das curtidas do Music Assistant",
  "ui.reorder_queue": "Reordenar fila",
  "ui.repeat": "Repetir",
  "ui.repeat_all": "Repetir tudo",
  "ui.repeat_off": "Repetição desligada",
  "ui.repeat_one": "Repetir uma",
  "ui.reset": "Redefinir",
  "ui.reset_lyrics_font_size": "Redefinir tamanho da fonte das letras",
  "ui.reset_lyrics_timing": "Redefinir sincronia das letras",
  "ui.results": "Resultados",
  "ui.rtl": "RTL",
  "ui.sat": "Sáb",
  "ui.save_current_target": "Salvar destino atual",
  "ui.save_schedule": "Salvar agendamento",
  "ui.scene_players_are_not_available": "Os players da cena não estão disponíveis",
  "ui.scene_presets": "predefinições de cena",
  "ui.scene_presets_2": "Predefinições de Cena",
  "ui.scenes": "Cenas",
  "ui.scales_interface_icons_without_changing_button_sizes": "Dimensiona os ícones da interface sem alterar os tamanhos dos botões ou o layout.",
  "ui.scheduled_start": "Início agendado",
  "ui.scheduled_start_activated_label": "Início agendado ativado: {label}",
  "ui.scheduled_start_cleared": "Início agendado cancelado",
  "ui.scheduled_start_failed": "Falha no início agendado",
  "ui.scheduled_start_saved": "Início agendado salvo",
  "ui.scheduled_starts_active_count": "{count} inícios agendados ativos",
  "ui.schedules": "Agendamentos",
  "ui.search": "Buscar",
  "ui.search_and_choose_play_next_add_radio_or_like": "Busque e escolha Tocar, Próxima, Adicionar, Rádio ou Curtir.",
  "ui.search_everything": "Buscar em tudo...",
  "ui.search_failed": "Falha na busca",
  "ui.search_in_queue": "Buscar na fila",
  "ui.search_queue_and_library": "Buscar na fila e na biblioteca...",
  "ui.search_the_library": "Buscar na biblioteca...",
  "ui.search_tracks_albums_artists_and_playlists": "Buscar faixas, álbuns, artistas e playlists",
  "ui.searching": "Buscando...",
  "ui.searching_library": "Buscando na biblioteca...",
  "ui.searching_smart_selection": "Buscando seleção inteligente...",
  "ui.seek": "Buscar posição",
  "ui.select": "Selecionar",
  "ui.select_lights": "Selecionar luz ou luzes",
  "ui.select_player": "Selecionar player",
  "ui.select_2": "Selecionar",
  "ui.select_a_player_first": "Selecione um player primeiro",
  "ui.select_at_least_one_studio_player": "Selecione pelo menos um player do Studio",
  "ui.select_at_least_two_players_to_create_a_group": "Selecione pelo menos dois players para criar um grupo",
  "ui.selected": "Selecionados",
  "ui.selected_music": "Música selecionada",
  "ui.selected_player": "Player Selecionado",
  "ui.selected_player_2": "Player selecionado",
  "ui.selected_player_3": "Player selecionado",
  "ui.selected_players_at_comfortable_volume": "Players selecionados em um volume confortável",
  "ui.selected_playlist": "Playlist selecionada",
  "ui.send_a_short_voice_message_or_announcement_url": "Envie uma mensagem de voz curta ou URL de anúncio.",
  "ui.send_a_voice_message": "Enviar uma mensagem de voz",
  "ui.send_announcement": "Enviar anúncio",
  "ui.sendspin_and_diagnostics": "Sendspin e diagnósticos",
  "ui.set_sleep_timer": "Definir timer para dormir",
  "ui.set_volume": "Definir volume",
  "ui.set_the_visual_order_of_quick_actions": "Defina a ordem visual. Apenas as Ações Rápidas selecionadas são mostradas; itens não selecionados são ignorados.",
  "ui.settings": "Configurações",
  "ui.settings_section_announcements": "Anúncios",
  "ui.settings_section_display": "Exibição",
  "ui.settings_section_music_assistant": "Music Assistant",
  "ui.settings_section_players_library": "Players e Biblioteca",
  "ui.settings_section_quick_actions_bar": "Ações Rápidas e Barra",
  "ui.settings_section_smart_home": "Casa Inteligente e Proteção de Tela",
  "ui.settings_section_voice_assistant": "Assistente de Voz",
  "ui.settings_source": "Origem das configurações",
  "ui.show_ma_button": "Mostrar botão do MA",
  "ui.show_or_hide_the_inline_next_track_row_in_now_playing": "Mostre ou oculte a linha da próxima faixa diretamente em 'Tocando Agora'.",
  "ui.show_theme_toggle": "Mostrar botão de alternar tema",
  "ui.show_up_next": "Mostrar a Próxima",
  "ui.show_up_next_2": "Mostrar a Próxima",
  "ui.shows_a_standalone_compact_player_tile_with_artwork_basic_controls_volum": "Mostra um bloco de player compacto independente com capa, controles básicos, volume e uma ação de expandir.",
  "ui.shuffle": "Aleatório",
  "ui.shuffle_all": "Misturar tudo",
  "ui.shuffle_favorites": "Misturar favoritos",
  "ui.shuffle_play": "Tocar no modo aleatório",
  "ui.skipped_to_up_next": "Pulou para a próxima",
  "ui.sleep_timer": "Timer para dormir",
  "ui.sleep_timer_2": "Timer para Dormir",
  "ui.sleep_timer_active_remaining": "Timer ativo: {remaining}",
  "ui.sleep_timer_added_minutes": "Adicionados {minutes} minutos ao timer",
  "ui.sleep_timer_and_morning_playback": "Timer para dormir e reprodução matinal",
  "ui.sleep_timer_and_scheduled_playback": "Timer para dormir e reprodução agendada",
  "ui.sleep_timer_cleared": "Timer para dormir cancelado",
  "ui.sleep_timer_finished": "Timer para dormir concluído",
  "ui.sleep_timer_presets": "Predefinições de timer para dormir",
  "ui.sleep_timer_set_for_15_minutes": "Timer para dormir definido para 15 minutos",
  "ui.sleep_timer_set_minutes": "Timer para dormir definido para {minutes} minutos",
  "ui.sleep_timer_updated_minutes": "Timer atualizado para {minutes} minutos",
  "ui.smaller_lyrics": "Letras menores",
  "ui.smart": "Inteligente",
  "ui.smart_mix": "mix inteligente",
  "ui.smart_mix_builder": "Criador de Mix Inteligente",
  "ui.smart_voice_selection": "Seleção de voz inteligente",
  "ui.soft_and_relaxed": "Suave e relaxado",
  "ui.soft_relaxed_music": "Música suave e relaxante",
  "ui.some_players_could_not_be_stopped_or_cleared": "Alguns players não puderam ser parados ou limpos",
  "ui.songs_around_an_artist": "Músicas similares a um artista",
  "ui.sort": "Ordenar",
  "ui.sort_ascending": "Ordenar crescentemente",
  "ui.sort_descending": "Ordenar decrescentemente",
  "ui.source_queue": "Fila de origem",
  "ui.spain": "Espanha",
  "ui.speak_to_target_players": "Falar com os players de destino",
  "ui.start_radio_mode": "Iniciar modo de rádio",
  "ui.start_time": "Hora de início",
  "ui.start_time_2": "Hora de início",
  "ui.started_on_selected_player": "Iniciado no player selecionado",
  "ui.starting_a_chill_mix": "Iniciando um mix relaxante",
  "ui.starting_quick_mix": "Iniciando Quick Mix...",
  "ui.stations": "estações",
  "ui.stay_active": "Manter ativo",
  "ui.stays_active": "Permanece ativo",
  "ui.stop_all": "Parar tudo",
  "ui.stop_all_players": "Parar todos os players",
  "ui.stop_command_failed": "Falha no comando de parar",
  "ui.stop_playback_clear_queues_and_disconnect_groups": "Parar reprodução, limpar filas e desconectar grupos",
  "ui.stopped_all_players_cleared_playlists_and_disconnected_groups": "Parou todos os players, limpou as playlists e desconectou os grupos",
  "ui.stops_this_browser_player": "Para este player do navegador",
  "ui.strong": "Forte",
  "ui.studio": "Studio",
  "ui.studio_closed": "Studio fechado",
  "ui.studio_media_action_failed": "Falha na ação de mídia do Studio",
  "ui.studio_mix_started": "Mix do Studio iniciado",
  "ui.studio_opened": "Studio aberto",
  "ui.studio_pro": "studio pro",
  "ui.studio_pro_2": "Studio Pro",
  "ui.studio_scene": "Cena do Studio",
  "ui.studio_scene_deleted": "Cena do Studio excluída",
  "ui.studio_scene_saved": "Cena do Studio salva",
  "ui.studio_scene_was_not_found": "A cena do Studio não foi encontrada",
  "ui.studio_search": "busca do studio",
  "ui.studio_shortcut": "Atalho do Studio",
  "ui.subtle": "Sutil",
  "ui.sun": "Dom",
  "ui.surprise_me": "Surpreenda-me",
  "ui.sync": "Sincronizar",
  "ui.sync_lyrics": "Sincronizar letras",
  "ui.tablet": "Tablet",
  "ui.tap_to_start_a_sleep_timer": "Toque para iniciar um timer para dormir",
  "ui.target_players": "Players de destino",
  "ui.target_queue": "Fila de destino",
  "ui.text_announcements_use_home_assistant_tts_into_the_selected_music_assist": "Anúncios de texto usam o TTS do Home Assistant no player do Music Assistant selecionado. Anúncios de URL usam a reprodução de anúncios do Music Assistant.",
  "ui.text_only": "Apenas texto",
  "ui.text_tone": "Tom do texto",
  "ui.theme": "Tema",
  "ui.theme_2": "Tema",
  "ui.theme_mode": "Modo do tema",
  "ui.theme_toggle": "Alternar tema",
  "ui.theme_toggle_2": "Alternar tema",
  "ui.this_device": "Este Dispositivo",
  "ui.this_device_2": "Este dispositivo",
  "ui.this_device_player_connected": "Player deste dispositivo conectado",
  "ui.this_device_player_disconnected": "Player deste dispositivo desconectado",
  "ui.thu": "Qui",
  "ui.timer": "Timer",
  "ui.timer_active_remaining": "Timer ativo: {remaining}",
  "ui.timers": "Timers",
  "ui.to": "Para",
  "ui.today": "Hoje",
  "ui.track": "Faixa",
  "ui.track_lyrics": "Letras da Faixa",
  "ui.tracks": "Faixas",
  "ui.transfer_clone_inspect_or_clear_queues_without_hiding_the_studio": "Transfira, clone, inspecione ou limpe filas sem ocultar o Studio.",
  "ui.transfer_is_unavailable_while_a_pinned_player_is_configured": "A transferência está indisponível enquanto um player fixado estiver configurado",
  "ui.transfer_queue": "Transferir Fila",
  "ui.transfer_queue_2": "Transferir fila",
  "ui.transfer_queue_3": "Transferir fila",
  "ui.try_again": "Tentar novamente",
  "ui.tts_entity": "Entidade TTS",
  "ui.tts_entity_used_by_the_announcement_screen": "Entidade TTS usada pela tela de anúncio.",
  "ui.tts_language": "Idioma do TTS",
  "ui.tue": "Ter",
  "ui.turkey": "Turquia",
  "ui.turn_off": "Desligar",
  "ui.turns_off_after_run": "Desliga após executar",
  "ui.turns_off_heavy_visuals_so_the_card_runs_smoother_on_nest_hub_older_tabl": "Desliga visuais pesados para que o cartão funcione mais suavemente no Nest Hub, tablets mais antigos e displays mais fracos.",
  "ui.type_a_free_style_first": "Digite um estilo livre primeiro",
  "ui.type_an_announcement": "Digite um anúncio...",
  "ui.type_anything": "Digite qualquer coisa",
  "ui.type_what_should_be_announced": "Digite o que deve ser anunciado...",
  "ui.ungroup": "Desagrupar",
  "ui.ungroup_2": "Desagrupar",
  "ui.united_kingdom": "Reino Unido",
  "ui.united_states": "Estados Unidos",
  "ui.unknown": "Desconhecido",
  "ui.up": "Para cima",
  "ui.move_down": "Mover para baixo",
  "ui.move_up": "Mover para cima",
  "ui.up_next": "A Seguir",
  "ui.up_next_2": "A seguir",
  "ui.up_next_title": "A seguir: {title}",
  "ui.upbeat_and_moving": "Animado e empolgante",
  "ui.use_any_home_assistant_path_example_lovelace_home": "Use qualquer caminho do Home Assistant. Exemplo: /lovelace/home",
  "ui.use_current_view_for_home_button": "Usar a visualização atual para o botão Início",
  "ui.use_expand_to_open_the_full_player": "Use expandir para abrir o player completo",
  "ui.uses_the_same_base_country_list_shown_in_the_in_card_settings_screen": "Usa a mesma lista base de países mostrada na tela de configurações do cartão.",
  "ui.visible_tiles": "blocos visíveis",
  "ui.visible_tiles_2": "Blocos visíveis",
  "ui.visual_editor": "Editor visual",
  "ui.assist_agent": "Agente do Assist",
  "ui.assist_agent_id": "ID do agente do Assist",
  "ui.assist_only": "Apenas Assist",
  "ui.default_assist_agent": "Assist padrão do Home Assistant",
  "ui.default_order": "Ordem padrão",
  "ui.hybrid_handles_music_locally_and_sends_unknown_commands_to_assist": "Recomendado: os comandos de música rodam localmente no player selecionado. Qualquer coisa que o cartão não entender será enviada para o Assist do Home Assistant.",
  "ui.hybrid_music_plus_assist": "Híbrido: Música + Assist",
  "ui.icon_size": "Tamanho do ícone",
  "ui.music_only": "Apenas música",
  "ui.music_plus_assist": "Música + Assist",
  "ui.optional_assist_agent_id_leave_empty_for_home_assistant_default": "ID opcional do agente do Assist. Deixe em branco para usar o agente Assist padrão do Home Assistant.",
  "ui.optional_assist_agent_leave_empty_for_home_assistant_default": "Opcional. Deixe no agente padrão a menos que você tenha vários agentes Assist e queira que este cartão use um agente específico.",
  "ui.show_a_push_to_talk_button_for_music_and_assist_commands": "Mostra um botão push-to-talk para comandos de música e fallback do Assist.",
  "ui.show_home_inside_quick_actions": "Mostra 'Início' como uma Ação Rápida em vez de um botão flutuante.",
  "ui.show_plus_minus_buttons_next_to_the_volume_slider": "Mostra botões de mais e menos ao lado do controle de volume.",
  "ui.speak_voice_assistant_responses_out_loud": "Fale a resposta reconhecida em voz alta através deste navegador quando suportado.",
  "ui.flow_assistant": "FLOW ASSISTANT",
  "ui.voice_assistant": "Assistente de voz",
  "ui.voice_assistant_disabled": "O assistente de voz está desativado",
  "ui.voice_assistant_listening": "Ouvindo um comando...",
  "ui.voice_assistant_mode": "Modo do assistente de voz",
  "ui.voice_command_executed": "Comando de voz executado",
  "ui.voice_command_completed_action": "Feito: {action}",
  "ui.voice_command_failed": "Falha no comando de voz",
  "ui.voice_command_no_player": "Selecione um player ou diga o nome do player.",
  "ui.voice_command_not_understood": "Não consegui entender esse comando.",
  "ui.voice_command_sent": "Comando de voz enviado",
  "ui.voice_done_status": "Concluído",
  "ui.voice_error_status": "Requer atenção",
  "ui.voice_feedback": "Feedback de voz",
  "ui.voice_group_connect_needs_players": "Diga o nome de pelo menos dois players, ou selecione um player e diga o outro.",
  "ui.voice_group_connected_players": "Conectado {primary} com {members}",
  "ui.voice_group_disconnect_needs_player": "Diga qual grupo de players desconectar.",
  "ui.voice_group_disconnected_player": "Grupo desconectado para {player}",
  "ui.voice_input_failed": "Falha na entrada de voz",
  "ui.voice_input_is_not_supported_on_this_device": "A entrada de voz não é suportada neste dispositivo",
  "ui.voice_language_is_not_supported": "Este navegador não suporta o idioma de reconhecimento de voz selecionado.",
  "ui.voice_match_not_confident": "Encontrei {title}, mas não corresponde suficientemente a \"{query}\". Tente dizer a música e o artista novamente.",
  "ui.voice_music_searching": "Buscando música: {query}",
  "ui.voice_playing_result": "Tocando {title}",
  "ui.voice_queue_transfer_needs_players": "Diga o player de origem e de destino, por exemplo: transferir a fila da Sala para a Cozinha.",
  "ui.voice_queue_transferred_between": "Fila transferida de {source} para {target}",
  "ui.voice_starting_playback": "Iniciando {title}...",
  "ui.voice_processing_status": "Processando comando...",
  "ui.voice_ready_status": "Pronto",
  "ui.voice_recognition_network_failed": "O serviço de reconhecimento de voz está indisponível. A permissão do microfone pode estar OK; verifique o navegador, VPN, DNS, firewall ou rede.",
  "ui.voice_response": "Resposta",
  "ui.voice_response_will_appear_here": "A resposta aparecerá aqui.",
  "ui.voice_search": "Busca por voz",
  "ui.voice_search_failed": "Falha na busca por voz",
  "ui.voice_search_is_not_supported_on_this_device": "A busca por voz não é suportada neste dispositivo",
  "ui.voice_transcript": "Transcrição",
  "ui.voice_listening_status": "Ouvindo...",
  "ui.waiting_for_speech": "Aguardando fala...",
  "ui.microphone_permission_or_browser_blocked": "O navegador bloqueou o reconhecimento de voz. Verifique as configurações de microfone e fala do navegador.",
  "ui.volume": "Volume",
  "ui.volume_and_player_target": "Volume e player de destino",
  "ui.volume_boost": "Aumento de volume",
  "ui.volume_control_large_screen_only": "Controle de volume (apenas tela grande)",
  "ui.volume_down": "Diminuir volume",
  "ui.volume_mode": "Modo de volume",
  "ui.volume_presets": "Predefinições de volume",
  "ui.volume_step_between_1_and_10_percent_default_5": "Passo de volume entre 1% e 10%. O padrão é 5%.",
  "ui.volume_step_buttons": "Botões de Volume +/-",
  "ui.volume_step_percent": "Passo do volume",
  "ui.volume_up": "Aumentar volume",
  "ui.waiting_for_this_device_player": "Aguardando o player deste dispositivo...",
  "ui.wake": "Despertar",
  "ui.wake_schedules": "Agendamentos de despertar",
  "ui.wed": "Qua",
  "ui.week": "Semana",
  "ui.what_would_you_like_to_listen_to": "O que você gostaria de ouvir?",
  "ui.will_play_next": "Tocará em seguida",
  "ui.will_play_next_in_studio": "Tocará em seguida no Studio",
  "ui.worldwide_popular": "Populares no mundo todo",
  "ui.add_player_light_pair": "Adicionar par",
  "ui.ambient_light": "Luz ambiente",
  "ui.ambient_light_brightness": "Brilho da luz",
  "ui.ambient_light_cooldown": "Intervalo de atualização da luz",
  "ui.ambient_light_entities": "Luzes coloridas padrão",
  "ui.ambient_light_player_map": "Mapeamento Player -> Luz",
  "ui.ambient_light_player_map_helper": "Use os seletores de player e luzes coloridas abaixo. Cada linha preenchida se torna um par; limpe um player ou suas luzes para remover o par.",
  "ui.ambient_light_transition": "Transição da luz",
  "ui.analog": "Analógico",
  "ui.choose_only_the_lights_that_should_follow_the_music": "Escolha apenas luzes compatíveis com cores que devem acompanhar a música quando não houver um par específico do player.",
  "ui.digital": "Digital",
  "ui.discover_albums": "Descobrir álbuns",
  "ui.discover_music": "Descobrir",
  "ui.discover_subtitle": "Playlists, álbuns e rádios recomendados.",
  "ui.discovery": "Descoberta",
  "ui.discovery_failed": "Falha no modo descoberta",
  "ui.discovery_mode": "Modo descoberta",
  "ui.discovery_started": "Descoberta iniciada: {mood}",
  "ui.maximum_brightness_for_music_lighting": "Brilho máximo para a iluminação da música.",
  "ui.minimum_seconds_between_light_updates": "Segundos mínimos entre as atualizações de luz.",
  "ui.player_light_pair_lights": "Luzes coloridas {number}",
  "ui.player_light_pair_lights_helper": "Escolha luzes compatíveis com cores para este player do Music Assistant. Limpe este campo ou o player para remover o par.",
  "ui.player_light_pair_player": "Player do Music Assistant {number}",
  "ui.player_light_pair_player_helper": "Escolha o player do Music Assistant para este par de luzes.",
  "ui.all": "Todos",
  "ui.all_genres": "Todos os gêneros",
  "ui.genres_and_styles": "Gêneros e estilos",
  "ui.compact_widget_mode": "Estilo de widget compacto",
  "ui.choose_when_compact_mode_uses_the_two_row_mobile_widget": "Escolha quando o modo compacto usará o widget mobile menor de duas linhas.",
  "ui.full": "Completo",
  "ui.mini_widget": "Mini widget",
  "ui.genre": "Gênero",
  "ui.mood_and_genre": "Humor e gênero",
  "ui.music_by_mood_and_genre": "Música por humor e gênero",
  "ui.optional_entity_for_the_power_button_leave_empty_to_stop_the_active_player": "Entidade opcional para o botão auxiliar. Deixe em branco para parar o player ativo.",
  "ui.optional_name_for_the_auxiliary_button": "Rótulo opcional mostrado como dica do botão auxiliar.",
  "ui.choose_the_auxiliary_button_icon": "Escolha o ícone exibido para o botão auxiliar.",
  "ui.choose_how_players_are_sorted": "Escolha a ordem padrão, alfabética ou personalizada dos players.",
  "ui.choose_music_assistant_players_to_hide_from_the_card": "Escolha os players do Music Assistant que nunca devem aparecer no cartão.",
  "ui.custom_order": "Ordem personalizada",
  "ui.no_visible_music_assistant_players_after_exclusions": "Todos os players do Music Assistant estão ocultos pela configuração de players excluídos.",
  "ui.set_custom_player_order": "Defina a ordem personalizada dos players. Espaços vazios são ignorados.",
  "ui.show_auxiliary_button_in_quick_actions": "Mostra este botão auxiliar na linha de Ações Rápidas.",
  "ui.power": "Energia",
  "ui.power_action_failed": "Falha na ação de energia",
  "ui.power_action_sent": "Ação de energia enviada",
  "ui.power_button": "Botão auxiliar",
  "ui.power_button_action": "Ação do botão auxiliar",
  "ui.power_button_entity": "Entidade do botão auxiliar",
  "ui.scene": "Cena",
  "ui.screensaver": "Proteção de tela",
  "ui.screensaver_buttons": "Botões da proteção de tela",
  "ui.screensaver_controls": "Controles da proteção de tela",
  "ui.screensaver_clock_mode": "Modo do relógio na proteção de tela",
  "ui.screensaver_clock_size": "Tamanho do relógio na proteção de tela",
  "ui.screensaver_clock_size_helper": "Ajusta o tamanho do relógio na proteção de tela do tablet sem mover a capa.",
  "ui.screensaver_clock_x": "Posição do relógio - ESQUERDA / DIREITA",
  "ui.screensaver_clock_x_helper": "Valores menores movem para a esquerda, valores maiores movem para a direita.",
  "ui.screensaver_clock_y": "Posição do relógio - CIMA / BAIXO",
  "ui.screensaver_clock_y_helper": "Valores menores movem para cima, valores maiores movem para baixo.",
  "ui.screensaver_message": "Mensagem da proteção de tela",
  "ui.screensaver_timeout": "Tempo limite da proteção de tela",
  "ui.script": "Script",
  "ui.short_optional_message_shown_on_the_screensaver": "Mensagem curta opcional mostrada na proteção de tela.",
  "ui.show_previous_next_controls_on_the_screensaver": "Mostra os botões de anterior e próximo na proteção de tela.",
  "ui.choose_which_buttons_appear_on_the_screensaver": "Escolha exatamente quais botões aparecem na proteção de tela, incluindo FLOW ASSISTANT, anterior e próximo.",
  "ui.show_a_calm_clock_artwork_display_after_idle_time": "Mostra um relógio calmo e a exibição da capa após um tempo de inatividade.",
  "ui.show_power_button_in_the_player_controls": "Mostra um botão auxiliar nas Ações Rápidas.",
  "ui.show_the_fullscreen_discovery_mode_in_actions": "Mostra o modo descoberta em tela cheia nas Ações.",
  "ui.smart_home": "Casa inteligente",
  "ui.soft_transition_time_for_music_lighting": "Tempo de transição suave para a iluminação da música.",
  "ui.stop_player": "Parar player",
  "ui.sync_selected_lights_to_the_current_artwork_color": "Sincroniza as luzes selecionadas com a cor atual da capa.",
  "ui.toggle": "Alternar",
  "ui.turn_on": "Ligar",
  "ui.choose_a_category_to_browse_provider_playlists": "Escolha uma categoria para navegar pelas playlists do provedor antes de tocar.",
  "ui.new_and_recommended": "Novidades e recomendações",
  "ui.provider_playlists": "Playlists do provedor",
  "ui.hotel_mode": "Modo Hotel",
  "ui.hotel_mode_helper": "Interface mínima segura para hotéis: apenas controles do player, volume, busca, navegação por capas e seleção de player.",
  "ui.style_and_genres": "Estilo e gêneros",
  "ui.card_id": "ID do Cartão",
  "ui.card_id_helper": "Slug único (letras, dígitos, '-', '_'). Defina isso ao executar vários painéis do HOMEii Flow no mesmo navegador para que cada painel mantenha seu próprio seletor de players, tema, layout e outras configurações do cartão. Deixe em branco para compartilhar o estado com todos os outros cartões HOMEii Flow neste navegador (o comportamento original).",
});

export default messages;