// Generated HOMEii Music Flow localization dictionary.
// Keep keys stable. Translate only the string values.
const messages = Object.freeze({
  "ui.action_menu_labels": "在图标下方显示操作名称",
  "ui.a_guided_music_wizard": "引导式音乐向导",
  "ui.a_radio_station": "一个电台",
  "ui.accent_color": "强调色",
  "ui.actions": "操作",
  "ui.actions_2": "操作",
  "ui.active_days": "生效日期",
  "ui.active_player_helper": "活动播放器辅助实体",
  "ui.active_player_helper_must_be_an_input_text_entity": "活动播放器辅助实体必须是 input_text",
  "ui.active_players": "活动播放器",
  "ui.add": "添加",
  "ui.add_to_queue": "加入队列",
  "ui.add_to_selection": "加入选择",
  "ui.added_to_liked": "已加入喜欢",
  "ui.added_to_music_assistant_liked": "已加入 Music Assistant 喜欢列表",
  "ui.added_to_queue": "已加入队列",
  "ui.added_to_studio_queue": "已加入音乐中枢队列",
  "ui.adds_motion_to_the_background_layers_subtle_keeps_it_calm_strong_is_noti": "为背景层添加动效。柔和模式较平静，强模式更明显，极强模式最有动感。",
  "ui.adds_to_the_current_volume_only_during_announcements_then_restores_the_p": "仅在播报期间提高当前音量，播报结束后恢复原有音量。",
  "ui.after_run": "执行后",
  "ui.album": "专辑",
  "ui.albums": "专辑",
  "ui.all_albums": "全部专辑",
  "ui.all_artists": "全部艺人",
  "ui.all_countries": "所有国家",
  "ui.all_player_groups_disconnected": "所有播放器分组已断开",
  "ui.all_players": "所有播放器",
  "ui.all_players_2": "所有播放器",
  "ui.all_podcasts": "全部播客",
  "ui.all_tracks": "全部歌曲",
  "ui.always_visible": "始终显示",
  "ui.announce": "播报",
  "ui.announce_to_all_players": "向所有播放器播报",
  "ui.announcement": "播报",
  "ui.announcement_failed_with_error": "播报失败{error}",
  "ui.announcement_language": "播报语言",
  "ui.announcement_presets": "播报预设",
  "ui.announcement_sent_to_player": "已向 {player} 发送播报",
  "ui.announcement_studio": "播报中心",
  "ui.announcement_studio_2": "播报中心",
  "ui.announcement_target": "播报目标",
  "ui.announcement_to_player_preview": "播报到 {player}：{preview}",
  "ui.announcement_volume_boost": "播报音量提升",
  "ui.announcements": "播报",
  "ui.appearance": "外观",
  "ui.alphabetical": "按字母排序",
  "ui.auxiliary_button": "辅助按钮",
  "ui.auxiliary_button_action": "辅助按钮动作",
  "ui.auxiliary_button_entity": "辅助按钮实体",
  "ui.auxiliary_button_icon": "辅助按钮图标",
  "ui.auxiliary_button_name": "辅助按钮名称",
  "ui.auxiliary_buttons": "辅助按钮",
  "ui.apply_group": "应用分组",
  "ui.apply_schedule": "应用计划",
  "ui.artist": "艺人",
  "ui.artist_radio": "艺人电台",
  "ui.artists": "艺人",
  "ui.artwork": "封面",
  "ui.artwork_swipe": "封面滑动",
  "ui.ascending": "升序",
  "ui.at_least_one_player_must_stay_selected": "至少保留一个已选播放器",
  "ui.australia": "澳大利亚",
  "ui.auto_chooses_mobile_or_tablet_based_on_actual_width": "自动模式会根据实际宽度选择手机或平板布局。",
  "ui.auto_cloud_default": "自动 / 云端默认",
  "ui.auto_extracts_colors_from_the_current_artwork_and_keeps_the_effect_subtl": "自动模式会从当前封面提取颜色并保持较柔和的效果；强模式会让配色更饱满、更明亮。",
  "ui.auto_leaves_home_assistant_cloud_voice_defaults_untouched_manual_choices": "自动模式会保留 Home Assistant Cloud 的默认语音设置；手动选择时会显式发送语言。",
  "ui.available": "可用",
  "ui.back": "返回",
  "ui.back_2": "返回",
  "ui.back_to_countries": "返回国家列表",
  "ui.back_to_queue": "返回队列",
  "ui.background_motion": "背景动效",
  "ui.behavior": "行为",
  "ui.browse_covers": "浏览封面",
  "ui.browse_playlists_artists_albums_and_radio": "浏览播放列表、艺人、专辑和电台",
  "ui.browser_players": "浏览器播放器",
  "ui.build_custom_mix": "生成自定义混音",
  "ui.building_studio_mix": "正在生成音乐中枢混音...",
  "ui.button": "按钮",
  "ui.by_mood": "按心情",
  "ui.cache_duration_in_milliseconds_for_selected_data_requests": "选定数据请求的缓存时长（毫秒）。",
  "ui.cache_ttl": "缓存 TTL",
  "ui.calm": "舒缓",
  "ui.canada": "加拿大",
  "ui.cancel": "取消",
  "ui.cancel_2": "取消",
  "ui.cancel_selection": "取消选择",
  "ui.card_configuration": "卡片配置",
  "ui.card_height": "卡片高度",
  "ui.card_height_in_pixels": "卡片高度（像素）。",
  "ui.card_settings_are_managed_from_the_visual_editor": "卡片设置由可视化编辑器管理",
  "ui.change_song": "切换歌曲",
  "ui.change_track": "切换歌曲",
  "ui.chill_mix": "轻松混音",
  "ui.choose_a_country_or_all_countries_to_browse_every_country_inside_the_rad": "选择一个国家，或选择“所有国家”以在电台标签中浏览全部国家。",
  "ui.choose_a_queue_position": "选择队列位置",
  "ui.choose_a_source_player": "选择源播放器",
  "ui.choose_a_target_player": "选择目标播放器",
  "ui.choose_at_least_one_player": "请至少选择一个播放器",
  "ui.choose_icons_text_or_both_for_the_footer": "选择底栏显示图标、文字或两者。",
  "ui.choose_music_assistant_players_only_the_in_card_pinning_list_shows_only": "仅选择 Music Assistant 播放器。卡片内固定列表只显示 Music Assistant 播放器，以避免混淆。",
  "ui.choose_one_clear_option": "请选择一个明确选项",
  "ui.choose_player": "选择播放器",
  "ui.choose_something_from_the_quick_shelf_or_tap_the_wand_for_a_random_playl": "从快捷栏选择内容，或点击魔杖获取随机播放列表。",
  "ui.choose_source": "选择音源",
  "ui.choose_target": "选择目标",
  "ui.choose_target_player": "选择目标播放器",
  "ui.choose_the_accent_color_for_the_mobile_layout": "为移动布局选择强调色。",
  "ui.choose_the_music": "选择音乐",
  "ui.choose_the_small_buttons_shown_under_the_song_title_timer_appears_first": "选择并排序歌曲标题下方显示的小按钮。",
  "ui.choose_the_source_first_playback_will_use_the_current_target": "请先选择音源，播放会发送到当前目标。",
  "ui.choose_where_to_play": "选择播放位置",
  "ui.choose_whether_artwork_swipe_changes_track_or_browses_covers": "选择封面滑动是切换歌曲还是浏览封面。",
  "ui.choose_whether_settings_are_controlled_from_the_in_card_ui_or_from_the_c": "选择由卡片内界面控制设置，还是由仪表板中的卡片配置控制。",
  "ui.choose_which_actions_appear_in_the_main_bar": "选择主栏中显示哪些操作。",
  "ui.choose_which_days_the_auto_night_mode_window_applies_to": "选择自动夜间模式生效的星期。",
  "ui.choose_which_icons_appear_in_the_quick_action_row": "选择快捷操作栏中显示哪些图标。",
  "ui.choose_which_players_appear_as_tiles_in_the_room": "选择哪些播放器以卡片形式显示在房间中。",
  "ui.choose_which_players_stay_in_the_current_control_selection": "选择哪些播放器保留在当前控制范围内。",
  "ui.choose_which_tabs_are_available_in_the_library_screen": "选择资料库页面中可用的标签。",
  "ui.choose_who_is_controlled": "选择控制对象",
  "ui.choosing_visual_disables_the_in_card_settings_screen": "选择“可视化编辑器”后会禁用卡片内设置界面。",
  "ui.clean_the_studio_wall": "整理音乐中枢面板",
  "ui.clear": "清除",
  "ui.clear_queue": "清空队列",
  "ui.clear_search": "清除搜索",
  "ui.clone_queue": "克隆队列",
  "ui.close": "关闭",
  "ui.collapse_compact_player": "收起紧凑播放器",
  "ui.compact_mode": "紧凑模式",
  "ui.configure_ready_made_announcement_phrases": "配置常用播报短语。",
  "ui.connect_this_device": "连接本机",
  "ui.connect_this_device_2": "连接此设备",
  "ui.connected": "已连接",
  "ui.connected_2": "已连接",
  "ui.connected_players": "已连接播放器",
  "ui.connected_players_2": "已连接播放器",
  "ui.connecting": "连接中",
  "ui.connecting_2": "连接中...",
  "ui.confirm": "确认",
  "ui.connection_and_behavior": "连接与行为",
  "ui.connects_directly_from_this_card_using_sendspin": "通过 Sendspin 直接从此卡片连接",
  "ui.continue": "继续",
  "ui.continue_2": "继续",
  "ui.continue_from_recent_music_assistant_activity": "从 Music Assistant 最近活动中继续播放。",
  "ui.continue_listening": "继续收听",
  "ui.continue_what_was_played_recently": "继续最近播放过的内容",
  "ui.control_whether_the_card_background_moves_gently_and_how_strong_the_moti": "控制卡片背景是否轻微移动，以及动效强度。",
  "ui.controlling": "当前控制",
  "ui.could_not_build_quick_mix_from_the_current_song": "无法根据当前歌曲生成快速混音",
  "ui.could_not_build_studio_mix": "无法生成音乐中枢混音",
  "ui.could_not_choose_media": "无法选择媒体内容",
  "ui.could_not_clone_the_queue": "无法克隆队列",
  "ui.could_not_find_music": "无法找到音乐",
  "ui.could_not_play_label": "无法播放：{label}",
  "ui.could_not_start_chill_mix": "无法启动轻松混音",
  "ui.could_not_start_playback": "无法开始播放",
  "ui.could_not_start_playback_2": "无法开始播放",
  "ui.could_not_start_playback_in_studio": "无法在音乐中枢中开始播放",
  "ui.could_not_start_quick_mix": "无法启动快速混音",
  "ui.could_not_start_radio_playback": "无法开始电台播放",
  "ui.could_not_transfer_the_queue": "无法转移队列",
  "ui.could_not_update_active_player_helper": "无法更新活动播放器辅助实体",
  "ui.create_schedule": "创建计划",
  "ui.current_path": "当前路径",
  "ui.custom": "自定义",
  "ui.dark": "深色",
  "ui.delete_scene": "删除场景",
  "ui.delete_schedule": "删除计划",
  "ui.descending": "降序",
  "ui.dictate": "语音输入",
  "ui.disabled": "关闭",
  "ui.disables_blur_animations_dynamic_backgrounds_and_heavy_shadows_recommend": "关闭模糊、动画、动态背景和重阴影。建议在 Nest Hub 或性能较弱的平板上开启。",
  "ui.disconnect": "断开连接",
  "ui.disconnect_all": "全部断开",
  "ui.disconnect_groups": "断开分组",
  "ui.disconnect_player_groups": "断开播放器分组",
  "ui.disconnect_this_device": "断开本机",
  "ui.disconnected": "已断开",
  "ui.disconnecting": "断开中",
  "ui.disconnecting_player_groups": "正在断开播放器分组...",
  "ui.discover": "发现",
  "ui.down": "下移",
  "ui.dynamic_theme": "动态主题",
  "ui.edit_schedule": "编辑计划",
  "ui.enable": "启用",
  "ui.enable_or_disable_the_footer_search_button": "启用或关闭底栏搜索按钮。",
  "ui.enable_or_disable_the_studio_button_in_the_footer_bar": "启用或关闭底栏中的音乐中枢按钮。",
  "ui.enable_the_floating_home_shortcut_button": "启用浮动主页快捷按钮。",
  "ui.enabled": "开启",
  "ui.enables_switching_to_local_liked_mode": "启用切换到本地喜欢模式。",
  "ui.end_time": "结束时间",
  "ui.excluded_players": "隐藏的播放器",
  "ui.energetic": "充满活力",
  "ui.energy_and_rhythm": "充满活力与节奏",
  "ui.enter_an_announcement_first": "请先输入播报内容",
  "ui.example_quiet_jazz_greek_music_workout": "例如：安静爵士、希腊音乐、运动",
  "ui.existing_content": "现有内容",
  "ui.expand_player": "展开播放器",
  "ui.extract_colors_from_the_current_artwork_and_apply_them_to_the_interface": "从当前封面提取颜色并应用到界面中。",
  "ui.extreme": "极强",
  "ui.fallback_for_setups_that_need_an_alternate_queue_service_path": "用于需要备用队列服务路径的环境。",
  "ui.fallback_mode": "基础模式",
  "ui.family_friendly": "适合全家收听",
  "ui.favorite": "收藏",
  "ui.favorite_action_failed": "收藏操作失败",
  "ui.favorite_action_sent": "收藏操作已发送",
  "ui.favorite_center": "收藏中心",
  "ui.favorite_center_2": "收藏中心",
  "ui.favorite_radio": "收藏电台",
  "ui.favorite_updated": "收藏已更新",
  "ui.favorites_and_liked_music": "收藏与喜欢的音乐",
  "ui.feature_detection_player_context_and_this_device_playback_tools": "功能检测、播放器上下文与本机播放工具。",
  "ui.find_music": "查找音乐",
  "ui.finding_music": "正在查找音乐",
  "ui.fixed": "固定",
  "ui.flow_mix": "FLOW 混音",
  "ui.font_scale": "字体缩放",
  "ui.font_size": "字体大小",
  "ui.footer_search": "底栏搜索",
  "ui.footer_style": "底栏样式",
  "ui.footer_style_2": "底栏样式",
  "ui.for_example_lovelace_home_or_any_other_home_assistant_path": "例如 /lovelace/home 或任何其他 Home Assistant 路径。",
  "ui.for_weaker_displays_turns_off_heavy_blur_animations_dynamic_theme_extrac": "适用于性能较弱的屏幕：关闭重模糊、动画、动态主题提取和背景动效。",
  "ui.france": "法国",
  "ui.free_style": "自由风格",
  "ui.free_style_quiet_jazz_greek_music_workout": "自由风格：安静爵士、希腊音乐、运动歌单……",
  "ui.fresh_start": "轻松开启一天",
  "ui.fresh_start_2": "轻松开启一天",
  "ui.fri": "周五",
  "ui.friendly_and_simple": "轻松简单",
  "ui.from": "从",
  "ui.general": "常规",
  "ui.general_and_display": "常规与显示",
  "ui.germany": "德国",
  "ui.global_scale_for_every_interface_font_1_is_the_default_size": "整个界面字体的全局缩放。1 为默认大小。",
  "ui.greece": "希腊",
  "ui.grid": "网格",
  "ui.group": "分组",
  "ui.group_cleared": "分组已清除",
  "ui.group_cleared_2": "分组已清除",
  "ui.group_speakers": "扬声器分组",
  "ui.group_speakers_2": "扬声器分组",
  "ui.group_updated": "分组已更新",
  "ui.group_volume": "分组音量",
  "ui.group_volume_up_energetic_mix": "分组、高音量、活力混音",
  "ui.grouped_players": "已分组播放器",
  "ui.hebrew": "希伯来语",
  "ui.history": "历史",
  "ui.history_tabs": "历史标签",
  "ui.home": "首页",
  "ui.home_party_night_presets": "家庭、派对、夜晚预设",
  "ui.home_path": "主页路径",
  "ui.home_scene_prepared": "家庭场景已准备好",
  "ui.home_shortcut": "主页快捷方式",
  "ui.home_shortcut_path": "主页快捷路径",
  "ui.icon_and_text": "图标和文字",
  "ui.icon_only": "仅图标",
  "ui.icon_plus_text": "图标 + 文字",
  "ui.idle": "空闲",
  "ui.idle_2": "空闲",
  "ui.in_card_ui": "卡片内界面",
  "ui.includes_the_custom_theme_mode_from_the_in_card_settings_screen": "包含卡片内设置界面里的自定义主题模式。",
  "ui.info": "信息",
  "ui.israel": "以色列",
  "ui.israeli": "以色列",
  "ui.italy": "意大利",
  "ui.items": "项",
  "ui.join_selected_players": "将所选播放器加入分组",
  "ui.kids": "儿童",
  "ui.language": "语言",
  "ui.larger_lyrics": "放大歌词",
  "ui.layout_adapted_to_height": "布局已按高度调整",
  "ui.layout_mode": "布局模式",
  "ui.leave_empty_if_the_card_should_use_home_assistant_only": "如果卡片只通过 Home Assistant 访问，请留空。",
  "ui.library": "资料库",
  "ui.library_2": "资料库",
  "ui.library_pages": "资料库页面",
  "ui.default_library_layout": "默认资料库布局",
  "ui.choose_how_library_pages_open_grid_or_list_can_still_be_changed_manually": "选择资料库页面打开时的布局。你仍然可以在资料库内手动切换网格/列表。",
  "ui.library_radio": "资料库电台",
  "ui.library_surprise": "资料库惊喜",
  "ui.library_tabs": "资料库标签",
  "ui.library_tabs_2": "资料库标签",
  "ui.light": "浅色",
  "ui.like": "喜欢",
  "ui.like_2": "喜欢",
  "ui.like_3": "喜欢",
  "ui.liked": "喜欢",
  "ui.liked_mode": "喜欢模式",
  "ui.liked_sync": "喜欢同步",
  "ui.list": "列表",
  "ui.listening": "正在聆听...",
  "ui.loading": "加载中...",
  "ui.loading_favorites": "正在加载收藏...",
  "ui.loading_library": "正在加载资料库...",
  "ui.loading_lyrics": "正在加载歌词...",
  "ui.loading_players": "正在加载播放器...",
  "ui.loading_queue": "正在加载队列...",
  "ui.loading_recent_items": "正在加载最近内容...",
  "ui.loading_schedules": "正在加载计划...",
  "ui.local": "本地",
  "ui.local_favorites": "本地热门",
  "ui.local_favorites_2": "本地热门",
  "ui.local_mode_is_only_meaningful_when_local_likes_are_enabled": "只有启用本地喜欢时，本地模式才有意义。",
  "ui.low_light_listening": "适合夜晚静听",
  "ui.low_volume_and_quiet_mix": "低音量、安静混音",
  "ui.lower_volume_mood": "低音量夜间氛围",
  "ui.lyrics": "歌词",
  "ui.lyrics_earlier": "歌词提前",
  "ui.lyrics_font_size": "歌词字号",
  "ui.lyrics_later": "歌词延后",
  "ui.lyrics_timing": "歌词时序",
  "ui.lyrics_unavailable_right_now": "当前无法获取歌词",
  "ui.ma_favorite_action_failed_with_error": "Music Assistant 收藏操作失败{error}",
  "ui.ma_interface_path": "MA 界面路径",
  "ui.main_bar": "主栏",
  "ui.main_bar_items": "主栏项目",
  "ui.main_bar_items_2": "主栏项目",
  "ui.main_opacity": "主界面透明度",
  "ui.mainly_relevant_on_larger_layouts": "主要用于较大布局。",
  "ui.matches_the_microphone_setting_from_the_in_card_settings_screen": "与卡片内设置界面的麦克风设置保持一致。",
  "ui.media": "媒体",
  "ui.media_2": "媒体",
  "ui.media_actions": "媒体操作",
  "ui.media_layout": "媒体布局",
  "ui.media_selected_target": "已选：{media} · 目标：{target}",
  "ui.menu": "菜单",
  "ui.message": "消息",
  "ui.microphone": "麦克风",
  "ui.microphone_2": "麦克风",
  "ui.microphone_is_disabled": "麦克风已禁用",
  "ui.missing_url": "缺少 URL",
  "ui.mobile": "手机",
  "ui.mon": "周一",
  "ui.mood_style_or_free_text": "心情、风格或自由输入",
  "ui.more_info": "更多信息",
  "ui.more_info_is_unavailable_for_this_player": "此播放器没有更多信息",
  "ui.morning": "清晨",
  "ui.morning_mix": "晨间混音",
  "ui.move_to_next": "移到下一首",
  "ui.move_to_position": "移动到指定位置",
  "ui.music": "音乐",
  "ui.music_assistant_required": "需要 Music Assistant",
  "ui.music_assistant_config_entry_id_if_you_want_direct_integration_lookup_th": "如果你希望通过 Home Assistant 直接关联 Music Assistant，可填写其配置条目 ID。",
  "ui.music_assistant_config_entry_was_not_found": "未找到 Music Assistant 配置条目",
  "ui.music_assistant_token": "Music Assistant 令牌",
  "ui.music_assistant_url": "Music Assistant 地址",
  "ui.music_hub": "音乐中心",
  "ui.music_hub_2": "音乐中心",
  "ui.mute": "静音",
  "ui.mute_command_failed": "静音命令失败",
  "ui.my_studio_scene": "我的音乐中枢场景",
  "ui.name_or_keyword": "名称或关键词",
  "ui.name_this_studio_scene": "为这个音乐中枢场景命名...",
  "ui.netherlands": "荷兰",
  "ui.new_schedule": "新建计划",
  "ui.new_wake_schedule": "新建唤醒计划",
  "ui.newest": "最新",
  "ui.next": "下一首",
  "ui.next_track_failed": "切换下一首失败",
  "ui.night": "夜晚",
  "ui.night_end_time": "夜间结束时间",
  "ui.night_mode": "夜间模式",
  "ui.night_mode_auto_window": "夜间模式自动 {start}-{end}",
  "ui.night_mode_days": "夜间模式日期",
  "ui.night_mode_is_always_on": "夜间模式始终开启",
  "ui.night_mode_is_off": "夜间模式已关闭",
  "ui.night_mode_is_off_until_you_choose_another_mode": "夜间模式将保持关闭，直到你选择其他模式。",
  "ui.night_mode_stays_on_until_you_choose_another_mode": "夜间模式将保持开启，直到你选择其他模式。",
  "ui.night_schedule_updated": "夜间计划已更新",
  "ui.night_start_time": "夜间开始时间",
  "ui.no_active_media": "当前没有活动媒体",
  "ui.no_active_players": "没有活动播放器",
  "ui.no_available_players": "没有可用播放器",
  "ui.no_content_found": "未找到内容",
  "ui.no_dynamic_player_groups_to_disconnect": "没有可断开的动态播放器分组",
  "ui.no_extra_ma_players": "没有额外的 MA 播放器",
  "ui.no_extra_ma_players_2": "没有额外的 MA 播放器",
  "ui.no_favorites_found": "未找到收藏内容。",
  "ui.no_liked_media_yet": "还没有喜欢的媒体内容",
  "ui.no_liked_tracks_to_play": "没有可播放的喜欢歌曲",
  "ui.no_light_entities_found": "未找到灯光实体。",
  "ui.no_lyrics_found": "未找到歌词",
  "ui.no_matching_content_was_found": "未找到匹配内容",
  "ui.no_media_found": "未找到媒体内容。",
  "ui.no_media_found_for_this_search": "这次搜索没有找到媒体内容。",
  "ui.no_mix_content_found": "未找到可用于混音的内容",
  "ui.no_music_assistant_players_were_found_check_music_assistant_and_media_pl": "需要 Music Assistant。请在 Home Assistant 中启用 Music Assistant 集成，并至少公开一个 Music Assistant media_player。其他 Home Assistant 媒体播放器会被隐藏。",
  "ui.no_music_assistant_players_were_found_for_pinning": "No Music Assistant players were found for pinning.",
  "ui.no_next_track_in_queue": "队列中没有下一首",
  "ui.no_player_groups_to_disconnect": "没有可断开的播放器分组",
  "ui.no_player_light_pairs_yet": "还没有播放器灯光配对。",
  "ui.no_player_selected": "未选择播放器",
  "ui.no_players_found": "未找到播放器",
  "ui.no_players_found_yet": "尚未发现播放器",
  "ui.no_playlists_found": "未找到播放列表",
  "ui.no_queue": "没有队列",
  "ui.no_queue_item_to_rebuild": "没有可重建的队列项",
  "ui.no_queue_to_clone": "没有可克隆的队列",
  "ui.no_radio_browser_countries_found": "未找到 Radio Browser 国家列表",
  "ui.no_radio_stations_found": "未找到电台",
  "ui.no_recent_listening_yet": "暂时还没有最近收听记录。",
  "ui.no_results": "没有结果",
  "ui.no_results_found": "未找到结果",
  "ui.no_saved_studio_scenes_yet": "还没有保存的音乐中枢场景。",
  "ui.no_scheduled_start_is_active": "当前没有启用定时启动",
  "ui.no_selected_tracks_to_play": "没有选中的可播放歌曲",
  "ui.no_sleep_timer_is_active": "当前没有启用睡眠定时器",
  "ui.no_speech_was_captured": "未捕获到语音",
  "ui.no_target_players_available": "没有可用的目标播放器",
  "ui.no_target_players_available_2": "没有可用的目标播放器",
  "ui.no_tts_service_or_entity_is_configured": "未配置 TTS 服务或实体",
  "ui.no_wake_schedules_yet": "还没有唤醒计划",
  "ui.none": "无",
  "ui.nothing_is_playing_right_now": "当前没有播放内容",
  "ui.nothing_playing": "当前没有播放内容",
  "ui.now_playing": "正在播放",
  "ui.now_playing_2": "正在播放",
  "ui.off": "关闭",
  "ui.off_2": "关闭",
  "ui.off_disables_it_on_keeps_it_active_and_auto_follows_the_configured_time": "关闭表示禁用，开启表示始终启用，自动表示按设定时间段生效。",
  "ui.oldest": "最早",
  "ui.on": "开启",
  "ui.one_tap_prepares_players_grouping_volume_and_content_save_your_own_curre": "一键准备播放器、分组、音量和内容，也可以把当前音乐中枢目标保存为本地场景。",
  "ui.only_actions_for_the_current_target_are_shown_here": "这里只显示当前目标可用的操作。",
  "ui.only_music_assistant_players_are_shown_here_browser_and_local_sendspin_p": "Only Music Assistant players are shown here. Browser and local Sendspin players are hidden to avoid confusion.",
  "ui.only_needed_when_using_a_direct_music_assistant_url": "仅在使用直连 Music Assistant 地址时需要。",
  "ui.opacity_for_popups_and_overlays": "弹窗和覆盖层的透明度。",
  "ui.opacity_for_the_main_card_background": "卡片主背景透明度。",
  "ui.open_full_interface": "打开完整界面",
  "ui.open_full_queue": "打开完整队列",
  "ui.open_interface_in": "界面打开方式",
  "ui.open_ma": "打开 MA",
  "ui.open_music_assistant": "打开 Music Assistant",
  "ui.open_music_assistant_2": "打开 Music Assistant？",
  "ui.open_music_assistant_on_this_device_to_activate_the_browser_player": "请在本机打开 Music Assistant 以启用浏览器播放器",
  "ui.open_player_picker": "打开播放器选择器",
  "ui.open_queue": "打开队列",
  "ui.open_saved_songs": "打开已保存歌曲",
  "ui.open_the_full_music_assistant_interface": "要打开完整的 Music Assistant 界面吗？",
  "ui.open_the_full_music_assistant_interface_2": "打开完整 Music Assistant 界面",
  "ui.opening_studio_library": "正在打开中枢资料库",
  "ui.opening_timers": "正在打开定时器",
  "ui.option": "选项",
  "ui.optional": "可选",
  "ui.optional_2": "可选",
  "ui.optional_entity_used_for_an_external_favorite_button": "用于外部收藏按钮的可选实体。",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for": "可选的 input_text 辅助实体。卡片会写入当前活动播放器的 entity_id，便于自动化和模板使用。",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for_2": "可选的 input_text 辅助实体。卡片会写入当前活动播放器的 entity_id，便于自动化和模板使用。",
  "ui.other": "其他",
  "ui.other_players": "其他播放器",
  "ui.party": "派对",
  "ui.path_used_when_opening_the_music_assistant_interface": "打开 Music Assistant 界面时使用的路径。",
  "ui.pause": "暂停",
  "ui.paused": "已暂停",
  "ui.per_device_in_card": "按设备 / 卡片内",
  "ui.performance_mode": "性能模式",
  "ui.performance_mode_for_weak_devices": "弱设备性能模式",
  "ui.performance_profile": "性能配置",
  "ui.performance_profile_helper": "选择卡片允许使用的视觉负载。Ultra Lite 会为性能较弱的设备降低透明度、模糊、动态封面背景和动效。",
  "ui.pick_a_mood_or_type_your_own_style_studio_will_search_music_assistant_an": "选择一种心情，或输入你自己的风格。音乐中枢会搜索 Music Assistant 并生成队列。",
  "ui.pinned": "已固定",
  "ui.pinned_players": "固定播放器",
  "ui.play": "播放",
  "ui.play_2": "播放",
  "ui.play_a_few_tracks_and_they_will_appear_here": "先播放几首歌，推荐内容就会出现在这里。",
  "ui.play_a_saved_list": "播放已保存列表",
  "ui.play_all": "全部播放",
  "ui.play_an_artist": "播放艺人作品",
  "ui.play_artwork_action": "封面操作",
  "ui.play_everywhere": "全屋播放",
  "ui.play_next": "下一首播放",
  "ui.play_next_and_clear_queue": "下一首播放并清空队列",
  "ui.play_now": "立即播放",
  "ui.play_now_and_clear_queue": "立即播放并清空队列",
  "ui.play_pause": "播放 / 暂停",
  "ui.play_queue_radio_or_remove_favorites_directly_from_studio": "直接在音乐中枢中播放、加入队列、开启电台或移除收藏。",
  "ui.play_selected": "播放所选",
  "ui.playback_command_failed": "播放命令失败",
  "ui.playback_command_failed_2": "播放命令失败",
  "ui.playback_started": "已开始播放",
  "ui.player": "播放器",
  "ui.player_2": "播放器",
  "ui.player_count_many": "{count} 个播放器",
  "ui.player_count_one": "1 个播放器",
  "ui.player_groups_could_not_be_disconnected": "无法断开播放器分组",
  "ui.player_is_pinned_from_settings": "该播放器已在设置中固定",
  "ui.player_is_ready": "播放器已就绪",
  "ui.player_is_ready_nothing_is_playing_right_now": "播放器已就绪，但当前没有播放内容",
  "ui.player_order": "播放器顺序",
  "ui.player_on_this_device": "本设备上的播放器",
  "ui.player_selected": "播放器已选中",
  "ui.player_settings_and_dsp_presets_stay_read_only_until_music_assistant_exp": "在 Music Assistant 为此播放器提供可靠 schema 之前，播放器设置和 DSP 预设将保持只读。",
  "ui.player_sort": "播放器排序",
  "ui.players": "播放器",
  "ui.players_queue_and_groups": "播放器、队列与分组",
  "ui.playing": "播放中",
  "ui.playing_a_random_playlist": "正在播放随机播放列表",
  "ui.playing_a_random_radio_station": "正在播放随机电台",
  "ui.playing_on": "当前播放设备",
  "ui.playing_on_2": "当前播放设备",
  "ui.playlist": "播放列表",
  "ui.playlists": "播放列表",
  "ui.podcast": "播客",
  "ui.podcasts": "播客",
  "ui.popup_opacity": "弹窗透明度",
  "ui.preset_message": "预设消息",
  "ui.previous": "上一首",
  "ui.primary": "主",
  "ui.primary_target": "主要目标",
  "ui.pro_tools": "专业工具",
  "ui.queue": "播放队列",
  "ui.queue_2": "播放队列",
  "ui.queue_action_failed": "队列操作失败",
  "ui.queue_action_is_not_available_for_this_player": "该播放器不支持此队列操作",
  "ui.queue_actions": "队列操作",
  "ui.queue_cleared": "队列已清空",
  "ui.queue_cleared_and_item_moved_next": "队列已清空，项目已移到下一首",
  "ui.queue_cloned": "队列已克隆",
  "ui.queue_cockpit": "队列控制台",
  "ui.queue_cockpit_2": "队列控制台",
  "ui.queue_is_empty": "播放队列为空",
  "ui.queue_is_unavailable_for_this_player": "该播放器暂不支持查看队列",
  "ui.queue_item": "队列项目",
  "ui.queue_item_id_is_not_ready_yet_refresh_the_queue_and_try_again": "队列项目 ID 尚未准备好，请刷新队列后重试。",
  "ui.queue_results": "队列结果",
  "ui.queue_transferred": "队列已转移",
  "ui.queues_refreshed": "队列已刷新",
  "ui.quick_actions": "快捷操作",
  "ui.quick_actions_2": "快捷操作",
  "ui.quick_mix": "快速混音",
  "ui.quick_mix_started": "快速混音已开始",
  "ui.quick_play": "快速播放",
  "ui.radio": "电台",
  "ui.radio_browser": "Radio Browser",
  "ui.radio_browser_countries": "Radio Browser 国家",
  "ui.radio_browser_country": "Radio Browser 国家",
  "ui.radio_browser_country_2": "Radio Browser 国家",
  "ui.radio_mode_is_not_available_for_this_media_type": "此媒体类型不支持电台模式",
  "ui.radio_mode_started": "电台模式已启动",
  "ui.radio_station_changed": "电台已切换",
  "ui.radio_stations": "电台频道",
  "ui.random": "随机",
  "ui.random_gentle_morning_mix": "随机轻柔晨间混音",
  "ui.random_playlist": "随机播放列表",
  "ui.random_radio": "随机电台",
  "ui.ready": "就绪",
  "ui.ready_to_play": "准备播放",
  "ui.recent": "最近",
  "ui.recent_continue": "最近 / 继续",
  "ui.recent_listening": "最近收听",
  "ui.recent_track": "最近播放歌曲",
  "ui.recently_added": "最近新增",
  "ui.recently_played": "最近播放",
  "ui.recently_played_2": "最近播放",
  "ui.recommendations_will_appear_once_homeii_flow_sees_your_queue_or_recent_l": "当 HOMEii Flow 检测到你的队列或最近收听记录后，这里会显示推荐内容。",
  "ui.recommended": "推荐",
  "ui.recommended_format_hh_mm_such_as_06_00_crossing_midnight_is_supported": "推荐格式：HH:MM，例如 06:00，支持跨午夜。",
  "ui.recommended_format_hh_mm_such_as_22_00": "推荐格式：HH:MM，例如 22:00。",
  "ui.recommended_playlist": "推荐播放列表",
  "ui.recommended_track": "推荐歌曲",
  "ui.reconnects_when_you_return_to_this_dashboard": "回到此仪表板后会自动重连",
  "ui.refresh": "刷新",
  "ui.remember_as_this_device": "记住为本机",
  "ui.remove": "移除",
  "ui.remove_from_selection": "从选择中移除",
  "ui.removed_from_liked": "已从喜欢中移除",
  "ui.removed_from_music_assistant_liked": "已从 Music Assistant 喜欢列表移除",
  "ui.reorder_queue": "重排队列",
  "ui.repeat": "循环",
  "ui.reset": "重置",
  "ui.reset_lyrics_font_size": "重置歌词字号",
  "ui.reset_lyrics_timing": "重置歌词时序",
  "ui.results": "结果",
  "ui.rtl": "RTL",
  "ui.sat": "周六",
  "ui.save_current_target": "保存当前目标",
  "ui.save_schedule": "保存计划",
  "ui.scene_players_are_not_available": "场景中的播放器当前不可用",
  "ui.scene_presets": "场景预设",
  "ui.scene_presets_2": "场景预设",
  "ui.scenes": "场景",
  "ui.scheduled_start": "定时启动",
  "ui.scheduled_start_activated_label": "定时启动已启用：{label}",
  "ui.scheduled_start_cleared": "定时启动已清除",
  "ui.scheduled_start_failed": "定时启动失败",
  "ui.scheduled_start_saved": "定时启动已保存",
  "ui.scheduled_starts_active_count": "{count} 个定时启动正在生效",
  "ui.schedules": "计划",
  "ui.search": "搜索",
  "ui.search_and_choose_play_next_add_radio_or_like": "搜索后可选择播放、下一首、添加、电台或喜欢。",
  "ui.search_everything": "搜索全部内容...",
  "ui.search_failed": "搜索失败",
  "ui.search_in_queue": "在队列中搜索",
  "ui.search_queue_and_library": "搜索队列和资料库...",
  "ui.search_the_library": "搜索资料库...",
  "ui.search_tracks_albums_artists_and_playlists": "搜索歌曲、专辑、艺人和播放列表",
  "ui.searching": "搜索中...",
  "ui.searching_library": "正在搜索资料库...",
  "ui.searching_smart_selection": "正在搜索智能选择...",
  "ui.seek": "拖动进度",
  "ui.select": "选择",
  "ui.select_lights": "选择灯或灯组",
  "ui.select_player": "选择播放器",
  "ui.select_2": "选择",
  "ui.select_a_player_first": "请先选择播放器",
  "ui.select_at_least_one_studio_player": "请至少选择一个音乐中枢播放器",
  "ui.select_at_least_two_players_to_create_a_group": "请至少选择两个播放器来创建分组",
  "ui.selected": "已选中",
  "ui.selected_music": "已选音乐",
  "ui.selected_player": "已选播放器",
  "ui.selected_player_2": "已选播放器",
  "ui.selected_player_3": "已选播放器",
  "ui.selected_players_at_comfortable_volume": "已选播放器，舒适音量",
  "ui.selected_playlist": "已选播放列表",
  "ui.send_a_short_voice_message_or_announcement_url": "发送简短语音消息或播报链接。",
  "ui.send_a_voice_message": "发送语音消息",
  "ui.send_announcement": "发送播报",
  "ui.sendspin_and_diagnostics": "Sendspin 与诊断",
  "ui.set_sleep_timer": "设置睡眠定时器",
  "ui.set_volume": "设置音量",
  "ui.set_the_visual_order_of_quick_actions": "设置显示顺序。只显示已勾选的快捷操作；未勾选的项目会被忽略。",
  "ui.settings": "设置",
  "ui.settings_section_announcements": "公告",
  "ui.settings_section_display": "显示屏",
  "ui.settings_section_music_assistant": "Music Assistant",
  "ui.settings_section_players_library": "播放器和图书馆",
  "ui.settings_section_quick_actions_bar": "快速操作和栏",
  "ui.settings_section_smart_home": "智能家居和屏幕保护程序",
  "ui.settings_section_voice_assistant": "语音助理",
  "ui.settings_source": "设置来源",
  "ui.show_ma_button": "显示 MA 按钮",
  "ui.show_or_hide_the_inline_next_track_row_in_now_playing": "显示或隐藏正在播放界面中的“即将播放”行。",
  "ui.show_theme_toggle": "显示主题切换",
  "ui.show_up_next": "显示即将播放",
  "ui.show_up_next_2": "显示即将播放",
  "ui.shows_a_standalone_compact_player_tile_with_artwork_basic_controls_volum": "显示一个独立的紧凑播放器卡片，包含封面、基础控制、音量和展开操作。",
  "ui.shuffle": "随机播放",
  "ui.shuffle_all": "全部随机",
  "ui.shuffle_favorites": "随机播放收藏",
  "ui.shuffle_play": "随机播放",
  "ui.skipped_to_up_next": "已切换到下一首",
  "ui.sleep_timer": "睡眠定时器",
  "ui.sleep_timer_2": "睡眠定时器",
  "ui.sleep_timer_active_remaining": "睡眠定时器运行中：剩余 {remaining}",
  "ui.sleep_timer_added_minutes": "已为定时器增加 {minutes} 分钟",
  "ui.sleep_timer_and_morning_playback": "睡眠定时与晨间播放",
  "ui.sleep_timer_and_scheduled_playback": "睡眠定时与定时播放",
  "ui.sleep_timer_cleared": "睡眠定时器已清除",
  "ui.sleep_timer_finished": "睡眠定时器已结束",
  "ui.sleep_timer_presets": "睡眠定时预设",
  "ui.sleep_timer_set_for_15_minutes": "睡眠定时器已设为 15 分钟",
  "ui.sleep_timer_set_minutes": "睡眠定时器已设为 {minutes} 分钟",
  "ui.sleep_timer_updated_minutes": "睡眠定时器已更新为 {minutes} 分钟",
  "ui.smaller_lyrics": "缩小歌词",
  "ui.smart": "智能",
  "ui.smart_mix": "智能混音",
  "ui.smart_mix_builder": "智能混音生成器",
  "ui.smart_voice_selection": "智能语音选择",
  "ui.soft_and_relaxed": "柔和放松",
  "ui.soft_relaxed_music": "柔和轻松的音乐",
  "ui.some_players_could_not_be_stopped_or_cleared": "部分播放器未能停止或清空",
  "ui.songs_around_an_artist": "围绕艺人的歌曲",
  "ui.sort": "排序",
  "ui.sort_ascending": "升序",
  "ui.sort_descending": "降序",
  "ui.source_queue": "源队列",
  "ui.spain": "西班牙",
  "ui.speak_to_target_players": "向目标播放器发送语音播报",
  "ui.start_radio_mode": "启动电台模式",
  "ui.start_time": "开始时间",
  "ui.start_time_2": "开始时间",
  "ui.started_on_selected_player": "已在所选播放器上开始播放",
  "ui.starting_a_chill_mix": "正在启动轻松混音",
  "ui.starting_quick_mix": "正在启动快速混音...",
  "ui.stations": "个电台",
  "ui.stay_active": "保持启用",
  "ui.stays_active": "保持启用",
  "ui.stop_all": "全部停止",
  "ui.stop_all_players": "停止所有播放器",
  "ui.stop_command_failed": "停止命令失败",
  "ui.stop_playback_clear_queues_and_disconnect_groups": "停止播放、清空队列并断开分组",
  "ui.stopped_all_players_cleared_playlists_and_disconnected_groups": "已停止所有播放器、清空列表并断开分组",
  "ui.stops_this_browser_player": "停止此浏览器播放器",
  "ui.strong": "强",
  "ui.studio": "音乐中枢",
  "ui.studio_closed": "音乐中枢已关闭",
  "ui.studio_media_action_failed": "音乐中枢媒体操作失败",
  "ui.studio_mix_started": "音乐中枢混音已开始",
  "ui.studio_opened": "音乐中枢已打开",
  "ui.studio_pro": "音乐中枢 Pro",
  "ui.studio_pro_2": "音乐中枢 Pro",
  "ui.studio_scene": "音乐中枢场景",
  "ui.studio_scene_deleted": "音乐中枢场景已删除",
  "ui.studio_scene_saved": "音乐中枢场景已保存",
  "ui.studio_scene_was_not_found": "未找到该音乐中枢场景",
  "ui.studio_search": "音乐中枢搜索",
  "ui.studio_shortcut": "音乐中枢快捷方式",
  "ui.subtle": "柔和",
  "ui.sun": "周日",
  "ui.surprise_me": "给我惊喜",
  "ui.sync": "同步",
  "ui.sync_lyrics": "同步歌词",
  "ui.tablet": "平板",
  "ui.tap_to_start_a_sleep_timer": "点击以启动睡眠定时器",
  "ui.target_players": "目标播放器",
  "ui.target_queue": "目标队列",
  "ui.text_announcements_use_home_assistant_tts_into_the_selected_music_assist": "文本播报会通过 Home Assistant TTS 发送到所选的 Music Assistant 播放器；链接播报则使用 Music Assistant 的播报播放功能。",
  "ui.text_only": "仅文字",
  "ui.text_tone": "文字色调",
  "ui.theme": "主题",
  "ui.theme_2": "主题",
  "ui.theme_mode": "主题模式",
  "ui.theme_toggle": "主题切换",
  "ui.theme_toggle_2": "主题切换",
  "ui.this_device": "本机",
  "ui.this_device_2": "此设备",
  "ui.this_device_player_connected": "本机播放器已连接",
  "ui.this_device_player_disconnected": "本机播放器已断开",
  "ui.thu": "周四",
  "ui.timer": "定时器",
  "ui.timer_active_remaining": "定时器运行中：剩余 {remaining}",
  "ui.timers": "定时器",
  "ui.to": "到",
  "ui.today": "今天",
  "ui.track": "歌曲",
  "ui.track_lyrics": "歌曲歌词",
  "ui.tracks": "歌曲",
  "ui.transfer_clone_inspect_or_clear_queues_without_hiding_the_studio": "无需离开音乐中枢即可转移、克隆、查看或清空队列。",
  "ui.transfer_is_unavailable_while_a_pinned_player_is_configured": "配置固定播放器后，暂不支持转移播放",
  "ui.transfer_queue": "转移队列",
  "ui.transfer_queue_2": "转移队列",
  "ui.transfer_queue_3": "转移队列",
  "ui.try_again": "重试",
  "ui.tts_entity": "TTS 实体",
  "ui.tts_entity_used_by_the_announcement_screen": "播报界面使用的 TTS 实体。",
  "ui.tts_language": "TTS 语言",
  "ui.tue": "周二",
  "ui.turkey": "土耳其",
  "ui.turn_off": "关闭",
  "ui.turns_off_after_run": "执行后关闭",
  "ui.turns_off_heavy_visuals_so_the_card_runs_smoother_on_nest_hub_older_tabl": "关闭高负载视觉效果，让卡片在 Nest Hub、旧平板和性能较弱的屏幕上运行得更流畅。",
  "ui.type_a_free_style_first": "请先输入自由风格",
  "ui.type_an_announcement": "输入播报内容...",
  "ui.type_anything": "随意输入",
  "ui.type_what_should_be_announced": "输入要播报的内容...",
  "ui.ungroup": "取消分组",
  "ui.ungroup_2": "取消分组",
  "ui.united_kingdom": "英国",
  "ui.united_states": "美国",
  "ui.unknown": "未知",
  "ui.up": "上移",
  "ui.move_down": "下移",
  "ui.move_up": "上移",
  "ui.up_next": "即将播放",
  "ui.up_next_2": "即将播放",
  "ui.up_next_title": "即将播放：{title}",
  "ui.upbeat_and_moving": "轻快有动感",
  "ui.use_any_home_assistant_path_example_lovelace_home": "可使用任意 Home Assistant 路径，例如：/lovelace/home",
  "ui.use_current_view_for_home_button": "主页按钮使用当前视图",
  "ui.use_expand_to_open_the_full_player": "使用展开按钮打开完整播放器",
  "ui.uses_the_same_base_country_list_shown_in_the_in_card_settings_screen": "使用与卡片内设置界面相同的基础国家列表。",
  "ui.visible_tiles": "显示卡片",
  "ui.visible_tiles_2": "显示卡片",
  "ui.visual_editor": "可视化编辑器",
  "ui.voice_input_failed": "语音输入失败",
  "ui.voice_input_is_not_supported_on_this_device": "此设备不支持语音输入",
  "ui.voice_search": "语音搜索",
  "ui.voice_search_failed": "语音搜索失败",
  "ui.voice_search_is_not_supported_on_this_device": "此设备不支持语音搜索",
  "ui.volume": "音量",
  "ui.volume_and_player_target": "音量与播放器目标",
  "ui.volume_boost": "音量增强",
  "ui.volume_control_large_screen_only": "音量控制（仅大屏可用）",
  "ui.volume_down": "降低音量",
  "ui.volume_mode": "音量模式",
  "ui.volume_presets": "音量预设",
  "ui.volume_step_between_1_and_10_percent_default_5": "音量步进范围为 1% 到 10%。默认 5%。",
  "ui.volume_step_buttons": "音量 +/- 按钮",
  "ui.volume_step_percent": "音量步进",
  "ui.volume_up": "提高音量",
  "ui.waiting_for_this_device_player": "正在等待本机播放器...",
  "ui.wake": "唤醒",
  "ui.wake_schedules": "唤醒计划",
  "ui.wed": "周三",
  "ui.week": "本周",
  "ui.what_would_you_like_to_listen_to": "你想听点什么？",
  "ui.will_play_next": "将作为下一首播放",
  "ui.will_play_next_in_studio": "将在音乐中枢中下一首播放",
  "ui.worldwide_popular": "全球热门",
  "ui.add_player_light_pair": "添加配对",
  "ui.ambient_light": "氛围灯光",
  "ui.ambient_light_brightness": "灯光亮度",
  "ui.ambient_light_cooldown": "灯光更新间隔",
  "ui.ambient_light_entities": "默认彩灯",
  "ui.ambient_light_player_map": "播放器到灯光映射",
  "ui.ambient_light_player_map_helper": "使用下方的播放器和彩灯选择器。每一行填写完整后会形成一个配对；清空播放器或灯光即可移除该配对。",
  "ui.ambient_light_transition": "灯光过渡",
  "ui.analog": "指针式",
  "ui.choose_only_the_lights_that_should_follow_the_music": "当没有针对播放器的专属配对时，只选择应跟随音乐变化的彩灯。",
  "ui.digital": "数字式",
  "ui.discover_albums": "发现专辑",
  "ui.discover_music": "发现",
  "ui.discover_subtitle": "推荐的歌单、专辑和电台。",
  "ui.discovery": "音乐发现",
  "ui.discovery_failed": "发现模式失败",
  "ui.discovery_mode": "发现模式",
  "ui.discovery_started": "发现模式已开始：{mood}",
  "ui.maximum_brightness_for_music_lighting": "音乐灯光的最大亮度。",
  "ui.minimum_seconds_between_light_updates": "两次灯光更新之间的最短间隔（秒）。",
  "ui.player_light_pair_lights": "彩灯 {number}",
  "ui.player_light_pair_lights_helper": "为这个 Music Assistant 播放器选择支持颜色的灯。清空此字段或播放器即可移除该配对。",
  "ui.player_light_pair_player": "Music Assistant 播放器 {number}",
  "ui.player_light_pair_player_helper": "为这个灯光配对选择 Music Assistant 播放器。",
  "ui.all": "全部",
  "ui.all_genres": "所有流派",
  "ui.genres_and_styles": "流派和风格",
  "ui.compact_widget_mode": "紧凑小组件样式",
  "ui.choose_when_compact_mode_uses_the_two_row_mobile_widget": "选择紧凑模式何时使用较小的两行移动小组件。",
  "ui.full": "完整",
  "ui.mini_widget": "迷你小组件",
  "ui.genre": "流派",
  "ui.mood_and_genre": "心情与流派",
  "ui.music_by_mood_and_genre": "按心情和流派选音乐",
  "ui.optional_entity_for_the_power_button_leave_empty_to_stop_the_active_player": "辅助按钮的可选实体。留空时将停止当前活动播放器。",
  "ui.power": "电源",
  "ui.power_action_failed": "电源操作失败",
  "ui.power_action_sent": "电源操作已发送",
  "ui.power_button": "辅助按钮",
  "ui.power_button_action": "辅助按钮动作",
  "ui.power_button_entity": "辅助按钮实体",
  "ui.scene": "场景",
  "ui.screensaver": "屏保",
  "ui.screensaver_clock_mode": "屏保时钟模式",
  "ui.screensaver_clock_size": "屏保时钟大小",
  "ui.screensaver_clock_size_helper": "调整平板屏保时钟的大小，不会移动封面。",
  "ui.screensaver_clock_x": "时钟位置 - 左 / 右",
  "ui.screensaver_clock_x_helper": "数值越小越靠左，数值越大越靠右。",
  "ui.screensaver_clock_y": "时钟位置 - 上 / 下",
  "ui.screensaver_clock_y_helper": "数值越小越靠上，数值越大越靠下。",
  "ui.screensaver_message": "屏保消息",
  "ui.screensaver_timeout": "屏保等待时间",
  "ui.script": "脚本",
  "ui.short_optional_message_shown_on_the_screensaver": "显示在屏保上的简短可选消息。",
  "ui.show_a_calm_clock_artwork_display_after_idle_time": "空闲一段时间后显示柔和的时钟与封面屏保。",
  "ui.show_power_button_in_the_player_controls": "在快捷操作中显示辅助按钮。",
  "ui.show_the_fullscreen_discovery_mode_in_actions": "在“操作”中显示全屏发现模式。",
  "ui.smart_home": "智能家居",
  "ui.soft_transition_time_for_music_lighting": "音乐灯光的柔和过渡时间。",
  "ui.stop_player": "停止播放器",
  "ui.sync_selected_lights_to_the_current_artwork_color": "将选中的灯光同步为当前封面颜色。",
  "ui.toggle": "切换",
  "ui.turn_on": "打开",
  "ui.choose_a_category_to_browse_provider_playlists": "播放前先选择一个分类浏览服务商播放列表。",
  "ui.new_and_recommended": "新品与推荐",
  "ui.provider_playlists": "服务商播放列表",
  "ui.clean_all": "清除全部",
  "ui.clean_all_confirm_action": "清除全部",
  "ui.clean_all_confirm_copy": "这会断开所有活动播放器、停止播放并清空它们的队列。继续吗？",
  "ui.clean_all_confirm_title": "清除所有播放器？",
  "ui.repeat_all": "全部循环",
  "ui.repeat_off": "关闭循环",
  "ui.repeat_one": "单曲循环",
  "ui.scales_interface_icons_without_changing_button_sizes": "缩放界面图标，不改变按钮大小或布局。",
  "ui.assist_agent": "Assist 助手",
  "ui.assist_agent_id": "Assist 助手 ID",
  "ui.assist_only": "仅 Assist",
  "ui.default_assist_agent": "默认 Home Assistant Assist",
  "ui.hybrid_handles_music_locally_and_sends_unknown_commands_to_assist": "推荐：音乐命令会在选中的播放器上本地执行。卡片无法理解的内容会发送给 Home Assistant Assist。",
  "ui.hybrid_music_plus_assist": "混合：音乐 + Assist",
  "ui.icon_size": "图标大小",
  "ui.music_only": "仅音乐",
  "ui.music_plus_assist": "音乐 + Assist",
  "ui.optional_assist_agent_id_leave_empty_for_home_assistant_default": "可选的 Assist 助手 ID。留空将使用 Home Assistant 默认 Assist 助手。",
  "ui.optional_assist_agent_leave_empty_for_home_assistant_default": "可选。除非你有多个 Assist 助手并希望此卡片使用指定助手，否则保持默认即可。",
  "ui.show_a_push_to_talk_button_for_music_and_assist_commands": "显示用于音乐命令和 Assist 兜底的按住说话按钮。",
  "ui.show_home_inside_quick_actions": "在快捷操作中显示主页，而不是浮动按钮。",
  "ui.show_plus_minus_buttons_next_to_the_volume_slider": "在音量滑块旁显示加号和减号按钮。",
  "ui.speak_voice_assistant_responses_out_loud": "在支持时通过此浏览器朗读识别到的回复。",
  "ui.flow_assistant": "FLOW ASSISTANT",
  "ui.voice_assistant": "语音助手",
  "ui.voice_assistant_disabled": "语音助手已禁用",
  "ui.voice_assistant_listening": "正在聆听命令...",
  "ui.voice_assistant_mode": "语音助手模式",
  "ui.voice_command_executed": "语音命令已执行",
  "ui.voice_command_completed_action": "完成：{action}",
  "ui.voice_command_failed": "语音命令失败",
  "ui.voice_command_no_player": "请选择播放器，或说出播放器名称。",
  "ui.voice_command_not_understood": "我无法理解这个命令。",
  "ui.voice_command_sent": "语音命令已发送",
  "ui.voice_done_status": "完成",
  "ui.voice_error_status": "需要注意",
  "ui.voice_feedback": "语音反馈",
  "ui.voice_group_connect_needs_players": "请说出至少两个播放器名称，或先选择一个播放器再说出另一个。",
  "ui.voice_group_connected_players": "已将 {primary} 与 {members} 连接",
  "ui.voice_group_disconnect_needs_player": "请说出要断开的播放器组。",
  "ui.voice_group_disconnected_player": "已断开 {player} 的组",
  "ui.voice_language_is_not_supported": "此浏览器不支持所选语音识别语言。",
  "ui.voice_match_not_confident": "我找到了 {title}，但它与“{query}”的匹配度不够高。请再说一次歌曲和艺人。",
  "ui.voice_music_searching": "正在搜索音乐：{query}",
  "ui.voice_playing_result": "正在播放 {title}",
  "ui.voice_queue_transfer_needs_players": "请说出来源和目标播放器，例如：transfer queue from Living Room to Kitchen。",
  "ui.voice_queue_transferred_between": "队列已从 {source} 转移到 {target}",
  "ui.voice_starting_playback": "正在开始播放 {title}...",
  "ui.voice_processing_status": "正在处理命令...",
  "ui.voice_ready_status": "就绪",
  "ui.voice_recognition_network_failed": "语音识别服务不可用。麦克风权限可能没有问题；请检查浏览器、VPN、DNS、防火墙或网络。",
  "ui.voice_response": "响应",
  "ui.voice_response_will_appear_here": "响应会显示在这里。",
  "ui.voice_transcript": "转录",
  "ui.voice_listening_status": "正在聆听...",
  "ui.waiting_for_speech": "正在等待语音...",
  "ui.microphone_permission_or_browser_blocked": "浏览器阻止了语音识别。请检查麦克风和浏览器语音设置。",
  "ui.screensaver_controls": "屏保控制",
  "ui.show_previous_next_controls_on_the_screensaver": "在屏保上显示上一首和下一首按钮。",
  "ui.optional_name_for_the_auxiliary_button": "显示为辅助按钮提示的可选标签。",
  "ui.choose_the_auxiliary_button_icon": "选择辅助按钮显示的图标。",
  "ui.choose_how_players_are_sorted": "选择默认、按字母或自定义播放器顺序。",
  "ui.choose_music_assistant_players_to_hide_from_the_card": "选择不应出现在卡片中的 Music Assistant 播放器。",
  "ui.custom_order": "自定义顺序",
  "ui.default_order": "默认顺序",
  "ui.no_visible_music_assistant_players_after_exclusions": "所有 Music Assistant 播放器都被隐藏播放器设置隐藏。",
  "ui.set_custom_player_order": "设置自定义播放器顺序。空槽位会被忽略。",
  "ui.show_auxiliary_button_in_quick_actions": "在快捷操作栏中显示此辅助按钮。",
  "ui.screensaver_buttons": "Screensaver buttons",
  "ui.choose_which_buttons_appear_on_the_screensaver": "Choose exactly which buttons appear on the screensaver, including FLOW ASSISTANT, previous and next.",
  "ui.hotel_mode": "酒店模式",
  "ui.hotel_mode_helper": "适合酒店的极简安全界面：仅保留播放器控制、音量、搜索、封面浏览和播放器选择。",
  "ui.style_and_genres": "风格和流派",
  "ui.card_id": "Card ID",
  "ui.card_id_helper": "Unique slug (letters, digits, '-', '_'). Set this when running multiple HOMEii Flow dashboards in the same browser so each dashboard keeps its own player picker, theme, layout, and other in-card settings. Leave blank to share state with every other HOMEii Flow card in this browser (the original behaviour).",
});

export default messages;
